### ISSUE TITLE
Mock is actually not needed

### ISSUE THREAD

**Issue by mcepl** [networktocode/ntc-templates#1000]
I don't know how it to `poetry.lock`, but it is certainly not needed for this package (there is nothing imported from there).

**Comment by itdependsnetworks** [comment]
I am not sure the question? Giving the timeline, closing pending further details.

**Comment by mcepl** [comment]
I was talking about

https://github.com/networktocode/ntc-templates/blob/e147c0272a454b6458cfac17e62bd59b636a26b6/poetry.lock#L640
