### ISSUE TITLE
cisco_xr_admin_show_inventory no parse correctly in several models

### ISSUE THREAD

**Issue by i-m-d** [networktocode/ntc-templates#1048]
##### ISSUE TYPE
 - Bug Report
 
##### TEMPLATE USING
 cisco_xr_admin_show_inventory.textfsm

Value NAME (.*)
Value DESCR (.*)
Value PID (([\S+]+|.*))
Value VID (.*)
Value SN ([\w+\d+]+)

Start
  ^NAME:\s+"${NAME}",\s+DESCR:\s+"${DESCR}"
  ^PID:\s+${PID}.*,.*VID:\s+${VID},.*SN:\s+${SN} -> Record
  ^PID:\s+,.*VID:\s+${VID},.*SN: -> Record
  ^PID:\s+${PID}.*,.*VID:\s+${VID},.*SN: -> Record
  ^PID:\s+,.*VID:\s+${VID},.*SN:\s+${SN} -> Record
  ^PID:\s+${PID}.*,.*VID:\s+${VID}.*
  ^PID:\s+,.*VID:\s+${VID}.*
  ^.*SN:\s+${SN} -> Record
  ^.*SN: -> Record

##### SAMPLE COMMAND OUTPUT
[{'name': '', 'descr': '', 'pid': '', 'vid': '', 'sn': 'FOC23XXXXXX'},
 {'name': '', 'descr': '', 'pid': '', 'vid': '', 'sn': 'POXXXXXXXXX'},
 {'name': '', 'descr': '', 'pid': '', 'vid': '', 'sn': 'POXXXXXXXXX'}]

##### SUMMARY
The template works correctly in models:

ASR 9006 4 Line Card Slot Chassis

The template DOES NOT work correctly in models:

ASR 9901 Chassis version 6.6.3
ASR 9906 Chassis version 6.7.3

In these models there is a white space at the beginning of the lines, so DO NOT start with ^NAME or ^PID

##### STEPS TO REPRODUCE
Output from ASR 9901 and 9906:
```
#admin show inventory
Fri Dec 24 13:42:23.980 CET

 Name: Rack 0                Descr: ASR 9906 4 Line Card Slot Chassis
 PID: ASR-9906               VID: V01                   SN: FOXXXXXXXX

 Name: 0/0                   Descr: 24X10G/1G Packet Transport Optimized LC
 PID: A9K-24X10GE-1G-TR      VID: V01                   SN: FOCYYYYYYYY

 Name: 0/1                   Descr: 48X10G/1G Packet Transport Optimized LC
 PID: A9K-48X10GE-1G-TR      VID: V01                   SN: FOC2XXXXXX
```

NOTE: i hope the white space before NAME and PID was clear

**Comment by itdependsnetworks** [comment]
Let's track in #1118
