### ISSUE TITLE
cisco_ios_show_interface_transceiver doesn't account for current measurement

### ISSUE THREAD

**Issue by tdco0** [networktocode/ntc-templates#1057]
##### ISSUE TYPE

 - Bug Report
 - 
##### TEMPLATE USING

```
Value IFACE (\w+\d+\/\S+)
Value TEMPERATURE (\d+.\d+)
Value VOLTAGE (\d+.\d+)
Value TX_PWR (\S+)
Value RX_PWR (\S+)

Start
  ^${IFACE}\s+${TEMPERATURE}\s+${VOLTAGE}\s+${TX_PWR}\s+${RX_PWR}\s+ -> Record
  # Capture time-stamp if vty line has command time-stamping turned on
  ^Load\s+for\s+
  ^Time\s+source\s+is
```
##### SAMPLE COMMAND OUTPUT

```
[{'iface': 'Te1/1/3', 'temperature': '29.0', 'voltage': '3.30', 'tx_pwr': '35.5', 'rx_pwr': '-2.3'}]
```
##### SUMMARY

The template does not account for the Current (mA) measurement taken. This means that the tx_pwr value is actually the Current value. 

##### STEPS TO REPRODUCE

net_conn.send_command('show interface transceiver', use_textfsm=True) 

##### EXPECTED RESULTS

The tx_pwr should have been -2.3

##### ACTUAL RESULTS

the tx_pwr reading was 35.5

[{'iface': 'Te1/1/3', 'temperature': '29.0', 'voltage': '3.30', 'tx_pwr': '35.5', 'rx_pwr': '-2.3'}]

####### FIX

changing the template to the following fixed the issue:
```
Value IFACE (\w+\d+\/\S+)
Value TEMPERATURE (\d+.\d+)
Value VOLTAGE (\d+.\d+)
Value TX_PWR (\S+)
Value RX_PWR (\S+)

Start
  ^${IFACE}\s+${TEMPERATURE}\s+${VOLTAGE}\s+${TX_PWR}\s+${RX_PWR}\s+ -> Record
  # Capture time-stamp if vty line has command time-stamping turned on
  ^Load\s+for\s+
  ^Time\s+source\s+is
```

**Comment by itdependsnetworks** [comment]
I cannot see the difference

**Comment by itdependsnetworks** [comment]
I think it would need to be 
```
Start
  ^${IFACE}\s+${TEMPERATURE}\s+${VOLTAGE}\s+${CURRENT}\s+${TX_PWR}\s+${RX_PWR}\s+ -> Record
  ^${IFACE}\s+${TEMPERATURE}\s+${VOLTAGE}\s+${TX_PWR}\s+${RX_PWR}\s+ -> Record
  # Capture time-stamp if vty line has command time-stamping turned on
  ^Load\s+for\s+
  ^Time\s+source\s+is
```
That being said, it's an additional feature, welcome to put in a PR with tests.

**Comment by itdependsnetworks** [comment]
As mentioned, PR's welcome, closing as this is a feature
