### ISSUE TITLE
Update to Arista "show ip ospf neighbor", running version 4.27.0F

### ISSUE THREAD

**Issue by JulioPDX** [networktocode/ntc-templates#1058]
##### ISSUE TYPE

 - Bug Report

##### TEMPLATE USING

```
Value NEIGHBOR_ID (\d+.\d+.\d+.\d+)
Value INSTANCE (\d+)
Value VRF (\S+)
Value PRIORITY (\d+)
Value STATE (\S+|\S+\s+\S+)
Value DEAD_TIME (\d+:\d+:\d+)
Value ADDRESS (\d+.\d+.\d+.\d+)
Value INTERFACE (\S+)

Start
  ^${NEIGHBOR_ID}\s+${INSTANCE}\s+${VRF}\s+${PRIORITY}\s+${STATE}\s+${DEAD_TIME}\s+${ADDRESS}\s+${INTERFACE} -> Record
```

##### SAMPLE COMMAND OUTPUT

```
Neighbor ID     Instance VRF      Pri State                  Dead Time   Address         Interface
0.0.0.5         1        default  0   FULL                   00:00:37    10.0.0.3        Ethernet2
0.0.0.2         1        default  0   EXCH START             00:00:31    10.0.0.1        Ethernet1
0.0.0.9         1        default  0   FULL                   00:00:35    10.0.0.21       Ethernet4
0.0.0.8         1        default  0   FULL                   00:00:31    10.0.0.19       Ethernet3
```

##### SUMMARY
Seems "instance" was added in the show ip ospf neighbor output on at least the version of Arista I am using. 4.27.0F

##### STEPS TO REPRODUCE

I updated the template above and seems to be working with this version, I'm not sure how to make it backwards compatible but I thought I would share. 

##### ACTUAL RESULTS

Results with using the included sample output and template.

```
[
    {
        'neighbor_id': '0.0.0.5',
        'instance': '1',
        'vrf': 'default',
        'priority': '0',
        'state': 'FULL',
        'dead_time': '00:00:29',
        'address': '10.0.0.3',
        'interface': 'Ethernet2'
    },
    {
        'neighbor_id': '0.0.0.2',
        'instance': '1',
        'vrf': 'default',
        'priority': '0',
        'state': 'EXCH START',
        'dead_time': '00:00:33',
        'address': '10.0.0.1',
        'interface': 'Ethernet1'
    },
    {
        'neighbor_id': '0.0.0.9',
        'instance': '1',
        'vrf': 'default',
        'priority': '0',
        'state': 'FULL',
        'dead_time': '00:00:36',
        'address': '10.0.0.21',
        'interface': 'Ethernet4'
    },
    {
        'neighbor_id': '0.0.0.8',
        'instance': '1',
        'vrf': 'default',
        'priority': '0',
        'state': 'FULL',
        'dead_time': '00:00:32',
        'address': '10.0.0.19',
        'interface': 'Ethernet3'
    }
]
```

**Comment by JulioPDX** [comment]
Give me a sec, output was not correct at all. Need to account for spacing in dual string possibility

**Comment by JulioPDX** [comment]
Okay thats much better, please let me know what you all think :)

**Comment by JulioPDX** [comment]
I think I see another bug in this. When in DR FULL in the text output it displays `FULL/DR`

**Comment by jvanderaa** [comment]
The update makes sense. Want to take a crack at the fix on it @JulioPDX ? Otherwise it may be just a little bit yet.

**Comment by JulioPDX** [comment]
> The update makes sense. Want to take a crack at the fix on it @JulioPDX ? Otherwise it may be just a little bit yet.

The template I posted above will work for new versions of EOS, I'm just not sure how to make it compatible with previous versions that do not add instance as a return value in the output.

**Comment by ryanmerolle** [comment]
What are the next steps here?

**Comment by jvanderaa** [comment]
@ryanmerolle next steps are to submit a PR.

**Comment by jvanderaa** [comment]
@JulioPDX you want to take a crack at this one?

**Comment by JulioPDX** [comment]
Ah yes, I can submit a PR @jvanderaa. Apologies for the delay

**Comment by mjbear** [comment]
@JulioPDX 
How are you doing?!

The solution to backwards compatibility could be to:
1. Have two rules (one with `${INSTANCE}` and one without)
2. Make INSTANCE optional (ex: `(${INSTANCE})?`

However it seems like #1174 has already merged a [fix for the OSPF instance ID](https://github.com/networktocode/ntc-templates/pull/1174/files#diff-148ad8a1c843e95547cfd239426b0b68d7a645f7db13e8e856a55dc3c8f9b6e9L10).
The template as it exists currently includes two rules (so option 1 from above).

Hope this helps!

**Comment by JulioPDX** [comment]
@mjbear Thanks for pointing this out. I just tested this and looks to be working.
