### ISSUE TITLE
cisco_ios_show_access-list.textfsm returns TextFSMTemplateError with textfsm v1.1.2 installed

### ISSUE THREAD

**Issue by SimpleManEngineer** [networktocode/ntc-templates#1060]
platform = 'cisco_ios'
command = 'show access-lists'
data = 'show_access_lists.txt'
parse_output(platform=platform, command=command, data=data)

returns: textfsm.parser.TextFSMTemplateError: Value '([(\S+\s\S+)]+)' must be contained within a '()' pair

##### ISSUE TYPE

 - Bug Report

##### TEMPLATE USING

# IOS ACL structure is quite complex.
# 
# Extended IP ACL:
# 	SEQUENCE_NUMBER ACTION PROTOCOL SOURCE [PORT id] [RANGE start finish] DESTINATION [MODIFIER]
#
# Standard ACL:
#	SEQUENCE_NUMBER ACTION SOURCE DESTINATION [MODIFIER]
#	 
#
Value Filldown NAME (\S+)
Value Required SN (\d+)
Value ACTION (\w+)
Value PROTOCOL (\w+)
#
# SOURCE RegEx must be able to catch every possible source combination including masks. 'any' and 'host' and 'wildcard bits' are possible too.
#
Value SOURCE (host\s\d+\.\d+\.\d+\.\d+|any|\d+\.\d+\.\d+\.\d+\s\d+\.\d+\.\d+\.\d+|\d+\.\d+\.\d+\.\d+,\s+wildcard bits\s\d+\.\d+\.\d+\.\d+|\d+\.\d+\.\d+\.\d+)
#
# We can specify protocols to match. 'eq', 'gt', 'lt', 'range' and 'neq' are supported.
#
Value PORT (eq|gt|lt|neq|range)
#
# This can be either a single port or a list.
#
Value RANGE ([(\S+\s\S+)]+)
#
# DESTINATION RegEx must be able to catch every possible source combination including masks. 'any' and 'host' and 'wildcard bits' are possible too.
# 
Value DESTINATION (host\s\d+\.\d+\.\d+\.\d+|any|\d+\.\d+\.\d+\.\d+\s\d+\.\d+\.\d+\.\d+|\d+\.\d+\.\d+\.\d+,\s+wildcard bits\s\d+\.\d+\.\d+\.\d+)
Value MODIFIER (.*)

Start
  ^.*list\s+${NAME}
  ^\s+${SN}\s+${ACTION}\s+${PROTOCOL}\s+${SOURCE}(\s+${PORT})*(\s${RANGE})*\s+${DESTINATION}(\s+${MODIFIER})* -> Record
  ^\s+${SN}\s+${ACTION}\s+${SOURCE}(\s+${MODIFIER})* -> Record
  # Capture time-stamp if vty line has command time-stamping turned on
  ^Load\s+for\s+
  ^Time\s+source\s+is

##### SAMPLE COMMAND OUTPUT

Standard IP access list 1
    10 permit 4.5.6.0 log
    20 permit any
Standard IP access list 2
    10 permit 0.0.0.0, wildcard bits 255.255.255.252 log (4556 matches)
    20 permit any (11665 matches)

##### SUMMARY

platform = 'cisco_ios'
command = 'show access-lists'
data = 'show_access_lists.txt'
parse_output(platform=platform, command=command, data=data)

returns: textfsm.parser.TextFSMTemplateError: Value '([(\S+\s\S+)]+)' must be contained within a '()' pair

NOTE: With textfsm v1.1.0 installed, template works fine.

##### STEPS TO REPRODUCE

pip3 install --upgrade textfsm (make sure you have latest version installed)

1. run ansible-playbook with task below and save output to 'show_access_lists.txt'
2.  In python script:
platform = 'cisco_ios'
command = 'show access-lists'
data = 'show_access_lists.txt'
parse_output(platform=platform, command=command, data=data)

```yaml
    - name: SHOW ACCESS LISTS
      ios_command:
        commands:
          - show access-lists
      register: access_lists
```

##### EXPECTED RESULTS

After running playbook above, and calling parse_output() i expect the output to be python list:

[{'name': '1', 'sn': '10', 'action': 'permit', 'protocol': '', 'source': '4.5.6.0', 'port': '', 'range': '', 'destination': '', 'modifier': 'log'}, {'name': '1', 'sn': '20', 'action': 'permit', 'protocol': '', 'source': 'any', 'port': '', 'range': '', 'destination': '', 'modifier': ''}, {'name': '2', 'sn': '10', 'action': 'permit', 'protocol': '', 'source': '0.0.0.0, wildcard bits 255.255.255.252', 'port': '', 'range': '', 'destination': '', 'modifier': 'log (4928 matches)'}, {'name': '2', 'sn': '20', 'action': 'permit', 'protocol': '', 'source': 'any', 'port': '', 'range': '', 'destination': '', 'modifier': '(12542 matches)'}]

##### ACTUAL RESULTS

Error:
textfsm.parser.TextFSMTemplateError: Value '([(\S+\s\S+)]+)' must be contained within a '()' pair. Line 25.

```
Traceback (most recent call last):
  File "generate_excel.py", line 86, in <module>
    access_lists_sheet() # not working for textfsm 1.1.2
  File "generate_excel.py", line 68, in access_lists_sheet
    json_data = txt_to_json_list('./outputs/' + 'show_access_lists.txt', command = 'show access-lists')
  File "generate_excel.py", line 31, in txt_to_json_list
    return parse_output(platform=platform, command=command, data=data)
  File "/home/devasc/.local/lib/python3.8/site-packages/ntc_templates/parse.py", line 57, in parse_output
    cli_table.ParseCmd(data, attrs)
  File "/home/devasc/.local/lib/python3.8/site-packages/textfsm/clitable.py", line 282, in ParseCmd
    self.table = self._ParseCmdItem(self.raw, template_file=template_files[0])
  File "/home/devasc/.local/lib/python3.8/site-packages/textfsm/clitable.py", line 306, in _ParseCmdItem
    fsm = textfsm.TextFSM(template_file)
  File "/home/devasc/.local/lib/python3.8/site-packages/textfsm/parser.py", line 586, in __init__
    self._Parse(template)
  File "/home/devasc/.local/lib/python3.8/site-packages/textfsm/parser.py", line 684, in _Parse
    self._ParseFSMVariables(template)
  File "/home/devasc/.local/lib/python3.8/site-packages/textfsm/parser.py", line 728, in _ParseFSMVariables
    raise TextFSMTemplateError('%s Line %s.' % (error, self._line_num))
textfsm.parser.TextFSMTemplateError: Value '([(\S+\s\S+)]+)' must be contained within a '()' pair. Line 25.
```

**Comment by diepes** [comment]
@SimpleManEngineer can you provide **sample output** from the cisco device for the `show access-list` in a code block.
Then we can add it as another test for for the `cisco_ios_show_access-list` command and try to update the parsing for it.

**Comment by abhi1693** [comment]
@diepes Does this work? I have the exact same issue

```
Standard IP access list 1
10 permit 4.5.6.0 log
20 permit any
Standard IP access list 2
10 permit 0.0.0.0, wildcard bits 255.255.255.252 log (4556 matches)
20 permit any (11665 matches)
```

**Comment by abhi1693** [comment]
I'm not sure but I changed the `RANGE` to `Value RANGE (\S+\s\S+)` and it seems to have worked.

**Comment by youngbobnetwork** [comment]
@abhi1693 Do you recall where you changed this at? I dont see it within the parser.py file

**Comment by abhi1693** [comment]
@youngbobnetwork You can check the change at https://github.com/Onemind-Services-LLC/ntc-templates/commit/6f7222d805a66389a180c77d74e5795d120c1245
