### ISSUE TITLE
lot of pull requests with small fix's,  currently 73 

### ISSUE THREAD

**Issue by diepes** [networktocode/ntc-templates#1095]
Hi There,

@itdependsnetworks , @jmcgill298 , @FragmentedPacket , @jvanderaa 

I see there is currently a lot of pull requests, waiting to be approved. (Currently 73)
I would like assist at getting them reviewed and approved, does anyone have the time to shadow/assist me  ?

Cheers,
Pieter

**Comment by itdependsnetworks** [comment]
Yea, that seems fair, will try and get back to you by this week

**Comment by jvanderaa** [comment]
Thanks @diepes, I'm going to try to get some updates in as well this week as some time will allow.

**Comment by itdependsnetworks** [comment]
@diepes to confirm, this would be in the capacity of becoming a maintainer, presumably there would be some sort of training, then some sort of trial period. Is this something that you could commit to some minimal amount of effort. Say a 2+ hours a month as example?

**Comment by diepes** [comment]
@itdependsnetworks yes to help with the maintenance (pr review) for a couple of hours per month.
My thinking was that i can start by reviewing PR's commenting and approving them, even if it does not move them forward currently.
Then when one of the current Maintainers review it, get some feedback of stuff to review etc.

**Comment by diepes** [comment]
Looking at some of the oldes PR's >2y, should be closed/cancelled,  as they have been abandoned
![image](https://user-images.githubusercontent.com/96414/158039315-231a5f1d-cfb4-46e1-90a4-42623eecf595.png)

I suggest we tag and then close them after a month, anything behind more that 100 commits, and touching more than 100 files. (These are probably all pre the big poetry update)

e.g.
https://github.com/networktocode/ntc-templates/pull/418
https://github.com/networktocode/ntc-templates/pull/475

**Comment by diepes** [comment]
Issue: https://github.com/networktocode/ntc-templates/issues/1051 can be closed

**Comment by itdependsnetworks** [comment]
@diepes finally getting around to fixing some things, contact me on slack if you wish to discuss further.
