### ISSUE TITLE
Cisco ASA show version template

### ISSUE THREAD

**Issue by bobthebutcher** [networktocode/ntc-templates#110]
##### ISSUE TYPE
 - Template Creation Help

##### SUMMARY
Would like to have a cisco ASA show version template. 
I am happy to work on this if no one else is already doing it.

**Comment by termlen0** [comment]
Hello,
Working on it...

**Comment by termlen0** [comment]
@bobthebutcher , PR #111 merged, to address this request.

**Comment by GGabriele** [comment]
Thanks @termlen0 , nice job!

**Comment by bobthebutcher** [comment]
@termlen0 awesome thanks you sir :)
