### ISSUE TITLE
Mikrotik router OS - IP route print - Multiple gateways

### ISSUE THREAD

**Issue by elavaud** [networktocode/ntc-templates#1195]
##### ISSUE TYPE
 - Bug Report

##### TEMPLATE USING
mikrotik_routeros_ip_route_print_terse

##### SAMPLE COMMAND OUTPUT
```
 6 A S  dst-address=0.0.0.0/0 gateway=185.138.116.222,185.138.116.223 gateway-status=185.138.116.222 unreachable,185.138.116.223 reachable via  pppoe-out1 distance=10 scope=30 target-scope=10 
```

##### SUMMARY
Parsing does not succeed when multiple gateways exist (see upper)

**Comment by itdependsnetworks** [comment]
Fixed in #1152
