### ISSUE TITLE
'show memory statistics' cisco switch/rotuer template

### ISSUE THREAD

**Issue by NedySuprianto** [networktocode/ntc-templates#121]
- Template Creation Help

would like have template 'show memory statistic' cisco switch/router :)

**Comment by itdependsnetworks** [comment]
@NedySuprianto if you can provide a few samples I can take a look at it.

**Comment by itdependsnetworks** [comment]
just a reminder @NedySuprianto

**Comment by NedySuprianto** [comment]
sorry for the late replay, i'm already got the answer @itdependsnetworks 
how can i close this issue?

**Comment by itdependsnetworks** [comment]
Do you mind uploading the template to help the next user?

**Comment by NedySuprianto** [comment]
i'm not sure this will work for all user, but this is work for me. Hope you can fix the problem if there's have something missing.


```
Value MEMTYPE ((Processor|\s+I/O|Driver te))
Value HEAD ([0-9A-f]+)
Value TOTAL (\d+)
Value USED (\d+)
Value FREE (\d+)
Value LOW (\d+)
Value LARGE (\d+)

Start
	^${MEMTYPE}\s+${HEAD}\s+${TOTAL}\s+${USED}\s+${FREE}\s+${LOW}\s+${LARGE} -> Record
```

**Comment by NedySuprianto** [comment]
actually it's grab `show memory statistics` and `show process memory` data, not only `show memory statistics`. the first one is `show memory statistics` and the second one is `show process memory`.
