### ISSUE TITLE
cisco show isdn status only return one interface 

### ISSUE THREAD

**Issue by network-shark** [networktocode/ntc-templates#1228]
##### SUMMARY
When using Cisco_show_isdn_status only the last item is returned instead of all interfaces.

##### STEPS TO REPRODUCE
Use cisco show isdn status with textfsm

##### EXPECTED RESULTS
Should return all interfaces
##### ACTUAL RESULTS
Only the last interface is parsed

**Comment by itdependsnetworks** [comment]
Please provide the raw output and actual error.

**Comment by network-shark** [comment]
I thought it is an easy fix , but I could not solve it. Yes, I will apply my findings asap. Am 03.12.2022 um 23:56 schrieb Ken Celenza ***@***.***>:﻿
Please provide the raw output and actual error.

**Comment by mjbear** [comment]
@network-shark 
1. Please respond with raw CLI output in a [code block](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks).
2. In the same response, please create a second code block that contains the TextFSM error message.

Thank you!

**Comment by mjbear** [comment]
@network-shark 
Test data shows parsing [raw output](https://github.com/networktocode/ntc-templates/blob/4b6773517271a94a98ef440723bbe668980e2add/tests/cisco_ios/show_isdn_status/cisco_ios_show_isdn_status.raw) with [multiple interfaces successfully](https://github.com/networktocode/ntc-templates/blob/4b6773517271a94a98ef440723bbe668980e2add/tests/cisco_ios/show_isdn_status/cisco_ios_show_isdn_status.yml) so there probably are differences in your device output that need accounted for.

**Comment by jmcgill298** [comment]
closing from lack of response. If re-interest arises, then the issue can be reopened with the output that causes failure
