### ISSUE TITLE
hp_procurve_show_vlans.template empty output

### ISSUE THREAD

**Issue by cyberdog478** [networktocode/ntc-templates#124]
The HP Procurve Show Vlans template regex is unable to handle the addition of the pipe separator used for separating the Name and Status colums (example below) which results in null returned. The following change to the regex resolves this issue (adding \S+\s+ to capture and ignore the pipe and white space):

Line 11: 
`  ^\s+${VLAN_ID}\s+${NAME}\s+\S+\s+${STATUS}\s+${VOICE}\s+${JUMBO} -> Record`

Original Line 11:
`  ^\s+${VLAN_ID}\s+${NAME}\s+${STATUS}\s+${VOICE}\s+${JUMBO} -> Record`

```
  VLAN ID Name                             | Status     Voice Jumbo
  ------- -------------------------------- + ---------- ----- -----
  1       DEFAULT_VLAN                     | Port-based No    No  


```

**Comment by itdependsnetworks** [comment]
@cyberdog478 I attempted to make the updates as you indicated, but it broke the existing test data. Can you provide full output (meaning cli prompt to cli prompt) of your show commands?

**Comment by itdependsnetworks** [comment]
just a reminder @cyberdog478

**Comment by rkerr** [comment]
Looks like #148 would resolve this without breaking the test cases.

The | between the name and status appears on most of the newer hardware but is missing on the older stuff. The jumbo frames column won't always be present - depends if the hardware supports jumbo frames.
