### ISSUE TITLE
NTC Parser does not support IPv4 and IPv6 mixed objects (used for NAT64/NAT46)

### ISSUE THREAD

**Issue by pertoft** [networktocode/ntc-templates#1241]
NTC Parser does not support IPv4 and IPv6 mixed objects (used for NAT64/NAT46)
` all_rules = parse_output(platform="cisco_asa", command="show access-lists", data=input_file.read())`

Example acl:
`
access-list internet-in line 3 extended permit udp object-group group1 object-group group2-subnets object-group monitoring-udp-services (hitcnt=163176) 0xfb290ba6

  access-list internet-in line 3 extended permit udp 2adb8:db80:0:f159::/64 172.28.64.128 255.255.255.128 eq ntp (hitcnt=0) 0xc01192ad

  access-list internet-in line 3 extended permit udp 2adb8:db80:0:f159::/64 172.28.64.128 255.255.255.128 eq snmp (hitcnt=0) 0xae3c968e
`

**Comment by mjbear** [comment]
@jmcgill298 
Another issue ticket related to PR #1351 (supersedes PR #1243)
