### ISSUE TITLE
Cisco IOS ping

### ISSUE THREAD

**Issue by KeithETruesdell** [networktocode/ntc-templates#1281]
### Environment
* ntc-templates version:  

### Proposed Functionality

Adding new textfsm template for ping command and variations

ping 192.168.0.1 source 192.168.0.10 size 1500 repeat 4 df

Already part of fork

**Comment by diepes** [comment]
@KeithETruesdell is see there is already support for ping.
If you can supply a command and sample output for a platform we can extend it to capture the output.

**Comment by KeithETruesdell** [comment]
this ticket can probably be closed as there is already a cisco ios ping template and a ticket #1282 that I created and was merged into things.  I am not sure why there is a duplicate request / issue for this, but it was probably something I did, maybe I didn't realize I  already opened this one when I did things with  #1282
