### ISSUE TITLE
cisco_nxos_show_ip_bgp does not function with "all" 

### ISSUE THREAD

**Issue by chuckysap** [networktocode/ntc-templates#1319]
### Proposed Functionality

It would be ideal if this template would work with `show ip bgp vrf all` and not just a specific VRF like so `show ip bgp vrf <VRF_NAME>`.  Is it possible to integrate this?

**Comment by jvanderaa** [comment]
Should be no problem to do so.

**Comment by mjbear** [comment]
@chuckysap 
Might you be able to share example output so this can be worked on?

(Note: I'm a community volunteer, but happy to work with you if I can get information.)

https://github.com/networktocode/ntc-templates/blob/master/ntc_templates/templates/cisco_nxos_show_ip_bgp.textfsm
https://github.com/networktocode/ntc-templates/tree/master/tests/cisco_nxos/show_ip_bgp
https://github.com/networktocode/ntc-templates/blob/master/ntc_templates/templates/index#L379

**Comment by mjbear** [comment]
@chuckysap 
If you'd like to test, please pull down a copy of my changes and test.

PR #1628 has been submitted

**Comment by ryanmerolle** [comment]
This has been merged.  Can we please close?
