### ISSUE TITLE
cisco_ios_show_access-list returns error:  Value '([(\S+\s\S+)]+)' must be contained within a '()' pair.

### ISSUE THREAD

**Issue by IcedZ** [networktocode/ntc-templates#1354]
##### ISSUE TYPE

 - Template Issue with error and raw data
 - Bug Report with the library
 - Feature - This is only relevant to the library, not templates
 - Documentation Report

##### TEMPLATE USING

```

```

##### SAMPLE COMMAND OUTPUT

```

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by IcedZ** [comment]
When using with netmiko, this command does not execute successfully. The other 16 commands work fine.
Additionally, the full Cisco IOS command is "show access-lists" (plural)

**Comment by mjbear** [comment]
@IcedZ 
Would you be able to provide further details?

Example output from your device would be helpful as would the template (just in case what you have isn't the latest template version and is instead a point release).

Thank you.

**Comment by mjbear** [comment]
@IcedZ - Would you be able to provide sample output?

**Comment by ryanmerolle** [comment]
@IcedZ bump

**Comment by IcedZ** [comment]
I'll have to pull up my code; should be able to look at it next week.

**Comment by mjbear** [comment]
> I'll have to pull up my code; should be able to look at it next week.

Hello @IcedZ 
Would you be willing to provide sample output this week?

Thank you!

**Comment by jmcgill298** [comment]
That syntax was changed in this PR https://github.com/networktocode/ntc-templates/pull/1353/files

**Comment by mjbear** [comment]
Ah. Thank you Jacob.
This probably means this issue ticket can be marked as resolved since #1353 should resolve the problem.

**Comment by mjbear** [comment]
@jmcgill298 
Another simple one to close since PR #1353 resolves it. :grinning:
