### ISSUE TITLE
Cisco NXOS - Error "Unsupported switch port mode DOT1Q_TUNNEL, assuming no VLANs allowed" while parsing interface config

### ISSUE THREAD

**Issue by svestenik** [networktocode/ntc-templates#1542]
Cisco Nexus 3048 switch configured with "dot1q-tunnel mode" (QinQ)
```
show running-config interface Ethernet1/22

interface Ethernet1/22
  description ** Some QinQ **
  no cdp enable
  switchport mode dot1q-tunnel
  switchport access vlan 111
  spanning-tree bpdufilter enable
  l2protocol tunnel cdp
  l2protocol tunnel stp
```

##### SUMMARY 

When parsing interfaces configured as QinQ tunnels on Nexus switches, error is returned as dot1Q-tunnel mode is not supported in NTC-Templates.

##### STEPS TO REPRODUCE

Try to parse any interface on Nexus switch configured as dot1Q-tunnel (valid NX-OS interface mode).

##### EXPECTED RESULTS

Interface should be returned as mode dot1Q-tunnel and outer vlan tag should be identified (inner vlans are not really important in this mode).

**Comment by jvanderaa** [comment]
Which template is this in regards to? Is there some show command output (other than show run, as configurations is not the usual path here).

**Comment by mjbear** [comment]
@svestenik 
* Could you please provide the name of the NX-OS template that has issues?
* Please provide sample command output so it can be used to test against?

Thank you!

**Comment by ryanmerolle** [comment]
bump @svestenik, can you please help @mjbear

**Comment by mjbear** [comment]
@svestenik 
Please respond back.
Without more information there is a bunch of guessing going on.

1. Could you please provide the name of the NX-OS template that has issues?
2. Please provide sample command output so it can be used to test against?

Thank you!

**Comment by jmcgill298** [comment]
lack of response, unable to assist further without more info
