### ISSUE TITLE
PR1439 / PR1444 - Broken IP address parsing from show interfaces on Cisco IOS

### ISSUE THREAD

**Issue by lamoni** [networktocode/ntc-templates#1545]
##### SUMMARY
Latest textfsm template for "show interfaces" on Cisco IOS broke the IP address parsing. I was using 4.0.0 and reverted back to 3.2.0 to get it working again. I believe PR1439 and PR14444 are pertaining to the issue but may not have captured the fix completely

##### STEPS TO REPRODUCE
Use latest templates and parse Cisco show interface output, IP address doesn't match anymore

##### EXPECTED RESULTS
Same behavior as older templates: ip_address gets filled

##### ACTUAL RESULTS
ip_address is no longer captured

**Comment by itdependsnetworks** [comment]
Hi, this is actualy  to be expected. We have done our best to communicate the changes:

https://blog.networktocode.com/post/ntc-templates-data-modeling/
https://github.com/networktocode/ntc-templates/blob/master/changes_for_4.md

As well as updates on Slack and Twitter as well as adhering to SemVer. I know this may be difficult to change, but this has been a common issue over the years we are trying to address for the community as a whole.

**Comment by lamoni** [comment]
@itdependsnetworks Thanks for the heads up, I'll close this
