### ISSUE TITLE
Using the .textfsm extension for templates

### ISSUE THREAD

**Issue by dagwieers** [networktocode/ntc-templates#171]
##### ISSUE TYPE
 - Feature Idea

##### TEMPLATE USING
all

##### SUMMARY
I think there's value in renaming the textfsm templates to use the `.textfsm` file extension as currently they cannot be syntax-highlighted in editors, or they are syntax-highlighted wrongly.

**Comment by itdependsnetworks** [comment]
@dagwieers remind me second week of new years, I'll bring this up. Not leaning to much one way or another, but worth a convo for sure.
