### ISSUE TITLE
enhancement - Normalize inventory related capture groups (cisco_*, arista_eos)

### ISSUE THREAD

**Issue by mjbear** [networktocode/ntc-templates#1786]
### Important Note

Feature request for new templates will be closed.
Feature request for adding data captured to existing templates will be closed.

### Environment
* ntc-templates version:  
latest on github

### Proposed Functionality
Consider normalizing some capture group names in `show inventory` templates ( :point_right: I'm looking for feedback before I work on this).

In looking for guidance for a different platform, I noticed that [cisco_ios sh inv](https://github.com/networktocode/ntc-templates/blob/4b6773517271a94a98ef440723bbe668980e2add/tests/cisco_ios/show_inventory/cisco_ios_show_inventory.yml#L10), [cisco_nxos sh inv](https://github.com/networktocode/ntc-templates/blob/4b6773517271a94a98ef440723bbe668980e2add/tests/cisco_nxos/show_inventory/cisco_nxos_show_inventory.yml#L5), and [cisco_xr sh inv](https://github.com/networktocode/ntc-templates/blob/4b6773517271a94a98ef440723bbe668980e2add/tests/cisco_xr/show_inventory/cisco_xr_show_inventory_01.yml#L5) capture groups closely resemble one another, but [arista_eos sh inv](https://github.com/networktocode/ntc-templates/blob/4b6773517271a94a98ef440723bbe668980e2add/tests/arista_eos/show_inventory/arista_eos_show_inventory.yml#L4) has some variation (as described next).

I'm looking for feedback on changing arista_eos show inventory capture group `name` to be `pid` to normalize with the convention we see in cisco_(ios|nxos) show inventory templates. This would be considered a breaking change.

```
Value NAME (\S+)

would become

Value PID (\S+)
```

### Use Case
Capture group normalization as noted in the previous section.

**Comment by mjbear** [comment]
@jvanderaa @jmcgill298 @itdependsnetworks 
Thoughts?

Thank you!

**Comment by jmcgill298** [comment]
That is fine with me

**Comment by jvanderaa** [comment]
Looks good.

**Comment by mjbear** [comment]
submitted PR #1787, resolving this issue ticket
