### ISSUE TITLE
idea: consolidate to cisco_xr_admin_show_inventory

### ISSUE THREAD

**Issue by mjbear** [networktocode/ntc-templates#1788]
### Important Note

Feature request for new templates will be closed.
Feature request for adding data captured to existing templates will be closed.

### Environment
* ntc-templates version:  
github latest

### Proposed Functionality
Modify the `index` file so that cisco_xr `admin show inventory` and `show inventory` utilize the same TextFSM template.
(I have successfully tested changes in a branch, but want to make sure there is agreement before sending in a PR.)

:dart: This reduces a duplicate template and will also remove one line from the `index` file.
:bulb: Since the capture group names are the same between the two, this is a seamless change.

Note: Raw output and parsed output for tests still needs placed in their respective directories.
```
tests/cisco_xr/admin_show_inventory/
tests/cisco_xr/show_inventory/
```

:balance_scale: The template for [`admin show inventory` is older](https://github.com/networktocode/ntc-templates/commit/f3eaa79c2f470739a60d9baaf4d21d52ecd195a6) along with regexes/$$ line termination ([[0]](https://github.com/networktocode/ntc-templates/blob/4b6773517271a94a98ef440723bbe668980e2add/ntc_templates/templates/cisco_xr_admin_show_inventory.textfsm) vs [[1]](https://github.com/networktocode/ntc-templates/blob/4b6773517271a94a98ef440723bbe668980e2add/ntc_templates/templates/cisco_xr_show_inventory.textfsm)) so I used that to choose which template to consolidate.

### Use Case
Developers benefit from this being DRY (don't repeat yourself).
This is similar to xr show platform PR #1783 where two commands were covered by a single template.

**Comment by mjbear** [comment]
Anyone have any feedback?
Thank you!

@jvanderaa @jmcgill298
@lamiskin @diepes @dainok

**Comment by dainok** [comment]
@mjbear to me it's fine. I don't have enough test equipment with XR, so I trust that `show inventory` and `admin show inventory` always have the same result.
I guess that exceptions can still be managed inside one template.

**Comment by mjbear** [comment]
> @mjbear to me it's fine. I don't have enough test equipment with XR, so I trust that `show inventory` and `admin show inventory` always have the same result. I guess that exceptions can still be managed inside one template.

That's a fair point @dainok.
Based on the test output we have the raw output structure is almost identical (minor: one has a blank line at a different spot :grinning:).
[cisco_xr_show_inventory tests](https://github.com/networktocode/ntc-templates/tree/4b6773517271a94a98ef440723bbe668980e2add/tests/cisco_xr/show_inventory)
[cisco_xr_admin_show_inventory tests](https://github.com/networktocode/ntc-templates/tree/4b6773517271a94a98ef440723bbe668980e2add/tests/cisco_xr/admin_show_inventory)

**Comment by jmcgill298** [comment]
yes, this can just be handled by the index file

**Comment by mjbear** [comment]
:100: 
I submitted PR #1797
