### ISSUE TITLE
some Cisco IP Phone 6901 not supported by template cisco_ios_show_lldp_neighbors_detail.textfsm

### ISSUE THREAD

**Issue by mcn29** [networktocode/ntc-templates#1884]
my quick fix in cisco_ios_show_lldp_neighbors_detail.textfsm :

line 29
```
  ^Chassis\s+id:\s+${CHASSIS_ID}\s*$$
```
changed into :

```
  ^Chassis\s+id:\s+(${CHASSIS_ID}\s*$$|::)
```

##### ISSUE TYPE
 - Template Issue with error and raw data

##### TEMPLATE USING
```
Value LOCAL_INTERFACE (\S+)
Value CHASSIS_ID ([^:]+)
Value NEIGHBOR_PORT_ID (.*)
Value NEIGHBOR_INTERFACE (.*)
Value NEIGHBOR_NAME (.+?)
Value NEIGHBOR_DESCRIPTION (.*)
Value CAPABILITIES (.*)
Value MGMT_ADDRESS (\S+)
Value VLAN_ID (\d+)
Value MAC_ADDRESS ([0-9a-fA-F]{4}\.[0-9a-fA-F]{4}\.[0-9a-fA-F]{4})
Value SERIAL (\S+)
Value MANUFACTURER (.*)
Value HW_REVISION (\S+)
Value FW_REVISION (\S+)
Value SW_REVISION (\S+)
Value PLATFORM (.*)
Value POWER_PAIR (\S+)
Value POWER_CLASS (\d+)
Value POWER_DEVICE_TYPE (\S+)
Value POWER_PRIORITY (\S+)
Value POWER_SOURCE (\S+)
Value POWER_REQUESTED (\d+)

Start
  ^.*not advertised
  ^.*Invalid input detected -> EOF
  ^.*LLDP is not enabled -> EOF
  ^Local\s+Intf:\s+${LOCAL_INTERFACE}\s*$$
  ^Chassis\s+id:\s+${CHASSIS_ID}\s*$$
  ^Port\s+id:\s+${NEIGHBOR_PORT_ID}\s*$$
  ^Port\s+Description:\s+${NEIGHBOR_INTERFACE}\s*$$
  ^System\s+Name(\s+-\s+not\s+advertised)\s*$$
  ^System\s+Name:?\s*$$
  ^System\s+Name(:\s+${NEIGHBOR_NAME})\s*$$
  ^System\s+Description -> GetDescription
  ^Time
  ^System\s+Capabilities
  ^Enabled\s+Capabilities:\s+${CAPABILITIES}\s*$$
  ^Management\s+Addresses
  ^\s+OID
  ^\s+[\d+\.]{8,}
  ^.*IP:\s+${MGMT_ADDRESS}\s*$$
  ^Auto\s+Negotiation
  ^Physical\s+media
  # Removed \(\s+\) from the template - The line 'Other/unknown' would not be captured
  # Now looks for any text beginning with any space
  ^\s+.+\s*$$
  ^Media\s+Attachment
  ^\s+Inventory
  ^\s+Capabilities
  ^\s+Device\s+type
  ^\s+Network\s+Policies
  ^\s+Power\s+requirements
  ^\s+Location
  ^Time\s+remaining
  ^Vlan\s+ID:\s+(?:${VLAN_ID}|-\s+not\s+advertised)\s*$$
  ^Peer\s+Source\s+MAC:\s+${MAC_ADDRESS}
  ^\s+\(\S+\)
  ^(?:PoE|\s+Power)
  ^\s*-+\s*$$ -> Record
  ^Power\s+via\s+MDI -> PowerMDI
  ^MED -> Med
  ^\s*\^\s*
  ^\s*Total\s+entries\s+displayed -> Record
  ^\s*$$
  # Capture time-stamp if vty line has command time-stamping turned on
  ^Load\s+for\s+
  ^Time\s+source\s+is
  ^.*$$ -> Error

GetDescription
  ^${NEIGHBOR_DESCRIPTION} -> IgnoreDescription

IgnoreDescription
  ^Time\s+remaining -> Start
  ^\S*
  ^\s*$$
  ^.* -> Error

PowerMDI
  ^\s+Power\s+Pair:\s+${POWER_PAIR}\s*$$
  ^\s+Power\s+Class:\s+${POWER_CLASS}\s*$$
  ^\s+Power\s+Device\s+Type:\s+${POWER_DEVICE_TYPE}\s*$$
  ^\s+Power\s+Source:\s+${POWER_SOURCE}\s*$$
  ^\s+Power\s+Priority:\s+${POWER_PRIORITY}\s*$$
  ^\s+Power\s+Requested:\s+${POWER_REQUESTED}\s+mW\s*$$
  ^\s*$$ -> Start

Med
  ^\s+Serial\s+number:\s+${SERIAL}\s*$$
  ^\s+Manufacturer:\s+${MANUFACTURER}\s*$$
  ^\s+Model:\s+${PLATFORM}\s*$$
  ^\s+H/W revision:\s+${HW_REVISION}\s*$$
  ^\s+F/W revision:\s+${FW_REVISION}\s*$$
  ^\s+S/W revision:\s+${SW_REVISION}\s*$$
  ^\s+\S+
  ^\s*$$
  ^\s*Total\s+entries\s+displayed -> Record
  ^\s*-+\s*$$ -> Continue.Record
  ^\s*-+\s*$$ -> Start
  ^.* -> Error
```
##### SAMPLE COMMAND OUTPUT
```
sh lldp nei det
------------------------------------------------
Local Intf: Gi1/0/22
Chassis id: ::
Port id: aabbccddeeff:P1
Port Description: SW PORT
System Name: SEPaabbccddeeff.phones.mycompany.domain

System Description:
Cisco IP Phone 6901,SCCP6901.9-3-1-SR2-2

Time remaining: 108 seconds
System Capabilities: T
Enabled Capabilities: T
Management Addresses:
    IP: 10.20.30.40
    IPV6: ::
Auto Negotiation - supported, enabled
Physical media capabilities:
    100base-TX(FD)
    100base-TX(HD)
    10base-T(FD)
    10base-T(HD)
Media Attachment Unit type: 16
Vlan ID: 999
Peer Source MAC: abcd.1234.efef

MED Information:

    MED Codes:
          (NP) Network Policy, (LI) Location Identification
          (PS) Power Source Entity, (PD) Power Device
          (IN) Inventory

    H/W revision: 1.0
    F/W revision: 6901.0-0-0-01-05
    S/W revision: SCCP6901.9-3-1-SR2-2
    Serial number: FCH12345GVM
    Manufacturer: Cisco Systems, Inc.
    Model: CP-6901
    Capabilities: NP, PD, IN
    Device type: Endpoint Class III
    Network Policy(Voice): VLAN data, untagged, Layer-2 priority: 5, DSCP: 46
    Network Policy(Voice Signal): VLAN data, untagged, Layer-2 priority: 3, DSCP: 46
    PD device, Power source: Unknown, Power Priority: Unknown, Wattage: 2.6
    Location - not advertised
```

##### SUMMARY
```
exception when using netmiko send_command('show lldp neighbors detail',use_textfsm="True") on a cisco IOS switch (C9200L-48P-4X      17.09.05          CAT9K_LITE_IOSXE)
```
##### STEPS TO REPRODUCE
Use the raw output of the command as typed on the switch

##### EXPECTED RESULTS
```
{'local_interface': 'Gi1/0/22', 'chassis_id': '', 'neighbor_port_id': 'aabbccddeeff:P1', 'neighbor_interface': 'SW PORT', 'neighbor_name': 'SEPaabbccddeeff.phones.company.domain', 'neighbor_description': 'Cisco IP Phone 6901,SCCP6901.9-3-1-SR2-2', 'capabilities': 'T', 'mgmt_address': '10.20.30.40', 'vlan_id': '999', 'mac_address': 'abcd.1234.efef', 'serial': 'FCH12345GVM', 'manufacturer': 'Cisco Systems, Inc.', 'hw_revision': '1.0', 'fw_revision': '6901.0-0-0-01-05', 'sw_revision': 'SCCP6901.9-3-1-SR2-2', 'platform': 'CP-6901', 'power_pair': '', 'power_class': '', 'power_device_type': '', 'power_priority': '', 'power_source': '', 'power_requested': ''}  
```
##### ACTUAL RESULTS
```
                lldp_nei = net_conn_acc.send_command('show lldp neighbors detail',use_textfsm="True")
Traceback (most recent call last):
  File "C:\Users\myself\my_script.py", line 3960, in audit_usr_stack
    lldp_nei = net_conn_acc.send_command('show lldp neighbors detail',use_textfsm="True")
  File "C:\Users\A0007473-R\AppData\Roaming\Python\Python39\site-packages\netmiko\base_connection.py", line 111, in wrapper_decorator
    return_val = func(self, *args, **kwargs)
  File "C:\Users\A0007473-R\AppData\Roaming\Python\Python39\site-packages\netmiko\utilities.py", line 596, in wrapper_decorator
    return func(self, *args, **kwargs)
  File "C:\Users\A0007473-R\AppData\Roaming\Python\Python39\site-packages\netmiko\base_connection.py", line 1834, in send_command
    return_val = structured_data_converter(
  File "C:\Users\A0007473-R\AppData\Roaming\Python\Python39\site-packages\netmiko\utilities.py", line 560, in structured_data_converter
    structured_output_tfsm = get_structured_data_textfsm(
  File "C:\Users\A0007473-R\AppData\Roaming\Python\Python39\site-packages\netmiko\utilities.py", line 380, in get_structured_data_textfsm
    output = _textfsm_parse(textfsm_obj, raw_output, attrs)
  File "C:\Users\myself\AppData\Roaming\Python\Python39\site-packages\netmiko\utilities.py", line 344, in _textfsm_parse
    tfsm_parse(raw_output, attrs)
  File "C:\Users\myself\AppData\Roaming\Python\Python39\site-packages\textfsm\clitable.py", line 282, in ParseCmd
    self.table = self._ParseCmdItem(self.raw, template_file=template_files[0])
  File "C:\Users\A0007473-R\AppData\Roaming\Python\Python39\site-packages\textfsm\clitable.py", line 315, in _ParseCmdItem
    for record in fsm.ParseText(cmd_input):
  File "C:\Users\myself\AppData\Roaming\Python\Python39\site-packages\textfsm\parser.py", line 895, in ParseText
    self._CheckLine(line)
  File "C:\Users\myself\AppData\Roaming\Python\Python39\site-packages\textfsm\parser.py", line 944, in _CheckLine
    if self._Operations(rule, line):
  File "C:\Users\myself\AppData\Roaming\Python\Python39\site-packages\textfsm\parser.py", line 1024, in _Operations
    raise TextFSMError('State Error raised. Rule Line: %s. Input Line: %s'
textfsm.parser.TextFSMError: State Error raised. Rule Line: 69. Input Line: Chassis id: ::
```

**Comment by jmcgill298** [comment]
@mcn29 can you put in a PR to fix this?

**Comment by mcn29** [comment]
@jmcgill298 assuming a PR means a pull request, I'll give it a try, it will take me some time as I'm a network admin, coding is new for me :-[

**Comment by jvanderaa** [comment]
Nothing better than working on these templates as a way to get started (personal opinion here). Thank you for opening the issue and working on it. Let us know if we can help @mcn29

**Comment by mjbear** [comment]
> Nothing better than working on these templates as a way to get started (personal opinion here). Thank you for opening the issue and working on it. Let us know if we can help @mcn29

:100:%

@mcn29 
GitHub munges the white space if the text isn't put in [code fences](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks). When you update the issue text above, I'd get new output from the CLI so you're sure the white space is likely to be preserved.

Code fences will also make sure the `# comments` within the textfsm template example in your post aren't interpreted as markdown headers creating some rather gnarly output on this thread. :laughing: 

You've got this one so I'll back off, but can still offer up a code review. :wink:

**Comment by mcn29** [comment]
> > Nothing better than working on these templates as a way to get started (personal opinion here). Thank you for opening the issue and working on it. Let us know if we can help @mcn29
> 
> 💯%
> 
> @mcn29 GitHub munges the white space if the text isn't put in [code fences](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks). When you update the issue text above, I'd get new output from the CLI so you're sure the white space is likely to be preserved.
> 
> Code fences will also make sure the `# comments` within the textfsm template example in your post aren't interpreted as markdown headers creating some rather gnarly output on this thread. 😆
> 
> You've got this one so I'll back off, but can still offer up a code review. 😉

@mjbear thanks for the offer and the tip, I edited my first post and put fences to prevent unwanted formating

**Comment by mcn29** [comment]
On second thought, this is a better fix :
```
Value CHASSIS_ID ([^:]+)
->
Value CHASSIS_ID (([^:]+|::))
```
because it retains the double column data which has a meaning (unassigned IPv6 address).

**Comment by mjbear** [comment]
> On second thought, this is a better fix :
> 
> ```
> Value CHASSIS_ID ([^:]+)
> ->
> Value CHASSIS_ID (([^:]+|::))
> ```
> 
> because it retains the double column data which has a meaning (unassigned IPv6 address).

@mcn29 
Does it make sense to keep the negated set? `[^:]`
~Maybe make CHASSIS_ID to be `\S+` since the capture group allows colons `:` now.~
:warning: Ehhh nope to `\S+` as it breaks the parsing.

Oh, there is whitespace in `tests/cisco_ios/show_lldp_neighbors_detail/cisco_ios_show_lldp_neighbors_detail5.raw`
with `Chassis id: S7-1200                   6DS7 212-1BH40-0XB0  S V-LCCC5820        10 V  4  3  1`

@jmcgill298 @jvanderaa
:rocket: But `.+` works fine and doesn't discombobulate the test data based on my test run.
`$ python cli.py gen-yaml-folder -f tests/cisco_ios/show_lldp_neighbors_detail/`

To all: Thoughts?

@mcn29
> [!TIP]
> When you put your raw data in a file within `tests/cisco_ios/show_lldp_neighbors_detail/`
> add it as a new file so old test data is retained. :wink:

**Comment by mcn29** [comment]
[^:] is still useful, it prevents processing a further new_field:new_value on the same line and goes to the Error instead.
```

**Comment by mjbear** [comment]
> [^:] is still useful, it prevents processing a further new_field:new_value on the same line and goes to the Error instead.
> 
> ```
> 
> ```

Hmm that code block is empty.

Ok, out of curiosity, is there test data to support that scenario?
(That would be slick to have and test against.)

**Comment by mcn29** [comment]
My bad, no code block was necessary after all.

I've never seen several fields:values on the same line so I don't have any test data.
In my understanding the [^:]  is a future safeguard

**Comment by mcn29** [comment]
I've raised my first pull request so bear with me.

I'm not sure about the YAML test file (cisco_ios_show_lldp_neighbors_detail6.yml) as it looks different from the existing ones, I just used a JSON to YAML converter.

**Comment by mjbear** [comment]
> I've raised my first pull request so bear with me.
> 
> I'm not sure about the YAML test file (cisco_ios_show_lldp_neighbors_detail6.yml) as it looks different from the existing ones, I just used a JSON to YAML converter.

@mcn29
All good - we've all been new at one point and I'm still learning too, haha.

There are [helper scripts](https://github.com/networktocode/ntc-templates/blob/master/docs/dev/dev_parser.md#development-helper-scripts) that can generate the parsed data based on the raw file being placed in the correct location.

I often run the helper script against an entire directory (as I hinted at above) so that I find out early if the parsed data changes. Sometimes the changes are alphabetical order of the keys, other times it could be an unexpected issue from modifying the template.
