### ISSUE TITLE
Cisco show mac address-table

### ISSUE THREAD

**Issue by i-m-d** [networktocode/ntc-templates#1896]
Hello,

 Why the template cisco_ios_show_mac-address-table.textfsm has:

Value DESTINATION_ADDRESS ([0-9a-fA-F]{4}\.[0-9a-fA-F]{4}\.[0-9a-fA-F]{4})
Value List DESTINATION_PORT ([^,\s]+)

and the template cisco_nxos_show_mac_address-table.textfsm has:

Value MAC_ADDRESS (\S+)
Value PORTS (\S+)

 I think would be better both has the same name:

Value MAC_ADDRESS xxx
Value PORTS xxx

 When i try to automate different Cisco Types same name are great.

NOTE: I have change locally the IOS template to the same name.

Best regards.

**Comment by jmcgill298** [comment]
that is just how the templates were submitted, and we did not do a good job of keeping names consistent early on. A lot of this has been cleaned up, and we are trying to get better and catching this. Feel free to submit a PR to update.
