### ISSUE TITLE
Test files for aruba os need renamed.

### ISSUE THREAD

**Issue by myyellowshoe** [networktocode/ntc-templates#224]
##### ISSUE TYPE

 - Bug Report
 - Documentation Report

##### SUMMARY

In all other case that I can tell there is a 1 to 1 of template names to test names.
It looks like the test folders and files for aruba os are incorrectly named. Interface is shortened to int.

**Template Names**
```
templates/aruba_os_show_ip_interface_brief.template
templates/aruba_os_show_ipv6_interface_brief.template
```

**Current Test Name**
```aruba_os/show_ip_int_brief/aruba_os_show_ip_int_brief.raw```

##### EXPECTED RESULTS
Expexcted to see test parsed/raw files named.

```
aruba_os/show_ip_int_brief/aruba_os_show_ip_interface_brief.parsed
aruba_os/show_ip_int_brief/aruba_os_show_ip_interface_brief.raw

aruba_os/show_ip_int_brief/aruba_os_show_ipv6_interface_brief.parsed
aruba_os/show_ip_int_brief/aruba_os_show_ipv6_interface_brief.raw
```

**Comment by myyellowshoe** [comment]
If this is an actual issue and I'm not missing something, happy to to put together a pull request for the change.

**Comment by jmcgill298** [comment]
They should be updated, and I believe those templates are not being tested for validity since they don't have the full name. Please put in the PR and I will merge.

**Comment by FragmentedPacket** [comment]
@myyellowshoe Do you have time to open PR with the changes so we can merge it?

**Comment by myyellowshoe** [comment]
Yeah, let me get something in this week.
