### ISSUE TITLE
cisco_asa_show_vpn-sessiondb_detail_l2l.template not parsing

### ISSUE THREAD

**Issue by murrad01** [networktocode/ntc-templates#231]
##### ISSUE TYPE

 - Bug Report

##### TEMPLATE USING

```
cisco_asa_show_vpn-sessiondb_detail_l2l.template
```

##### SAMPLE COMMAND OUTPUT

```
'\nSession Type: LAN-to-LAN Detailed\n\nConnection   : p.p.p.p\nIndex        : 508                    IP Addr      : p.p.p.p\nProtocol     : IKE IPsec\nEncryption   : 3DES                   Hashing      : SHA1\nBytes Tx     : 0                      Bytes Rx     : 12360\nLogin Time   : 06:59:55 PDT Sat Jul 21 2018\nDuration     : 3h:33m:32s\nIKE Tunnels: 1\nIPsec Tunnels: 1\n\nIKE:\n  Tunnel ID    : 508.1\n  UDP Src Port : 500                    UDP Dst Port : 500\n  IKE Neg Mode : Main                   Auth Mode    : preSharedKeys\n  Encryption   : 3DES                   Hashing      : SHA1\n  Rekey Int (T): 28800 Seconds          Rekey Left(T): 15987 Seconds\n  D/H Group    : 2\n  Filter Name  : acl_Tarzana\n  IPv6 Filter  : \n\nIPsec:\n  Tunnel ID    : 508.2\n  Local Addr   : x.x.x.x.0/255.255.252.0/0/0\n  Remote Addr  : y.y.y.y/255.255.255.255/0/0\n  Encryption   : 3DES                   Hashing      : SHA1                   \n  Encapsulation: Tunnel                 \n  Rekey Int (T): 28800 Seconds          Rekey Left(T): 15987 Seconds          \n  Idle Time Out: 30 Minutes             Idle TO Left : 29 Minutes             \n  Bytes Tx     : 0                      Bytes Rx     : 12360                  \n  Pkts Tx      : 0                      Pkts Rx      : 206                    \n  \nNAC:\n  Reval Int (T): 0 Seconds              Reval Left(T): 0 Seconds\n  SQ Int (T)   : 0 Seconds              EoU Age(T)   : 12813 Seconds\n  Hold Left (T): 0 Seconds              Posture Token: \n  Redirect URL : \n\nConnection 
```

##### SUMMARY

Not getting formatted data back, only a long string
##### STEPS TO REPRODUCE

```
output = net_conn.send_command("show vpn-sessiondb detail l2l", use_textfsm=True)
```

##### EXPECTED RESULTS

expected formatted data like I get from the following command
output = net_conn.send_command("show running-config tunnel-group", use_textfsm=True)

[{'name': 'x.x.x.x',
  'type': 'ipsec-l2l',
  'dhcp_selection': [],
  'dhcp_server': [],
  'authorization': '',
  'authorization_intfc': '',
  'authorization_grp': '',
  'accounting_grp': '',
  'ipv4_pool_intfc': '',
  'ipv4_pool_name': '',
  'authentication_intfc': '',
  'authentication_pri_grp': '',
  'authentication_sec_grp': '',
  'authentication_svr': '',
  'authenticated_user': '',
  'group_policy': 'gp-lab1',
  'ipv6_pool_intfc': '',
  'ipv6_pool_name': '',
  'nat_intfc': '',
  'scep_enroll': '',
  'sec_authentication_grp_intfc': '',
  'sec_authentication_pri_grp': '',
  'sec_authentication_sec_grp': '',
  'sec_authentication_use_pri_user': '',
  'sec_cert_codes': '',
  'sec_cert_fallback': '',
  'pri_cert_codes': '',
  'pri_cert_fallback': '',
  'strip_grp': '',
  'strip_realm': '',
  'ikev1_psk': '',
  'chain': '',
  'client_os': [],
  'update_url': [],
  'revs': [],
  'trust_point': '',
  'ikev1_user_auth_intfc': [],
  'ikev1_user_auth_type': [],
  'ikev2_local_auth_cert': '',
  'ikev2_remote_auth_type': [],
  'peer_id_validate': '',
  'radius_with_expiry': '',
  'ppp_auth_type': [],
  'webvpn_auth': '',
  'webvpn_custom': '',
  'dns_grp': '',
  'webvpn_grp_alias': [],
  'webvpn_grp_alias_state': [],
  'webvpn_grp_url': [],
  'webvpn_grp_url_state': [],
  'nbns_svr': [],
  'nbns_master': [],
  'nbns_timeout': [],
  'nbns_retry': [],
  'override_svc_download': '',
  'pri_prefill_user_type': [],
  'sec_prefill_user_type': [],
  'proxy_auth': '',
  'radius_reject_msg': '',
  'saml_id_provider': '',
  'without_csd': ''},
##### ACTUAL RESULTS

```
'\nSession Type: LAN-to-LAN Detailed\n\nConnection   : 69.238.162.252\nIndex        : 508                    IP Addr      : 69.238.162.252\nProtocol     : IKE IPsec\nEncryption   : 3DES                   Hashing      : SHA1\nBytes Tx     : 0                      Bytes Rx     : 12360\nLogin Time   : 06:59:55 PDT Sat Jul 21 2018\nDuration     : 3h:33m:32s\nIKE Tunnels: 1\nIPsec Tunnels: 1\n\nIKE:\n  Tunnel ID    : 508.1\n  UDP Src Port : 500                    UDP Dst Port : 500\n  IKE Neg Mode : Main                   Auth Mode    : preSharedKeys\n  Encryption   : 3DES                   Hashing      : SHA1\n  Rekey Int (T): 28800 Seconds          Rekey Left(T): 15987 Seconds\n  D/H Group    : 2\n  Filter Name  : acl_Tarzana\n  IPv6 Filter  : \n\nIPsec:\n  Tunnel ID    : 508.2\n  Local Addr   : 166.124.120.0/255.255.252.0/0/0\n  Remote Addr  : 170.220.248.71/255.255.255.255/0/0\n  Encryption   : 3DES                   Hashing      : SHA1                   \n  Encapsulation: Tunnel                 \n  Rekey Int (T): 28800 Seconds          Rekey Left(T): 15987 Seconds          \n  Idle Time Out: 30 Minutes             Idle TO Left : 29 Minutes             \n  Bytes Tx     : 0                      Bytes Rx     : 12360                  \n  Pkts Tx      : 0                      Pkts Rx      : 206                    \n  \nNAC:\n  Reval Int (T): 0 Seconds              Reval Left(T): 0 Seconds\n  SQ Int (T)   : 0 Seconds              EoU Age(T)   : 12813 Seconds\n  Hold Left (T): 0 Seconds              Posture Token: \n  Redirect URL : \n\nConnection 
```

**Comment by FragmentedPacket** [comment]
Did you follow the step in this article for setting it up? https://pynet.twb-tech.com/blog/automation/netmiko-textfsm.html

Did you put the templates in your home directory or set an environment variable for the location of the templates? Typically, when you get unstructured data, it is due to it not being able to find the templates.

I can test this at work as well, but figured I'd at least have you check some of the basics prior to that.

**Comment by murrad01** [comment]
Yes, the templates are in my home directory.  Other templates are working
fine.

Thanks!

**Comment by FragmentedPacket** [comment]
Looks like I'm able to reproduce the issue as well. I'll try and work on it over the next few days, but someone else might possibly chime in before.

**Comment by murrad01** [comment]
Thanks for checking this out, really appreciate it.

BTW, I wanted to take a stab a creating my own templates.  Any
recommendations for resource material?

Thanks!

**Comment by FragmentedPacket** [comment]
I just kind of jumped in and helped people, I believe. The TextFSM templates I first worked on were way less convoluted than this one.

You may want to read a blog post Jason has in regards to this:
http://jedelman.com/home/programmatic-access-to-cli-devices-with-textfsm/

Jason's blog has a link to a regex parser online that I use as well when troubleshooting/creating templates.

I've used this site as well:
https://github.com/google/textfsm/wiki/TextFSM

You're also more than welcome to join NetworkToCode Slack. The feedback loop is much faster and short as well: 
https://networktocode.slack.com/

**Comment by murrad01** [comment]
Not sure how I request an account for networktocode.slack.com

Sign in to networktocode

networktocode.slack.com


Don't have an account on this workspace yet?Contact the workspace
administrator for an invitation

**Comment by FragmentedPacket** [comment]
Here it is:
http://slack.networktocode.com/

**Comment by murrad01** [comment]
thanks!

**Comment by murrad01** [comment]
Here's a section of my submitted output.  Shouldn't this work?  Wouldn't the NAC section just be ignored?

'\nSession Type: LAN-to-LAN Detailed\n\nConnection

**Comment by jmcgill298** [comment]
ya, I think I chopped that off when I was reformatting the `\n` to be newlines. I think the NAC is causing the issue b/c of the `EOF` in the template. I can get some data to record by removing that, but then there are other issues with the `Record`, so this template really needs more work than I have time for at this moment

**Comment by FragmentedPacket** [comment]
https://github.com/networktocode/ntc-templates/pull/237

I think I have it figured out, but feedback is welcomed.
