### ISSUE TITLE
Build is failing in Travis CI

### ISSUE THREAD

**Issue by niralkk** [networktocode/ntc-templates#240]
Kindly check, my build is getting failed with below error

vmware_nsxv_show_ip_route2
----> passed
==================================================
The command "python test-templates.py" exited with 1.
Done. Your build exited with 1.

**Comment by jmcgill298** [comment]
The tests pass fine against master. I see several failures against the suggested edits you have in your PR. I have made a few requests against your PR, and breaking it up into several PRs will make it easier and faster to fix. You can run `pytest` locally to validate the templates against the test day before making commits and pushing upstream.
