### ISSUE TITLE
cisco_xr_show_cdp_neighbors_detail.template shows remote and local interface incorrectly

### ISSUE THREAD

**Issue by fallenarc** [networktocode/ntc-templates#277]
##### ISSUE TYPE

 - Bug Report

##### TEMPLATE USING

cisco_xr_show_cdp_neighbors_detail.template

```

```

##### SAMPLE COMMAND OUTPUT

-------------------------
Device ID: RCMT-RSDVR01
SysName : 
Entry address(es): 
  IPv4 address: 172.19.0.3
Platform: cisco WS-C3850-48T,  Capabilities: Router Switch IGMP 
Interface: TenGigE0/0/0/6
Port ID (outgoing port): TenGigabitEthernet4/0/24
Holdtime : 131 sec

Version :
Cisco IOS Software, IOS-XE Software, Catalyst L3 Switch Software (CAT3K_CAA-UNIVERSALK9-M), Version 03.07.05E RELEASE SOFTWARE (fc1)
Technical Support: http://www.cisco.com/techsupport
Copyright (c) 1986-2017 by Cisco Systems, Inc.
Compiled Fri 10-Feb-17 07:59 by prod_rel_team

advertisement version: 2
VTP Management Domain: 'RCMT-RSDVR'
Duplex: full

```

```

##### SUMMARY
The output above is done from a Cisoc ASR9010 with a Cisco IOS device as it's neighbor. As you can see from the output. The local interface  is shown next to "Interface and remote interface is shown on "outgoing interface"

##### STEPS TO REPRODUCE

```yaml

```

##### EXPECTED RESULTS
 Simple, Values for Remote and local need to be swapped 

##### ACTUAL RESULTS

```

```

**Comment by jmcgill298** [comment]
@fallenarc I have a fix in my fork, feel free to pull that down and test. [jmcgill298/xr_cdp](https://github.com/jmcgill298/ntc-templates/tree/xr_cdp)

**Comment by fallenarc** [comment]
@jmcgill298 Yep that'll get it. Thanks!
