### ISSUE TITLE
New Template Request

### ISSUE THREAD

**Issue by sakabio** [networktocode/ntc-templates#286]
##### ISSUE TYPE

 - Feature Idea

##### SUMMARY

Can you add templates for show interface description for Cisco devices
##### STEPS TO REPRODUCE
Output should be similar to show interface status

**Comment by itdependsnetworks** [comment]
@sakabio Thanks for your interest in the project!

There are hundreds if not thousands of commands that could be in scope, and they essentially they are delivered on an as needed basis. I highly suggest take one of the following routes:

- Develop the templates and tests, and contribute them back
- Find someone within your scope of influence to do that for you
- Join the slack.networktocode.com channel, and ask for assistance on the #networktocode channel there

Unfortunately we do not take requests for additions right now.
