### ISSUE TITLE
show ip route IOS vs NXOS

### ISSUE THREAD

**Issue by kevindasilva03** [networktocode/ntc-templates#382]
##### ISSUE TYPE

 - Bug Report

##### TEMPLATE USING

```
Value Filldown PROTOCOL (\w)
Value Filldown TYPE (\w{0,2})
Value Required,Filldown NETWORK (\d{1,3}.\d{1,3}.\d{1,3}.\d{1,3})
Value Filldown MASK (\d{1,2})
Value DISTANCE (\d+)
Value METRIC (\d+)
Value NEXTHOP_IP (\d{1,3}.\d{1,3}.\d{1,3}.\d{1,3})
Value NEXTHOP_IF ([A-Z][\w\-\.:/]+)
Value UPTIME (\d[\w:\.]+)

Start
  ^Gateway.* -> Routes

Routes
  # For "is (variably )subnetted" line, capture mask, clear all values.
  ^\s+\d{1,3}.\d{1,3}.\d{1,3}.\d{1,3}\/${MASK}\sis -> Clear
  #
  # Match directly connected route with explicit mask
  ^${PROTOCOL}(\s|\*)${TYPE}\s+${NETWORK}\/${MASK}\sis\sdirectly\sconnected,\s${NEXTHOP_IF} -> Record
  #
  # Match directly connected route (mask is inherited from "is subnetted")
  ^${PROTOCOL}(\s|\*)${TYPE}\s+${NETWORK}\sis\sdirectly\sconnected,\s${NEXTHOP_IF} -> Record
  #
  # Match regular routes, with mask, where all data in same line
  ^${PROTOCOL}(\s|\*)${TYPE}\s+${NETWORK}\/${MASK}\s\[${DISTANCE}/${METRIC}\]\svia\s${NEXTHOP_IP}(,\s${UPTIME})?(,\s${NEXTHOP_IF})? -> Record
  #
  # Match regular route, all one line, where mask is learned from "is subnetted" line
  ^${PROTOCOL}(\s|\*)${TYPE}\s+${NETWORK}\s\[${DISTANCE}\/${METRIC}\]\svia\s${NEXTHOP_IP}(,\s${UPTIME})?(,\s${NEXTHOP_IF})? -> Record
  #
  # Match route with no via statement (Null via protocol)
  ^${PROTOCOL}(\s|\*)${TYPE}\s+${NETWORK}\/${MASK}\s\[${DISTANCE}/${METRIC}\],\s${UPTIME},\s${NEXTHOP_IF} -> Record
  #
  # Match "is a summary" routes (often Null0)
  ^${PROTOCOL}(\s|\*)${TYPE}\s+${NETWORK}\/${MASK}\sis\sa\ssummary,\s${UPTIME},\s${NEXTHOP_IF} -> Record
  #
  # Match regular routes where the network/mask is on the line above the rest of the route
  ^${PROTOCOL}(\s|\*)${TYPE}\s+${NETWORK}\/${MASK} -> Next
  #
  # Match regular routes where the network only (mask from subnetted line) is on the line above the rest of the route
  ^${PROTOCOL}(\s|\*)${TYPE}\s+${NETWORK} -> Next
  #
  # Match the rest of the route information on line below network (and possibly mask)
  ^\s+\[${DISTANCE}\/${METRIC}\]\svia\s${NEXTHOP_IP}(,\s${UPTIME})?(,\s${NEXTHOP_IF})? -> Record
  #
  # Match load-balanced routes
  ^\s+\[${DISTANCE}\/${METRIC}\]\svia\s${NEXTHOP_IP} -> Record
  #
  # Clear all variables on empty lines
  ^\s* -> Clearall

EOF
```

##### SAMPLE COMMAND OUTPUT

```
route_output = net_conn.send_command("show ip route vrf xxx y.y.y.y", use_textfsm=True)
```

##### SUMMARY

When using textfsm for to show the ip route with a hostname, I get different results with IOS vs NXOS.

With IOS, it return a string. With NXOS, it returns a list of dictionaries, as I would expect. 

FYI... I'm using Netmiko and not sure if it's related to that module vs using textFSM independently. 

##### STEPS TO REPRODUCE

route_output = net_conn.send_command("show ip route vrf xxx y.y.y.y", use_textfsm=True)

```yaml

```

##### EXPECTED RESULTS

NXOS - returning a list of dictionaries 
[{'protocol': 'ospf-800',
  'type': 'intra',
  'network': '10.25.176.0',
  'mask': '24',
  'distance': '110',
  'metric': '2',
  'nexthop_ip': '10.1.12.29',
  'nexthop_if': 'Vlan1806',
  'uptime': '11w1d',
  'nexthop_vrf': '',
  'tag': '',
  'segid': '',
  'tunnelid': '',
  'encap': ''},
 {'protocol': 'ospf-800',
  'type': 'intra',
  'network': '10.25.176.0',
  'mask': '24',
  'distance': '110',
  'metric': '2',
  'nexthop_ip': '10.1.24.29',
  'nexthop_if': 'Vlan1871',
  'uptime': '11w1d',
  'nexthop_vrf': '',
  'tag': '',
  'segid': '',
  'tunnelid': '',
  'encap': ''}]

##### ACTUAL RESULTS

```


IOS - returning a string

'Routing entry for 10.25.0.0/16\n  Known via "ospf 100", distance 110, metric 29, type inter area\n  Last update from 10.1.64.5 on Vlan1298, 7w0d ago\n  Routing Descriptor Blocks:\n  * 10.1.64.5, from 10.1.77.2, 7w0d ago, via Vlan1298\n      Route metric is 29, traffic share count is 1'


```

**Comment by FragmentedPacket** [comment]
@kevindasilva03 This appears to be that the NXOS template has more use cases built out. There is no special handling for the output returned from `show ip route vrf xxx y.y.y.y` within the `cisco_ios_show_ip_route.template`, but for regular output from `show ip route` should work, but does require additional work to find what you're looking to match after you get the structured data back.

If you'd like to submit a PR for this, that would be great and we'd be more than happy to help either via Github or our public Slack.

**Comment by FragmentedPacket** [comment]
I'm going to go ahead and close this issue. If you'd like to revisit this and need some help, please reach out via another issue or on our public Slack.
