### ISSUE TITLE
Huawei - display lldp neighbor formatting

### ISSUE THREAD

**Issue by Abed1985** [networktocode/ntc-templates#396]
Hi , 
it will be greate if somebody can assist formating the below output . I am struggling to get it working , I did the arp one easy , but this require alot of work, any tips at least to which template might help reverse engineer this ?

<> display lldp neighbor 

GigabitEthernet0/0/0 has 0 neighbors

GigabitEthernet0/0/1 has 1 neighbors:

Neighbor index : 1
Chassis type   :macAddress 
Chassis ID     :f41f-c2c5-e180 
Port ID type   :interfaceName 
Port ID        :Gi1/0/1
Port description    :GigabitEthernet1/0/1
**System name         :tsa-2960-sw01**
**System description  :Cisco IOS Software, C2960S Software (C2960S-UNIVERSALK9-M), Version 12.2(55)SE7, RELEASE SOFTWARE (fc1)**
Technical Support: http://www.cisco.com/techsupport
Copyright (c) 1986-2013 by Cisco Systems, Inc.
Compiled Mon 28-Jan-13 10:28 by prod_rel_team
System capabilities supported   :bridge router 
System capabilities enabled     :bridge 
Management address type  :ipV4
**Management address       : 192.168.0.240**  
Expired time   :102s

Port VLAN ID(PVID)  :1
Protocol identity   :

Auto-negotiation supported    :Yes 
Auto-negotiation enabled      :Yes
OperMau   :speed(1000)/duplex(Full)

Power port class         :PD 
PSE power supported      :No 
PSE power enabled        :No 
PSE pairs control ability:No 
Power pairs              :Unknown 
Port power classification:Unknown

Link aggregation supported:No 
Link aggregation enabled :No 
Aggregation port ID      :0 
Maximum frame Size       :0

MED Device information             
Device class   :Network Connectivity

HardwareRev       :WS-C2960S-48LPS-L (PowerPC):F0
FirmwareRev       :NA
SoftwareRev       :12.2(55)SE7
SerialNum         :NA
**Manufacturer name :Cisco Systems, Inc.**
**Model name        :WS-C2960S-48LPS-L**
Asset tracking identifier :NA

Media policy type   :Voice 
Unknown Policy      :Unknown 
VLAN tagged         :No 
Media policy VlanID      :0 
Media policy L2 priority :0 
Media policy Dscp        :0

Power Type               :PSE 
PoE PSE power source     :PSE 
Port PSE Priority        :Low 
Port Available power value:0

Location format     :Civic Address LCI
Location information:what(LLDP-MED Endpoint)  country(  )
 Ca type   Ca value
GigabitEthernet0/0/2 has 0 neighbors

GigabitEthernet0/0/3 has 0 neighbors

GigabitEthernet0/0/4 has 0 neighbors

GigabitEthernet0/0/5 has 0 neighbors

GigabitEthernet0/0/6 has 0 neighbors

GigabitEthernet0/0/7 has 0 neighbors

GigabitEthernet0/0/8 has 0 neighbors

GigabitEthernet0/0/9 has 0 neighbors

GigabitEthernet0/0/10 has 0 neighbors

**Comment by Abed1985** [comment]
I have parsed what I need using the below :

cat huawei_display_lldp_neighbor.template 

`Value SYSTEM_NAME (\S+)
Value MANAGEMENT_ADDRESS (\d+.\d+.\d+.\d+)
Value MANUFACTURER_NAME (.*)
Value MODEL_NAME (.*)


Start
  ^System name.+:${SYSTEM_NAME} 
  ^Management address.+:\s${MANAGEMENT_ADDRESS} 
  ^Manufacturer name.+:${MANUFACTURER_NAME}
  ^Model name.+:${MODEL_NAME} -> Record`


Sample output:

python3 test-huawei-lldp.py                 
`[{'system_name': 'tsa-2960-sw01', 'management_address': '192.168.0.240', 'manufacturer_name': 'Cisco Systems, Inc.', 'model_name': 'WS-C2960S-48LPS-L'}]`

**Comment by Abed1985** [comment]
its always parsing a single value neighbor ,, any ideas where this is going wrong? guess thats not the correct way of parsing

**Comment by Abed1985** [comment]
Record start it is ! sorry

**Comment by FragmentedPacket** [comment]
@Abed1985 Did you get this sorted out?

**Comment by Abed1985** [comment]
> 
> 
> @Abed1985 Did you get this sorted out?

Yes. I parsed what I need from this output , using the following , if it addresses all the output I would have contributed back :) Thanks


Value SYSTEM_NAME (\S+)
Value MANAGEMENT_ADDRESS (\d+.\d+.\d+.\d+)
Value MANUFACTURER_NAME (.*)
Value MODEL_NAME (.*)


Start
  ^System name.+:${SYSTEM_NAME} 
  ^Management address.+:\s${MANAGEMENT_ADDRESS} 
  ^Manufacturer name.+:${MANUFACTURER_NAME}
  ^Model name.+:${MODEL_NAME} -> Record Start

**Comment by FragmentedPacket** [comment]
@Abed1985 Would you mind submitting a PR for this?

You should be able to reference PR #398
