### ISSUE TITLE
README Documentation missing setup information

### ISSUE THREAD

**Issue by robobeaver6** [networktocode/ntc-templates#411]
##### ISSUE TYPE

 - Documentation Report

##### TEMPLATE USING

```
N/A
```

##### SAMPLE COMMAND OUTPUT

```
N/A
```

##### SUMMARY
Documentation README.md does not include any initial setup or prerequisite requirements.
It also does not give any info on how to run the tests.

##### STEPS TO REPRODUCE
Setup from scratch with 
`git clone https://github.com/networktocode/ntc-templates.git`

##### EXPECTED RESULTS
1.  git clone https://github.com/networktocode/ntc-templates.git
2.  Setup a virtual environment
3.  Run Tests.  I assume this is done with the `test-templates.py` script, but it does not say in the README.md as far as I can see.

##### ACTUAL RESULTS
I don't know if I have missed some fundamental piece of information somewhere, but as far as I can see there is no information in the README, ore elsewhere in the repo, to explain the base requirements for running the tests.  Also there is no info on how to run them.
After cloning the repo, I have no idea what the requirements are, and I am now just guessing as I come across errors.

I found out on the slack channel to use tox to run it.  I suggest adding that to the README.md

**Comment by robobeaver6** [comment]
I have added a PR for this issue (#414).  It adds a few lines to tell people to use TOX and also addes a Pipfile so the requirements can be easily installed in a venv.

**Comment by jmcgill298** [comment]
#452
