### ISSUE TITLE
Index sequence tests do not test command ordering correctly

### ISSUE THREAD

**Issue by robobeaver6** [networktocode/ntc-templates#417]
##### ISSUE TYPE

 - Bug Report

##### SUMMARY

The test_index_order.py test does not test the commands correctly.  
The template index rules state:
```
OS in alphabetical order
Command in length other
When Length is the same, use alphabetical order
Keep space between OS's
```
However, the test splits the template file name into vendor_os and command, but the file name is not always the command.  The command is the last field on the line.  there could potentially be two commands pointing to the same template file.  For example,  I have the following in my templates:
```
arista_eos_show_ip_bgp.template, .*, arista_eos, sh[[ow]] i[[p]] bg[[p]] ne[[ighbors]] (\S+) ad[[vertised-routes]]
arista_eos_show_ip_bgp.template, .*, arista_eos, sh[[ow]] i[[p]] bg[[p]] ne[[ighbors]] (\S+) rec[[eived-routes]]
```
It is important that the sequencing be correct, as the command is significantly longer than the template, and you need to sequence according to the actual command, but the output is equivalent to the basic `show ip bgp` command, so the same template should be used to avoid duplication.
To correct this, lines 117 and 118 should be changed to:
```
        os = row[2].strip()
        cmd = row[3].strip()
```
Line 116 should be deleted as it is now redundant.  
This IMHO is a more correct test, as it more accurately tests how the command regex is processed by TextFSM.  It is also simpler.
You might find that correctly testing the command results in a need to re-sequence the file.
Arguably, it might be desirable to strip the square brackets out and compare the command without them.
##### STEPS TO REPRODUCE
Run the tests

##### EXPECTED RESULTS
Compare the commands, not the template file name elements

##### ACTUAL RESULTS
template file name is compared.

**Comment by itdependsnetworks** [comment]
Let's track in #418
