### ISSUE TITLE
Cisco IOS Show Run Template

### ISSUE THREAD

**Issue by kesabo** [networktocode/ntc-templates#469]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Please forgive me if this is not the correct approach to handle this. I am new to Github.

Is there a current effort towards parsing the Cisco IOS 'show running-config' command into a template? Many of the things we do at my current place of employment works off of 'show running-config' validations.

I am interested in contributing to a template for this, but I do not want to start a whole new template for such a large task if one is already being worked on.

This could be designed as a whole template, or as a series of templates using 'show run | sec ^interface' for the interface parser for example.

What are people's thoughts on this? And is there any current effort towards this?

**Comment by itdependsnetworks** [comment]
We would likely want to do this in yangify/ntc-rosetta. You can find more information here: https://www.networktocode.com/blog/post/yangify-is-released/

If you want to have further real time conversation, it may be easier on the #networktocode channel on out public slack. You can auto sign up for it at http://slack.networktocode.com

**Comment by kesabo** [comment]
This is interesting, but the problem with that is two-fold.

Firstly, many companies are marred by antiquated design engineers who refuse to allow for NETCONF/RESTCONF protocols to be used in their network. It is my understanding that a YANG based solution would be useless in a CLI-based 'show' only environment, correct me if I am wrong here.

Secondly, Netmiko does not currently have a native support for this new project. Netmiko utilizes the NTC-Templates for its TextFSM parsing.

As I am part of an organization that is limited by both of these problems, I would be most interested in building or contributing to a template (or series of templates) for parsing the 'show run' command.

Thoughts?

**Comment by jabelk** [comment]
hi @kesabo , I suggest you look at the docs for ntc-rosetta / yangify:
https://ntc-rosetta.readthedocs.io/en/latest/
the project does not require any protocols, it is a parsing / rendering engine offline based on Yang data models and Python objects. You could use netmiko, napalm or whatever to push / pull the config. 
See my demo here:
https://github.com/jabelk/rosetta-yangify-nornir-demo
note that even though I connect to the devices (with napalm ssh), the same could have been accomplished completely offline.

**Comment by jmcgill298** [comment]
Thanks for the interest, we discussed this some more, and we think it is best to not include the show run commands as that will be difficult to capture all possible outputs, and will cause Errors when parsing the output.
