### ISSUE TITLE
need a help on escaping the parenthesis 

### ISSUE THREAD

**Issue by Rashmi-Nuviso** [networktocode/ntc-templates#47]
Hi All ,

can anybody help me how do i escape the paranthesis

my requirement is to pull the X86_64_LINUX_IOSD-UNIVERSALK9-M

from the build from the cisco show version output

Cisco IOS Software, CSR1000V Software (X86_64_LINUX_IOSD-UNIVERSALK9-M),

since textfsm has the definition where most of the pattern we want to fetch it needs to be grouped

if i try like

pattern = ((.*)) to extract the (X86_64_LINUX_IOSD-UNIVERSALK9-M)

the textFSM throws the error .

any help on this will be appreciated .

**Comment by GGabriele** [comment]
Hi,
you can escape parenthesis with a `\`. Your pattern would be `pattern = (\(.*\))`

**Comment by itdependsnetworks** [comment]
I would have the outside `()` escaped and not in the capture group and label it a different variable. That being said, it will be easiest to see the full output.

**Comment by Rashmi-Nuviso** [comment]
pasting the solution suggested by Ken here for others who are  would like pull the build X86_64_LINUX_IOSD-UNIVERSALK9-M  from the  line 

Cisco IOS Software, CSR1000V Software (X86_64_LINUX_IOSD-UNIVERSALK9-M), Version 15.5(3)S2, RELEASE SOFTWARE (fc2)

of the  show version command 

`^.*Software\s.*\(${BUILD}\),\sVersion\s${VERSION},*\s+RELEASE.*`

Closing this issue . 

Thanks Ken :)
