### ISSUE TITLE
"Cisco IOS show authentication session" issue when session count exceeds ~10

### ISSUE THREAD

**Issue by juggah** [networktocode/ntc-templates#473]
##### ISSUE TYPE

 - Template Creation Help
##### TEMPLATE USING
cisco_ios_show_authentication_sessions.template

Value INTERFACE (.+?)
Value MAC (.+?)
Value METHOD (.+?)
Value DOMAIN (.+?)
Value STATUS (.+?)
Value SESSION (\w+?)

Start
  ^Interface\s+MAC Address\s+Method\s+Domain -> Catch

Catch
  ^${INTERFACE}\s+${MAC}\s+${METHOD}\s+${DOMAIN}\s+${STATUS}\s+${SESSION}$$ -> Record
  ^.* -> Start

##### SAMPLE COMMAND OUTPUT

Example 1:
sw-bbz-ham-1
Interface                MAC Address    Method  Domain  Status Fg  Session ID
--------------------------------------------------------------------------------------------
Gi2/0/9                  001a.e803.3419 mab     VOICE   Auth        0A3C01F90005350CA150251E
Gi2/0/11                 001a.e803.c168 mab     VOICE   Auth        0A3C01F90000000D3F641919
Gi2/0/7                  001a.e803.c152 mab     VOICE   Auth        0A3C01F9000BE837682F6765
Gi1/0/14                 0021.8628.90f3 N/A     UNKNOWN Unauth    0A3C01F9000B97FE47E69FE7
Te3/0/47                 0021.b7e5.6c18 dot1x   DATA    Auth        0A3C01F90008AA7D0549F033
Gi2/0/6                  c85b.760b.8633 dot1x   DATA    Auth        0A3C01F9000BE74B67D17B98
Gi1/0/13                 0021.8628.747b N/A     UNKNOWN Unauth   A3C01F9000B980047E6ABBB
Gi2/0/12                 c85b.760b.8a80 dot1x   DATA    Auth        0A3C01F9000AE83E000DA4CD
Gi2/0/4                  0021.b715.37e6 dot1x   DATA    Auth        0A3C01F9000BE51266EC98A8
Gi2/0/10                 c85b.760b.9037 dot1x   DATA    Auth        0A3C01F9000BE5B4672D4FD2
Gi1/0/15                 00c0.b7ca.eb66 N/A     UNKNOWN Unauth    0A3C01F9000B980147E708BB
Gi2/0/21                 0021.b745.6c28 dot1x   DATA    Auth        0A3C01F9000A661BCD4080A5
Gi2/0/6                  001a.e803.3412 mab     VOICE   Auth        0A3C01F90000000E3F641B8C
Te3/0/48                 f80f.41ad.37f6 dot1x   DATA    Auth        0A3C01F9000B86C63FCA8486

Session count = 14

Example 2:
sw-bbz-stu-4#

Interface    MAC Address    Method  Domain  Status Fg Session ID
Gi0/1        0014.c123.93a1 N/A     UNKNOWN Unauth    0A3C07F6000015D0F0A2D2EC
Gi0/1        0021.b715.3707 dot1x   DATA    Auth      0A3C07F6000015CFF0A2753F
Gi0/7        001a.e803.3498 N/A     UNKNOWN Unauth    0A3C07F6000010092FAA658A
Gi0/8        001a.e803.2c26 N/A     UNKNOWN Unauth    0A3C07F600000017000C7A43
Gi0/6        0896.ad9d.115e N/A     UNKNOWN Unauth    0A3C07F6000006D7DE31AF5E

Session count = 5

##### SUMMARY

If session count exceeds ~10 Cisco IOS adds a dashed line between the  header and the data. This leads to textfsm not recording the data when session count is > ~10.
I added the dotted line to the template like this:

Start
  ^Interface\s+MAC Address\s+Method\s+Domain,
  ^.*----- -> Catch

This works for session count >~10. Is there a way to combine the two conditions in one template somehow ?

**Comment by juggah** [comment]
Im sorry for the large&bold letters in the middle of the post. Couldnt set the formatting to default on this section.

**Comment by FragmentedPacket** [comment]
I would say that we can change the template to:
```
Value INTERFACE (.+?)
Value MAC (.+?)
Value METHOD (.+?)
Value DOMAIN (.+?)
Value STATUS (.+?)
Value SESSION (\w+?)

Start
  ^Interface\s+MAC Address\s+Method\s+Domain -> Catch

Catch
  ^---
  ^${INTERFACE}\s+${MAC}\s+${METHOD}\s+${DOMAIN}\s+${STATUS}\s+${SESSION}$$ -> Record
  ^.* -> Start
```

Do you mind testing that and then opening a PR with the change and a new **raw** and **parsed** with the outputs with `---` in it?
