### ISSUE TITLE
Cisco IOS LLDP

### ISSUE THREAD

**Issue by feisa** [networktocode/ntc-templates#484]
we are running the following 
- name: Gather LLDP Neighbors
  ntc_show_command:
    connection: ssh
    platform: cisco_ios
    template_dir: /usr/lib/python2.7/site-packages/napalm_ansible/ntc-ansible/ntc-templates/templates/
    command: 'sh lldp neighbors'
    host: "{{ inventory_hostname }}"
    username: networklogin
    password: "{{ networklogin_password }}"
  register: neighbors

but ntc returns no value for lldp neighbors 

    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "changed": false,
    "invocation": {
        "module_args": {
            "command": "sh lldp neighbors",
            "connection": "ssh",
            "connection_args": {},
            "delay": "1",
            "file": null,
            "global_delay_factor": "1",
            "host": "test-leafc001",
            "index_file": "index",
            "key_file": null,
            "local_file": null,
            "optional_args": {},
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "platform": "cisco_ios",
            "port": null,
            "provider": null,
            "secret": null,
            "template_dir": "/usr/lib/python2.7/site-packages/modules/ntc-ansible/ntc-templates/templates/",
            "trigger_device_list": null,
            "use_keys": false,
            "use_templates": true,
            "username": "networklogin"
        }
    },
    "response": [],
    "response_list": []
}

**Comment by feisa** [comment]
any update?

**Comment by jmcgill298** [comment]
What is the result when you set `use_templates` to `false`?

**Comment by feisa** [comment]
the response is this 

 "Capability codes:\n    (R) Router, (B) Bridge, (T) Telephone, (C) DOCSIS Cable Device\n    (W) WLAN Access Point, (P) Repeater, (S) Station, (O) Other\n\nDevice ID           Local Intf     Hold-time  Capability      Port ID\ntestspinc001.hq.crabTwe1/1/1       120        B,R             Ethernet1/41\ntestrschx007.hq.crabGi1/0/38       120        B               mgmt\ntestrschx006.hq.crabGi1/0/12       120        S               mgmt\ntestrschx004.hq.crabGi1/0/10       120        S               mgmt\ntestspinc002.hq.crabTwe1/1/2       120        B,R             Ethernet1/41\ntestrschx002.hq.crabGi1/0/14       120        B,R             mgmt\n\nTotal entries displayed: 6\

**Comment by jmcgill298** [comment]
What happens if you save that output to a file and use TextFSM to parse it using the template?
I have the latest version of TextFSM so the command looks like: `python ~/venv/ntcansible/lib/python3.6/site-packages/textfsm/parser.py templates/cisco_ios_show_lldp_neighbors.template lldp_output.txt`

What version of ntc-ansible do you have? If you updated the ntc-templates repo, what commit is your HEAD pointing to?

**Comment by jmcgill298** [comment]
I believe #376 might be the fix that you need to incorporate into your templates

**Comment by feisa** [comment]
I tried the fix in 376 but that didnt work 

I just recloned the templates 

b6f5463317eb787acc87260350375210b3de6949 HEAD
813f1c9cdcd93186ebc0d5ee0a512a93ff74b041 refs/heads/master
813f1c9cdcd93186ebc0d5ee0a512a93ff74b041 refs/remotes/origin/HEAD
259e67c1c0272fe9c71fb98ab67d33f932790293 refs/remotes/origin/itdependsnetworks-bfd_cdp
813f1c9cdcd93186ebc0d5ee0a512a93ff74b041 refs/remotes/origin/master
6370da768d7f4441e031b9c2bab76a1b6001e11a refs/remotes/origin/module_version
63acccaf4fd05a141d538d76d37e2b7ec645417f refs/tags/0.9.0
c211d3e493d6d7d7eb2075f31b6993cf80c61e92 refs/tags/v1.1.1
9fd544b45e0361d48d5336bec5da258b96903bd9 refs/tags/v1.2.0
b3c1fc382374c3edfe9e20089c6fbaa1c7c26432 refs/tags/v1.2.1

**Comment by jmcgill298** [comment]
your head shows at #273 which was merged a year ago

**Comment by jmcgill298** [comment]
@feisa I created a new release earlier today that updated the ntc-submodule to the latest release (v1.2.1). I tested running a playbook in offline mode with the data you provided and got a the expected parsed data.

**Comment by feisa** [comment]
@jmcgill298 this works now
