### ISSUE TITLE
cisco_nxos_show_version does not display N5K platform

### ISSUE THREAD

**Issue by martino76** [networktocode/ntc-templates#545]
It seems like show_nxos_version template doe not collect N5K platform. Return date has none for platform.
`{'uptime': '749 day(s), 15 hour(s), 5 minute(s), 8 second(s)', 'last_reboot_reason': 'Disruptive', 'os': '7.1(4)N1(1)', 'boot_image': 'bootflash:///n5000-uk9-kickstart.7.1.4.N1.1.bin', 'platform': ''}`

**Comment by itdependsnetworks** [comment]
Can you provide the actual raw "show version" from this device?

**Comment by martino76** [comment]
sorry please see below raw output
`TAC support: http://www.cisco.com/tac
Documents: http://www.cisco.com/en/US/products/ps9372/tsd_products_support_series_home.html
Copyright (c) 2002-2016, Cisco Systems, Inc. All rights reserved.
The copyrights to certain works contained herein are owned by
other third parties and are used and distributed under license.
Some parts of this software are covered under the GNU Public
License. A copy of the license is available at
http://www.gnu.org/licenses/gpl.html.

Software
  BIOS:      version 3.6.0
  Power Sequencer Firmware: 
             Module 1: v7.0
             Module 1: v1.0
             Module 2: v1.0
             Module 3: v1.0
  Microcontroller Firmware:        version v1.0.0.2
  QSFP Microcontroller Firmware:   
             Module not detected
  CXP Microcontroller Firmware:   
             Module not detected
  kickstart: version 7.1(4)N1(1)
  system:    version 7.1(4)N1(1)
  BIOS compile time:       05/09/2012
  kickstart image file is: bootflash:///n5000-uk9-kickstart.7.1.4.N1.1.bin
  kickstart compile time:  9/2/2016 10:00:00 [09/02/2016 19:37:35]
  system image file is:    bootflash:///n5000-uk9.7.1.4.N1.1.bin
  system compile time:     9/2/2016 10:00:00 [09/02/2016 21:16:21]


Hardware
  cisco Nexus 5596 Chassis ("O2 48X10GE/Modular Supervisor")
  Intel(R) Xeon(R) CPU         with 8253848 kB of memory.
  Processor Board ID FOC17153X08

  Device name: IEDP02-N5K-SW01
  bootflash:    2007040 kB

Kernel uptime is 749 day(s), 15 hour(s), 17 minute(s), 48 second(s)

Last reset at 958444 usecs after  Wed Nov  1 21:20:35 2017

  Reason: Disruptive upgrade
  System version: 7.0(7)N1(1)
  Service: 

plugin
  Core Plugin, Ethernet Plugin, Fc Plugin`

**Comment by martino76** [comment]
I added following to the template ^\s+cisco\s+Nexus\s+${PLATFORM}\s+[cC]hassis and is working now

**Comment by itdependsnetworks** [comment]
Can you edit the field and put it into proper triple backticks? I am concerned your solution will trip up other working use cases.
