### ISSUE TITLE
cisco_asa_show_failover_state

### ISSUE THREAD

**Issue by danielgurau** [networktocode/ntc-templates#546]
##### ISSUE TYPE

 - Template Creation Help

##### TEMPLATE USING
New template to be added for asa show failover state

##### SAMPLE COMMAND OUTPUT
```
               State          Last Failure Reason      Date/Time
This host  -   Secondary
               Active         None
Other host -   Primary
               Standby Ready  Ifc Failure              16:01:23 UTC Nov 5 2019
                              il2-admin admin: Failed

====Configuration State===
        Sync Done - STANDBY
====Communication State===
        Mac set
```

##### SUMMARY
The show failover command produces errors for different modules that are available and this will be an easier way to get details for role, state, mate_state

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by danielgurau** [comment]
State          Last Failure Reason      Date/Time
This host  -   Secondary
               Active         None
Other host -   Primary
               Standby Ready  Ifc Failure              16:01:23 UTC Nov 5 2019
                              il2-admin skyscape_admin: Failed

====Configuration State===
        Sync Done - STANDBY
====Communication State===
        Mac set

**Comment by FragmentedPacket** [comment]
@danielgurau Do you have anything started for this new template?

**Comment by FragmentedPacket** [comment]
I'm going to close this issue as no information has been provided, but if you're stuck somewhere, please re-open and update or join our Slack workspace for help.
