### ISSUE TITLE
nxos show lldp neighbors failing when there is hostname is long

### ISSUE THREAD

**Issue by sjtarik** [networktocode/ntc-templates#58]
When hostname is long, lldp record becomes two lines as follows:

```
us-ny13-dist.corp.acme.com
                     Eth1/8          120        BR          Ethernet1/47  
```

**Comment by GGabriele** [comment]
Hi @sjtarik , I've just updated the template via #61 . It will fix this problem.

**Comment by sjtarik** [comment]
@GGabriele Still there is an issue. I think when you hit a single word line (like a long host name), you should record whatever value you have and continue parsing with the current line. Below is working:

Value NEIGHBOR (\S+)
Value LOCAL_INTERFACE (\S+)
Value NEIGHBOR_INTERFACE (\S+)

Start
  ^Device.*ID -> LLDP

LLDP
  ^${NEIGHBOR}\s+${LOCAL_INTERFACE}\s+\d+\s+[\w+\s]+\S+\s+${NEIGHBOR_INTERFACE}$$ -> Record
  ^\S+$$ -> Continue.Record
  ^${NEIGHBOR}$$
  ^\s+${LOCAL_INTERFACE}\s+\d+\s+[\w+\s]+\S+\s+${NEIGHBOR_INTERFACE}$$ -> Record

**Comment by GGabriele** [comment]
Hi @sjtarik ,
using your template I have this result:
```
FSM Template:
Value NEIGHBOR (\S+)
Value LOCAL_INTERFACE (\S+)
Value NEIGHBOR_INTERFACE (\S+)

Start
  ^Device.*ID -> LLDP

LLDP
  ^${NEIGHBOR}\s+${LOCAL_INTERFACE}\s+\d+\s+[\w+\s]+\S+\s+${NEIGHBOR_INTERFACE}$$ -> Record
  ^\S+$$ -> Continue.Record
  ^${NEIGHBOR}$$
  ^\s+${LOCAL_INTERFACE}\s+\d+\s+[\w+\s]+\S+\s+${NEIGHBOR_INTERFACE}$$ -> Record


FSM Table:
['NEIGHBOR', 'LOCAL_INTERFACE', 'NEIGHBOR_INTERFACE']
['PERIMETER.cisco.com', 'mgmt0', 'Fa1/0/10']
['n9k1.cisconxapi.com', 'Eth1/1', 'Ethernet1/1']
['n9k1.cisconxapi.com', 'Eth1/2', 'Ethernet1/2']
['n9k1.cisconxapi.com', 'Eth1/2', 'Ethernet1/3']
['neighbor.with.long.hostname.n9k2.cisconxapi.com', '', '']
```

While using the current template the result is this, which seems to be correct:
```
FSM Template:
Value NEIGHBOR (\S+(\.\S+)+)
Value LOCAL_INTERFACE (\S+)
Value NEIGHBOR_INTERFACE (\S+)

Start
  ^Device.*ID -> LLDP

LLDP
  ^${NEIGHBOR}\s+${LOCAL_INTERFACE}\s+\d+\s+[\w+\s]+\S+\s+${NEIGHBOR_INTERFACE} -> Record
  ^${NEIGHBOR}
  ^\s+${LOCAL_INTERFACE}\s+\d+\s+[\w+\s]+\S+\s+${NEIGHBOR_INTERFACE} -> Record


FSM Table:
['NEIGHBOR', 'LOCAL_INTERFACE', 'NEIGHBOR_INTERFACE']
['PERIMETER.cisco.com', 'mgmt0', 'Fa1/0/10']
['n9k1.cisconxapi.com', 'Eth1/1', 'Ethernet1/1']
['n9k1.cisconxapi.com', 'Eth1/2', 'Ethernet1/2']
['n9k1.cisconxapi.com', 'Eth1/2', 'Ethernet1/3']
['neighbor.with.long.hostname.n9k2.cisconxapi.com', 'Eth1/21', 'Te5/1']
```

**Comment by sjtarik** [comment]
Hi @GGabriele, have you applied the patch or simply modified the template for the test? It should work since it passed the commit checks on Travis CI (parsed and raw data comparison). If you add a few more lines after a long host name line, it will be better test case to show why this patch is necessary.

**Comment by GGabriele** [comment]
This is just a test with native TextFSM, not with `ntc-ansible`...can you please try to run `py.test` on the main folder? It'd run additional tests not used by Travis CI right now and I see it failing when using your patch.

**Comment by sjtarik** [comment]
After cloning the repo, 

`git clone git@github.com:sjtarik/ntc-templates.git`

I just ran this:

`py.test tests/test_structured_data_against_parsed_reference_files.py`

Results:

(venv) $ py.test tests/test_structured_data_against_parsed_reference_files.py 
============================= test session starts ==============================
platform darwin -- Python 2.7.10, pytest-3.0.5, py-1.4.32, pluggy-0.4.0
rootdir: /Users/sjtarik/Desktop/ntc-templates, inifile: 
collected 364 items 

tests/test_structured_data_against_parsed_reference_files.py ............................................................................................................................................................................................................................................................................................................................................................................

========================== 364 passed in 4.20 seconds ==========================

Am I doing something wrong?

**Comment by GGabriele** [comment]
@sjtarik my bad, I messed it up locally. Tested again and it's good to go. Thanks!
