### ISSUE TITLE
 arista_eos_show_ip_route.textfsm fails on vrrp route display

### ISSUE THREAD

**Issue by centove** [networktocode/ntc-templates#588]
##### ISSUE TYPE
 - Bug Report

##### TEMPLATE USING
Value Filldown VRF (\S+)
Value Filldown PROTOCOL (\S+\s\S+?|\w?)
Value Filldown NETWORK (\d+.\d+.\d+.\d+)
Value Filldown MASK (\d+)
Value DISTANCE (\d+)
Value METRIC (\d+)
Value DIRECT (directly)
Value Required NEXT_HOP (connected|\d+\.\d+\.\d+\.\d+)
Value INTERFACE (\S+)

Start
  ^\s+${PROTOCOL}\s+${NETWORK}/${MASK}\s+(?:\[${DISTANCE}/${METRIC}\]|is\s+${DIRECT})(?:.+?)${NEXT_HOP},\s+${INTERFACE}$$ -> Record
  ^VRF name:\s+${VRF}\s*$$
  ^WARNING:.*
  ^kernel.*
  ^Codes:
  # Match for codes
  ^\s+\S+\s+-\s+\S+
  ^Gateway\s+of\s+last
  ^\s*$$
  ^. -> Error

```

```

##### SAMPLE COMMAND OUTPUT
```
br01.ATL02#sh ip route 74.119.147.148/32

VRF name: default
Codes: C - connected, S - static, K - kernel,
       O - OSPF, IA - OSPF inter area, E1 - OSPF external type 1,
       E2 - OSPF external type 2, N1 - OSPF NSSA external type 1,
       N2 - OSPF NSSA external type2, B I - iBGP, B E - eBGP,
       R - RIP, I L1 - ISIS level 1, I L2 - ISIS level 2,
       O3 - OSPFv3, A B - BGP Aggregate, A O - OSPF Summary,
       NG - Nexthop Group Static Route, V - VXLAN Control Service

 B I    74.119.147.148/32 [200/0] via 199.229.255.31, Vlan70
                                  via 199.229.255.35, Vlan71


```

##### SUMMARY
Not handling the vrrp route output, this happens on alot of the routers I have access to when the route from the border to the distribution can pass to two different distributions before getting to the ultimate end location. 

##### EXPECTED RESULTS

the output should be parsed. I made a few local changes to handle other issues but I'm not sure how to address this.

##### ACTUAL RESULTS
textfsm.TextFSMError: State Error raised. Rule Line: 21. Input Line:                                   via 199.229.255.35, Vlan71

```

```

**Comment by FragmentedPacket** [comment]
Can you test PR #589 ? I used the same format, but maybe you have a command with more routes to test on as well.
