### ISSUE TITLE
Cisco ASA Show interface does not catch unnamed interfaces

### ISSUE THREAD

**Issue by jvanderaa** [networktocode/ntc-templates#627]
##### ISSUE TYPE

 - Bug Report

##### TEMPLATE USING

```
cisco_asa_show_interface
```

##### SUMMARY

When executing the show interface, even though the output has several interfaces, only those with a nameif assigned to them are being returned.

I have the start of a fix, but will also spend time to get the full cleanup done on the template to match what we have in place for newer templates.

**Comment by FragmentedPacket** [comment]
@jvanderaa How's this going?
