### ISSUE TITLE
New template: hp_comware_display_interface_textFSM

### ISSUE THREAD

**Issue by Lasselasse2** [networktocode/ntc-templates#634]

**Comment by FragmentedPacket** [comment]
@Lasselasse2 Do you mind providing more info about this? Raw output would be nice. There is also new templates being added so not sure if one exists for the one you're looking for, but looks to be display_ip_interface

**Comment by FragmentedPacket** [comment]
@Lasselasse2 I will go ahead and close this issue. If you need help please join our Slack or re-open this issue with the requested information.
