### ISSUE TITLE
template request: show ip bgp neighbors x.x.x.x advertised-routes 

### ISSUE THREAD

**Issue by asoltes** [networktocode/ntc-templates#639]
##### ISSUE TYPE

 - Feature Idea

**Comment by FragmentedPacket** [comment]
Do you mind providing more information for this? OS, raw output, etc? This may just need to be updated in an existing template, but not much information to go off of to address it.

**Comment by asoltes** [comment]
![image](https://user-images.githubusercontent.com/52017443/80724842-e1bc5d80-8b34-11ea-92af-6aef3d7a5ff4.png)

Hi @FragmentedPacket something like this. the blue marker is a network address like: 192.168.11.0/24 it was the prefix advertised to your bgp neighbor.  Thanks

**Comment by asoltes** [comment]
Dummy Router#show ip bgp neighbors 172.17.55.13 advertised-routes 
BGP table version is 143173748, local router ID is 192.168.88.2
Status codes: s suppressed, d damped, h history, * valid, > best, i - internal, 
              r RIB-failure, S Stale, m multipath, b backup-path, f RT-Filter, 
              x best-external, a additional-path, c RIB-compressed, 
              t secondary path, 
Origin codes: i - IGP, e - EGP, ? - incomplete
RPKI validation codes: V valid, I invalid, N Not found

     Network          Next Hop            Metric LocPrf Weight Path
 *>   113.55.45.0/24   0.0.0.0                            32768 i
 *>   113.55.48.0/24   0.0.0.0                            32768 i
 *>   113.55.50.0/24   0.0.0.0                            32768 i
 *>   113.55.51.0/24   0.0.0.0                            32768 i
 *>   113.55.53.0/24   0.0.0.0                            32768 i
 *>   113.55.54.0/24   0.0.0.0                            32768 i
 *>   113.55.58.0/24   0.0.0.0                            32768 i

Total number of prefixes 7 
Dummy Router#

**Comment by FragmentedPacket** [comment]
Do you get structured data parsing this with `show_ip_bgp`?

**Comment by asoltes** [comment]
I tried the command show ip bgp but it takes forever to load maybe because of the thousands of routes. i tried the show ip bgp neighbors but i did not get the structured data. see the output below.
![image](https://user-images.githubusercontent.com/52017443/80832069-91b9c580-8c1e-11ea-955c-43aab0b1d36e.png)

**Comment by FragmentedPacket** [comment]
Ok no problem. I'll have to take a look at some point to see what the differences are and whether it's worth another template or adding any use cases that don't already exist in that template.

**Comment by asoltes** [comment]
@FragmentedPacket  Again, Thank you for the efforts and for making all of the templates.

**Comment by FragmentedPacket** [comment]
@asoltes I submitted a new PR for this. So i'll have Jacob review it and if everything looks good we'll merge it.

**Comment by asoltes** [comment]
@FragmentedPacket  I saw that the templates is now merged and I am able to update/download the new template but I am not able to parse the data.
see the image below. I am using nornir and netmiko and I am able to parsed the data in command "show ip int br" 
but when i tested the show ip bgp x.x.xx. neig advertised-routes its not working. Thanks

```
def show_adv_routes(task):
    adv_routes = task.run(netmiko_send_command, command_string="show ip bgp neighbors 172.17.32.165 advertised-routes",use_textfsm=True)
    task.host['adv_routes'] = adv_routes.result
    print_result(adv_routes)

```

![image](https://user-images.githubusercontent.com/52017443/82389175-02117500-9a6e-11ea-964b-ea860753a222.png)


/ntc-templates/templates/cisco_ios_show_ip_bgp_neighbors_advertised_routes.textfsm

**Comment by FragmentedPacket** [comment]
@asoltes I just submitted PR to fix this- #709 . It was the index file that was not correct. Please test though before I merge it in.

**Comment by asoltes** [comment]
@FragmentedPacket woah that was awesome. I am now able to get the parsed data. Thank you, It will help us a lot in automating our network. stay safe and have a good day :) 

![image](https://user-images.githubusercontent.com/52017443/82395146-756eb300-9a7d-11ea-8496-391411ce7f67.png)

**Comment by FragmentedPacket** [comment]
@asoltes I didn't catch that the tests weren't passing. I had to make some changes to the template names and index file as well.

Do you mind testing again and letting me know? I will merge it once tested and be cutting a new release hopefully this week.
