### ISSUE TITLE
Template Creation Help: cisco_xr_admin_show_environment_power to get power supply, voltage and current  

### ISSUE THREAD

**Issue by ansible75013** [networktocode/ntc-templates#648]
##### ISSUE TYPE

 - Bug Report
 - Feature Idea
 - Template Creation Help
 - Documentation Report

##### TEMPLATE USING

```

```

##### SAMPLE COMMAND OUTPUT

```
#admin show environment power
Thu Apr  9 16:54:55.656 FrSummer
R/S/I   Modules         Capacity        Status
                        (W)
0/PS0/M0/*
        host    PM      6000            Ok

0/PS1/M0/*
        host    PM      6000            Ok


R/S/I           Power Supply    Voltage         Current
                (W)             (V)             (A)
0/PS0/M0/*      1339.5          54.9            24.4
0/PS1/M0/*      1305.8          55.1            23.7
--------------
Total:  2645.3

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by FragmentedPacket** [comment]
Have you attempted at making the template and stuck at a certain point?

**Comment by FragmentedPacket** [comment]
@ansible75013 Bump. Any update?

**Comment by FragmentedPacket** [comment]
@ansible75013 I'm going to close this issue as no information has been provided, but if you're stuck somewhere, please re-open and update or join our Slack workspace for help.
