### ISSUE TITLE
cisco_ios_show_mac-address-table.textfsm "N/A" in vlan field.

### ISSUE THREAD

**Issue by delhipnr** [networktocode/ntc-templates#657]
note: macs are set to 0000.0000.0000 due to security reason on production device.

switch>show version
Cisco IOS Software, c6880x Software (c6880x-IPSERVICESK9-M), Version 15.5(1)SY3, RELEASE SOFTWARE (fc5)
switch>show ip vrf
#around 5 vrfs

switch>show mac address-table 

Legend: * - primary entry
        age - seconds since last seen
        n/a - not available
        S - secure entry
        R - router's gateway mac address entry
        D - Duplicate mac address entry
        # - Fabric mac address entry. Clear mac cli doesn't clear this entry

Displaying entries from active supervisor::

      vlan   mac address    type   learn    age                 ports
-----+----+---------------+-------+-----+----------+-----------------------------
         82 0000.0000.0000  dynamic  Yes        0     Te2/5/4
   R   N/A  1005.0000.0000   static   No       -      Router
        216 0000.0000.0000  dynamic  Yes      265     Te1/1/8

++++++++++++++++Code+++++++++++++++++++++++
from ntc_templates.parse import parse_output
from pprint import pprint

indata = """

Legend: * - primary entry
        age - seconds since last seen
        n/a - not available
        S - secure entry
        R - router's gateway mac address entry
        D - Duplicate mac address entry
        # - Fabric mac address entry. Clear mac cli doesn't clear this entry

Displaying entries from active supervisor::

      vlan   mac address    type   learn    age                 ports
-----+----+---------------+-------+-----+----------+-----------------------------
         82 0000.0000.0000  dynamic  Yes        0     Te2/5/4
   R   N/A  1005.0000.0000   static   No       -      Router
        216 0000.0000.0000  dynamic  Yes      265     Te1/1/8
"""
>>> 
 RESTART: C:\Users\userabc\AppData\Local\Programs\Python\Python37-32\dictl.py 
Traceback (most recent call last):
  File "C:\Users\userabc\AppData\Local\Programs\Python\Python37-32\dictl.py", line 23, in <module>
    vlan_parsed = parse_output(platform="cisco_ios", command="show mac address-table", data=indata)
  File "C:\Users\userabc\AppData\Local\Programs\Python\Python37-32\lib\site-packages\ntc_templates\parse.py", line 39, in parse_output
    cli_table.ParseCmd(data, attrs)
  File "C:\Users\userabc\AppData\Local\Programs\Python\Python37-32\lib\site-packages\clitable.py", line 277, in ParseCmd
    self.table = self._ParseCmdItem(self.raw, template_file=template_files[0])
  File "C:\Users\userabc\AppData\Local\Programs\Python\Python37-32\lib\site-packages\clitable.py", line 310, in _ParseCmdItem
    for record in fsm.ParseText(cmd_input):
  File "C:\Users\userabc\AppData\Local\Programs\Python\Python37-32\lib\site-packages\textfsm.py", line 885, in ParseText
    self._CheckLine(line)
  File "C:\Users\userabc\AppData\Local\Programs\Python\Python37-32\lib\site-packages\textfsm.py", line 908, in _CheckLine
    if self._Operations(rule, line):
  File "C:\Users\userabc\AppData\Local\Programs\Python\Python37-32\lib\site-packages\textfsm.py", line 989, in _Operations
    % (rule.line_num, line))
textfsm.TextFSMError: State Error raised. Rule Line: 32. Input Line:    R   N/A  1005.0000.0000   static   No       -      Router

**Comment by FragmentedPacket** [comment]
Can you do similar for this one as well? Provide the actual output from the device and wrap in triple backticks?

**Comment by delhipnr** [comment]
> Can you do similar for this one as well? Provide the actual output from the device and wrap in triple backticks?

from ntc_templates.parse import parse_output
from pprint import pprint

indata = """

Legend: * - primary entry
        age - seconds since last seen
        n/a - not available
        S - secure entry
        R - router's gateway mac address entry
        D - Duplicate mac address entry
        # - Fabric mac address entry. Clear mac cli doesn't clear this entry

Displaying entries from active supervisor::

      vlan   mac address    type   learn    age                 ports
-----+----+---------------+-------+-----+----------+-----------------------------
         75 0000.0000.4500  dynamic  Yes        0     Te2/5/4
        402 0000.0000.21de  dynamic  Yes        0     Po4
          3 0000.0000.3800  dynamic  Yes        0     Te2/5/10
         24 0000.0000.0f00  dynamic  Yes      265     Te1/1/9
 *       10 0000.0100.0000  dynamic  Yes        0     Te1/5/13
   R    459 0000.0000.0e00   static   No       -      Router
 *       39 0000.0000.0d00  dynamic  Yes        0     Te1/5/4
        174 0000.0000.ace0  dynamic  Yes      265     Te1/1/11
        361 0000.0000.1bea  dynamic  Yes      265     Po4
        310 0000.0000.e903  dynamic  Yes      105     Te2/1/5
 *      302 0000.0000.0400  dynamic  Yes        0     Te1/5/4
        402 0000.0000.0000  dynamic  Yes      265     Te1/1/10
   R    303 0000.0000.0e00   static   No       -      Router
        141 0000.0000.3e00  dynamic  Yes        0     Te2/1/9
          8 0000.0000.3900  dynamic  Yes        0     Te2/5/3
        111 0000.0000.0f00  dynamic  Yes      265     Te1/1/9
   R     68 0000.0000.0e00   static   No       -      Router
         60 0000.0000.39c9  dynamic  Yes      105     Te2/1/5
          6 0000.0000.a3ea  dynamic  Yes        0     Te2/5/8
        703 0000.0000.4000  dynamic  Yes        0     Te2/1/9
   R     62 0000.0000.0e00   static   No       -      Router
 *       10 0000.0000.1300  dynamic  Yes        0     Te1/5/13
        200 0000.0000.3cc0  dynamic  Yes       20     Te1/1/8
         82 0000.0000.3900  dynamic  Yes        0     Te2/5/4
   R   N/A  0000.0000.0e00   static   No       -      Router
        216 0000.0000.4b10  dynamic  Yes      265     Te1/1/8
        361 0000.0000.7565  dynamic  Yes       50     Po4
        361 0000.0000.0ca6  dynamic  Yes      105     Po4
   R    451 0000.0000.0e00   static   No       -      Router
        401 0000.0000.1fcb  dynamic  Yes        5     Po4
"""

vlan_parsed = parse_output(platform="cisco_ios", command="show mac address-table", data=indata)
pprint(vlan_parsed)

>>> 
 RESTART: C:\Users\a0725645\AppData\Local\Programs\Python\Python37-32\dictl.py 
Traceback (most recent call last):
  File "C:\Users\a0725645\AppData\Local\Programs\Python\Python37-32\dictl.py", line 50, in <module>
    vlan_parsed = parse_output(platform="cisco_ios", command="show mac address-table", data=indata)
  File "C:\Users\a0725645\AppData\Local\Programs\Python\Python37-32\lib\site-packages\ntc_templates\parse.py", line 39, in parse_output
    cli_table.ParseCmd(data, attrs)
  File "C:\Users\a0725645\AppData\Local\Programs\Python\Python37-32\lib\site-packages\clitable.py", line 277, in ParseCmd
    self.table = self._ParseCmdItem(self.raw, template_file=template_files[0])
  File "C:\Users\a0725645\AppData\Local\Programs\Python\Python37-32\lib\site-packages\clitable.py", line 310, in _ParseCmdItem
    for record in fsm.ParseText(cmd_input):
  File "C:\Users\a0725645\AppData\Local\Programs\Python\Python37-32\lib\site-packages\textfsm.py", line 885, in ParseText
    self._CheckLine(line)
  File "C:\Users\a0725645\AppData\Local\Programs\Python\Python37-32\lib\site-packages\textfsm.py", line 908, in _CheckLine
    if self._Operations(rule, line):
  File "C:\Users\a0725645\AppData\Local\Programs\Python\Python37-32\lib\site-packages\textfsm.py", line 989, in _Operations
    % (rule.line_num, line))
textfsm.TextFSMError: State Error raised. Rule Line: 32. Input Line:    R   N/A  0000.0000.0e00   static   No       -      Router
>>>

**Comment by delhipnr** [comment]
> Can you do similar for this one as well? Provide the actual output from the device and wrap in triple backticks?

it also has "R N/A" . Sharing a 2015 post here 
https://community.cisco.com/t5/switching/suspicious-mac-address-entires-and-mac-address-table/td-p/2769966

R N/A 0008.e3ff.fc28 static No - Router
* 2 f4ce.46ba.d47e dynamic Yes 0 Te1/5/7
R N/A 0008.e3ff.fc28 static No - Router
* 2 0008.e0ff.fc28 dynamic Yes 0 Po11
R N/A 0008.e3ff.fc28 static No - Router
R 2 0008.e3ff.fc28 static No - Router

**Comment by FragmentedPacket** [comment]
This should be a pretty simple fix. Could you do me a favor and follow the directions from the following link to wrap the output in a code block? https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks

I can then fix your issue and add a test with that data to make sure we don't break this functionality moving forward.

**Comment by delhipnr** [comment]
> This should be a pretty simple fix. Could you do me a favor and follow the directions from the following link to wrap the output in a code block? https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks
> 
> I can then fix your issue and add a test with that data to make sure we don't break this functionality moving forward.
I am sorry don't use formatting frequently. Here it is and thank you again. 
```
imt_netr_ops-1542774-clt2641->show mac address-table 

Legend: * - primary entry
        age - seconds since last seen
        n/a - not available
        S - secure entry
        R - router's gateway mac address entry
        D - Duplicate mac address entry
        # - Fabric mac address entry. Clear mac cli doesn't clear this entry

Displaying entries from active supervisor::

      vlan   mac address    type   learn    age                 ports
-----+----+---------------+-------+-----+----------+-----------------------------
         75 0000.0000.4500  dynamic  Yes        0     Te2/5/4
        402 0000.0000.21de  dynamic  Yes        0     Po4
          3 0000.0000.3800  dynamic  Yes        0     Te2/5/10
         24 0000.0000.0f00  dynamic  Yes      265     Te1/1/9
 *       10 0000.0100.0000  dynamic  Yes        0     Te1/5/13
   R    459 0000.0000.0e00   static   No       -      Router
 *       39 0000.0000.0d00  dynamic  Yes        0     Te1/5/4
        174 0000.0000.ace0  dynamic  Yes      265     Te1/1/11
        361 0000.0000.1bea  dynamic  Yes      265     Po4
        310 0000.0000.e903  dynamic  Yes      105     Te2/1/5
 *      302 0000.0000.0400  dynamic  Yes        0     Te1/5/4
        402 0000.0000.0000  dynamic  Yes      265     Te1/1/10
   R    303 0000.0000.0e00   static   No       -      Router
        141 0000.0000.3e00  dynamic  Yes        0     Te2/1/9
          8 0000.0000.3900  dynamic  Yes        0     Te2/5/3
        111 0000.0000.0f00  dynamic  Yes      265     Te1/1/9
   R     68 0000.0000.0e00   static   No       -      Router
         60 0000.0000.39c9  dynamic  Yes      105     Te2/1/5
          6 0000.0000.a3ea  dynamic  Yes        0     Te2/5/8
        703 0000.0000.4000  dynamic  Yes        0     Te2/1/9
   R     62 0000.0000.0e00   static   No       -      Router
 *       10 0000.0000.1300  dynamic  Yes        0     Te1/5/13
        200 0000.0000.3cc0  dynamic  Yes       20     Te1/1/8
         82 0000.0000.3900  dynamic  Yes        0     Te2/5/4
   R   N/A  0000.0000.0e00   static   No       -      Router
        216 0000.0000.4b10  dynamic  Yes      265     Te1/1/8
        361 0000.0000.7565  dynamic  Yes       50     Po4
        361 0000.0000.0ca6  dynamic  Yes      105     Po4
   R    451 0000.0000.0e00   static   No       -      Router
        401 0000.0000.1fcb  dynamic  Yes        5     Po4
```

**Comment by FragmentedPacket** [comment]
Thank you! I will try and get a fix for this submitted within the next day or two.
