### ISSUE TITLE
Problem to add or install ntc-templates:

### ISSUE THREAD

**Issue by raikone14** [networktocode/ntc-templates#658]
I installed the ntc-templates with git clone into my project folder, but didnt work.
[https://ibb.co/K9wm1Ys](url)
but still ask me to install...
I also tried to add the variable:
[https://ibb.co/bgWP55g](url)

but still the same error, thanks for any help.

**Comment by FragmentedPacket** [comment]
Do you mind providing more information?

What project are you attempting to use and what tool is saying ntc-templates is not installed?

**Comment by raikone14** [comment]
> Do you mind providing more information?
> 
> What project are you attempting to use and what tool is saying ntc-templates is not installed?

Hey thanks for repply and sorry for the lack of information.
I am using pycharm as IDE and doinf a simple project with netmiko to get some info from a cisco ios device.
First I tried to install via pycharm , just select into my project.
After I tried to do a git clone from my project folder, as you can see in the pic I have  the ntc templates into my project folder, but also didnt work.
And I also tried to add the variable but this one I am not sure if I did right.. tks a lot

**Comment by jmcgill298** [comment]
have you tried using `pip install ntc-templates`?

**Comment by itdependsnetworks** [comment]
Gone stale, if there is still an issue, feel free to reopen ticket.
