### ISSUE TITLE
Ciena naming doesn’t conform to Netmiko

### ISSUE THREAD

**Issue by georgesnow** [networktocode/ntc-templates#662]
In testing with Nornir/Netmiko using textfsm against ciena network devices they fail. If you rename them to conform they will work with Netmiko. I discovered this while working on some additional templates. I have adjusted the names in my fork for when I put in merge request.

from:

ciena_6x

To:

ciena_saos

**Comment by smk4664** [comment]
I believe Netmiko is right here, the os is saos, 6x is the version number.

**Comment by georgesnow** [comment]
as reference

https://github.com/ktbyers/netmiko/tree/master/netmiko/ciena
