### ISSUE TITLE
cisco_ios neighbor summary per address family new request.

### ISSUE THREAD

**Issue by delhipnr** [networktocode/ntc-templates#664]
In continuation to #663 request you to also check feasibilities to get the neighbor table per address family.  Like unicast, multicast, and VPNV4. as of now "show ip bgp summary" is working like anything but it is limited to unicast family. I am sharing below per family command output with you for reference.

```
R1#show ip bgp all summary
For address family: IPv4 Unicast
BGP router identifier 1.1.1.1, local AS number 65000
BGP table version is 9, main routing table version 9
8 network entries using 1152 bytes of memory
9 path entries using 720 bytes of memory
2/2 BGP path/bestpath attribute entries using 272 bytes of memory
1 BGP AS-PATH entries using 24 bytes of memory
2 BGP extended community entries using 48 bytes of memory
0 BGP route-map cache entries using 0 bytes of memory
0 BGP filter-list cache entries using 0 bytes of memory
BGP using 2216 total bytes of memory
BGP activity 24/0 prefixes, 25/0 paths, scan interval 60 secs

Neighbor        V           AS MsgRcvd MsgSent   TblVer  InQ OutQ Up/Down  State/PfxRcd
10.0.14.4       4        65001      26      27        9    0    0 00:20:06        7

For address family: VPNv4 Unicast
BGP router identifier 1.1.1.1, local AS number 65000
BGP table version is 17, main routing table version 17
16 network entries using 2496 bytes of memory
16 path entries using 1280 bytes of memory
4/3 BGP path/bestpath attribute entries using 576 bytes of memory
1 BGP AS-PATH entries using 24 bytes of memory
2 BGP extended community entries using 48 bytes of memory
0 BGP route-map cache entries using 0 bytes of memory
0 BGP filter-list cache entries using 0 bytes of memory
BGP using 4424 total bytes of memory
BGP activity 24/0 prefixes, 25/0 paths, scan interval 60 secs

Neighbor        V           AS MsgRcvd MsgSent   TblVer  InQ OutQ Up/Down  State/PfxRcd
10.10.13.3      4        65001      48      48       17    0    0 00:40:00        5
10.10.14.4      4        65001       0       0        1    0    0 never    Idle

For address family: VPNv4 Multicast


For address family: MVPNv4 Unicast


```

And this is what we have for now working. but limited to unicast default table.

```
R1#show ip bgp summary
BGP router identifier 1.1.1.1, local AS number 65000
BGP table version is 9, main routing table version 9
8 network entries using 1152 bytes of memory
9 path entries using 720 bytes of memory
2/2 BGP path/bestpath attribute entries using 272 bytes of memory
1 BGP AS-PATH entries using 24 bytes of memory
2 BGP extended community entries using 48 bytes of memory
0 BGP route-map cache entries using 0 bytes of memory
0 BGP filter-list cache entries using 0 bytes of memory
BGP using 2216 total bytes of memory
BGP activity 24/0 prefixes, 25/0 paths, scan interval 60 secs

Neighbor        V           AS MsgRcvd MsgSent   TblVer  InQ OutQ Up/Down  State/PfxRcd
10.0.14.4       4        65001      33      35        9    0    0 00:26:48        7
R1#

```

Thank You.

**Comment by FragmentedPacket** [comment]
@delhipnr I'm just going to echo my same sentiment on #663 . I'd suggest you take a stab at this and learn some about building/adding to a TextFSM template.

We're available to help in our [public NTC Slack](https://slack.networktocode.com) in the #networktocode channel.

**Comment by delhipnr** [comment]
> @delhipnr I'm just going to echo my same sentiment on #663 . I'd suggest you take a stab at this and learn some about building/adding to a TextFSM template.
> 
> We're available to help in our [public NTC Slack](https://slack.networktocode.com) in the #networktocode channel.

I am very aggressive to learn the ntc template quickly like anything. I am familiar with python regex.

I am unable to open your link
![Screenshot_2020-04-29-01-28-07-99](https://user-images.githubusercontent.com/6277677/80531879-ec51e800-89b8-11ea-8476-c72f4662d00a.png)

**Comment by FragmentedPacket** [comment]
Try again. I believe the site falls asleep until it gets hit once or twice.

**Comment by delhipnr** [comment]
networktocode.com is working but slack.networktocode.com is not.

Might be a suburl is not working in the site, can you please check?

**Comment by FragmentedPacket** [comment]
@delhipnr I'm not sure why it's not working for you. Maybe try on mobile data or if you have browser extensions?

**Comment by FragmentedPacket** [comment]
@delhipnr I submitted a PR for this so if you want to let me know if it is what you're looking for.
