### ISSUE TITLE
Arista eos - sh ip bgp summ vrf all and sh ip route vrf all template

### ISSUE THREAD

**Issue by hett39** [networktocode/ntc-templates#666]
Hi , need Arista eos - sh ip bgp summ vrf all and sh ip route vrf all templates

 - Feature Idea

**Comment by FragmentedPacket** [comment]
@hett39 We typically don't have the time to build templates for everyone and suggest that you take a stab at it and learn some TextFSM. We're available to help and typically have more time to do so.

I believe you're already in our NTC Slack so I'd definitely suggest taking a shot at building the templates and then asking for help in #networktocode.

**Comment by FragmentedPacket** [comment]
I'm going to close this, but if you're stuck at a certain point and need help, you can re-open with relevant details (template and raw output).

We're also available on our Slack community in the #networktocode channel for live assistance.
