### ISSUE TITLE
Arista EOS show ip route parse error

### ISSUE THREAD

**Issue by centove** [networktocode/ntc-templates#668]
- Bug Report
##### TEMPLATE USING
templates/arista_eos_show_ip_route.textfsm 
Value Filldown VRF (\S+)
Value Filldown PROTOCOL (\S+\s\S+?|\w?)
Value Filldown NETWORK (\d+.\d+.\d+.\d+)
Value Filldown MASK (\d+)
Value Filldown DISTANCE (\d+)
Value Filldown METRIC (\d+)
Value DIRECT (directly)
Value Required NEXT_HOP (connected|\d+\.\d+\.\d+\.\d+)
Value INTERFACE (\S+)

Start
  ^\s+${PROTOCOL}\s+${NETWORK}/${MASK}\s+(?:\[${DISTANCE}/${METRIC}\]|is\s+${DIRECT})(?:.+?)${NEXT_HOP},\s+${INTERFACE}$$ -> Record
  ^\s+via\s+${NEXT_HOP},\s+${INTERFACE}
  ^VRF\s+name:\s+${VRF}\s*$$
  ^VRF:\s+${VRF}\s*$$
  ^Codes:
  # Match for codes
  ^\s+\S+\s+-\s+\S+
  ^Gateway\s+of\s+last
  ^\s*$$
  ^. -> Error

```

##### SAMPLE COMMAND OUTPUT
Encountered a non setup/teardown error State Error raised. Rule Line: 21. Input Line: WARNING: Some of the routes are not programmed in     


##### SUMMARY
Arista throws a couple of extra lines in if your device has a lot of routs that can't be programmed into the hardware, see below, the template should ignore those lines when they appear.
##### STEPS TO REPRODUCE

VRF name: default
WARNING: Some of the routes are not programmed in     
kernel, and they are marked with '%'.                 
Codes: C - connected, S - static, K - kernel, 
       O - OSPF, IA - OSPF inter area, E1 - OSPF external type 1,
       E2 - OSPF external type 2, N1 - OSPF NSSA external type 1,
       N2 - OSPF NSSA external type2, B I - iBGP, B E - eBGP,
       R - RIP, I L1 - ISIS level 1, I L2 - ISIS level 2,
       O3 - OSPFv3, A B - BGP Aggregate, A O - OSPF Summary,
       NG - Nexthop Group Static Route, V - VXLAN Control Service

Gateway of last resort:
 O E1   0.0.0.0/0 [110/21] via 172.83.43.48, Vlan55
                           via 172.83.43.50, Vlan65

 S      10.1.26.0/24 [1/0] via 142.54.229.92, Vlan2503
[...]

**Comment by FragmentedPacket** [comment]
@centove I believe I have it fixed in the PR attached to this. Can you pull it down and test?
