### ISSUE TITLE
cisco_ios "show ip ospf database router" fails if OSPF domain includes an ASBR or an ABR

### ISSUE THREAD

**Issue by ariesgeek** [networktocode/ntc-templates#690]
##### ISSUE TYPE

 - Bug Report

##### TEMPLATE USING

NTC template `cisco_ios_show_ip_ospf_database_router.textfsm`

```
Value Filldown ROUTER_ID (\d+\.\d+\.\d+\.\d+)
Value Filldown PROCESS_ID (\d+)
Value Filldown AREA (\d+\.\d+\.\d+\.\d+|\d+)
Value Filldown LSA_AGE (\d+)
Value Filldown LSA_OPTIONS (.+)
Value Filldown LSA_TYPE (.+)
Value Filldown LSA_ID (\d+\.\d+\.\d+\.\d+)
Value Filldown LSA_ADV_ROUTER (\d+\.\d+\.\d+\.\d+)
Value Filldown LSA_SEQ_NUMBER (\S+)
Value Filldown LSA_CHECKSUM (\S+)
Value Filldown LSA_LENGTH (\d+)
Value Filldown LSA_NUM_LINKS (\d+)
Value LS_LINK_TYPE (.+?)
Value LS_LINK_ID (\d+\.\d+\.\d+\.\d+)
Value LS_LINK_DATA (\d+\.\d+\.\d+\.\d+)
Value LS_MTID_METRICS (\d+)
Value LS_TOS_0_METRICS (\d+)

Start
  ^\s*OSPF\s+Router\s+with\s+ID\s+\(${ROUTER_ID}\)\s+\(Process\s+ID\s+${PROCESS_ID}\)
  ^\s+Router\s+Link\s+States\s+\(Area ${AREA}\) -> LSAInfo
  ^\s*$$
  ^. -> Error

LSAInfo
  ^\s+LS\s+age:\s+${LSA_AGE}
  ^\s+Options:\s+\(${LSA_OPTIONS}\)
  ^\s+LS\s+Type:\s+${LSA_TYPE}
  ^\s+Link\s+State\s+ID:\s+${LSA_ID}
  ^\s+Advertising\s+Router:\s+${LSA_ADV_ROUTER}
  ^\s+LS\s+Seq\s+Number:\s+${LSA_SEQ_NUMBER}
  ^\s+Checksum:\s+${LSA_CHECKSUM}
  ^\s+Length:\s+${LSA_LENGTH}
  ^\s+Number\s+of\s+Links:\s+${LSA_NUM_LINKS} -> LSAs
  ^\s*$$
  ^. -> Error

LSAs
  ^\s+Link\s+connected\s+to:\s+${LS_LINK_TYPE}$$
  ^\s+\(Link ID\)\s+((Network\/subnet\s+number)|(Designated\s+Router\s+address)|(Neighboring\s+Router ID)):\s+${LS_LINK_ID}
  ^\s+\(Link Data\)\s+((Network\s+Mask)|(Router\s+Interface\s+address)):\s+${LS_LINK_DATA}
  ^\s+Number\s+of\s+MTID\s+metrics:\s+${LS_MTID_METRICS}
  ^\s+TOS\s+0\s+Metrics:\s+${LS_TOS_0_METRICS} -> Next.Record
  ^\s+LS\s+age:\s+${LSA_AGE} -> LSAInfo
  ^\s*$$
  ^. -> Error

EOF
```

##### SAMPLE COMMAND OUTPUT

Sample 1:  Single-area OSPF domain with an Autonomous System Boundary Router.

```
OSPF Router with ID (10.0.0.1) (Process ID 1)

                Router Link States (Area 0)

  LS age: 11
  Options: (No TOS-capability, DC)
  LS Type: Router Links
  Link State ID: 10.0.0.1
  Advertising Router: 10.0.0.1
  LS Seq Number: 80000005
  Checksum: 0x5CAE
  Length: 36
  AS Boundary Router
  Number of Links: 1

    Link connected to: a Stub Network
     (Link ID) Network/subnet number: 10.0.0.1
     (Link Data) Network Mask: 255.255.255.255
      Number of MTID metrics: 0
       TOS 0 Metrics: 1


```

Sample 2:  Multi-area OSPF domain with an Area Border Router.

```
OSPF Router with ID (10.0.0.1) (Process ID 1)

                Router Link States (Area 0)

  LS age: 4
  Options: (No TOS-capability, DC)
  LS Type: Router Links
  Link State ID: 10.0.0.1
  Advertising Router: 10.0.0.1
  LS Seq Number: 80000006
  Checksum: 0x5DAB
  Length: 36
  Area Border Router
  AS Boundary Router
  Number of Links: 1

    Link connected to: a Stub Network
     (Link ID) Network/subnet number: 10.0.0.1
     (Link Data) Network Mask: 255.255.255.255
      Number of MTID metrics: 0
       TOS 0 Metrics: 1



                Router Link States (Area 1)

  LS age: 4
  Options: (No TOS-capability, DC)
  LS Type: Router Links
  Link State ID: 10.0.0.1
  Advertising Router: 10.0.0.1
  LS Seq Number: 80000002
  Checksum: 0x7694
  Length: 36
  Area Border Router
  AS Boundary Router
  Number of Links: 1

    Link connected to: a Stub Network
     (Link ID) Network/subnet number: 10.1.1.1
     (Link Data) Network Mask: 255.255.255.255
      Number of MTID metrics: 0
       TOS 0 Metrics: 1


```

##### SUMMARY

The current template does not account for the appearance of `AS Boundary Router` or `Area Border Router` in the LSA header output.

If there is at least one router in the OSPF domain that is redistributing external routes into OSPF, including a default route, then the output of the `show ip ospf database router` command will always include at least one occurrence of `AS Boundary Router`.

Similarly, in a multi-area OSPF domain, the output of the `show ip ospf database router` command will always include at least one occurrence of `Area Border Router`.

In attempting to resolve these issues, I found that the OSPF area ID is only captured in the `Start` state, which is also the trigger to move to the `LSAInfo` state.  As there are no triggers to return to the `Start` state, the current template is unable to support a multi-area environment overall.

I have successfully resolved all of the above problems and created appropriate tests, and will submit a pull request, but wanted to make sure to document first.  If it's better that I close this issue and separate it into two or more separate issues, that is fine, just let me know.

##### STEPS TO REPRODUCE

Configure redistribution into OSPF to make the router an Autonomous System Boundary Router, which will produce the output shown in Sample 1 above.

```
router ospf 1
 redistribute static subnets
end
```

Alternatively, or additionally, configure an interface in a non-backbone area, thus creating a mult-area OSPF domain, which will product the output shown in Sample 2 above.

```
interface Loopback1
 ip address 10.1.1.1 255.255.255.255
 ip ospf 1 area 1
end
```

Use Netmiko with TextFSM to get the output of `show ip ospf database router`.

```python
import netmiko

deviceDict = {
    "host": "10.0.0.1",
    "username": "cisco",
    "password": "cisco",
    "device_type": "cisco_ios",
}
connection = netmiko.ConnectHandler(**deviceDict)
db = connection.send_command("show ip ospf database router", use_textfsm=True)
```

##### EXPECTED RESULTS

I would expect the command to parse without error, as it does on a non-ABR / non-ASBR router.

##### ACTUAL RESULTS

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/me/.venv/lib64/python3.6/site-packages/netmiko/utilities.py", line 347, in wrapper_decorator
    return func(self, *args, **kwargs)
  File "/home/me/.venv/lib64/python3.6/site-packages/netmiko/base_connection.py", line 1447, in send_command
    template=textfsm_template,
  File "/home/me/.venv/lib64/python3.6/site-packages/netmiko/utilities.py", line 280, in get_structured_data
    return _textfsm_parse(textfsm_obj, raw_output, attrs)
  File "/home/me/.venv/lib64/python3.6/site-packages/netmiko/utilities.py", line 252, in _textfsm_parse
    textfsm_obj.ParseCmd(raw_output, attrs)
  File "/home/me/.venv/lib64/python3.6/site-packages/netmiko/_textfsm/_clitable.py", line 272, in ParseCmd
    self.table = self._ParseCmdItem(self.raw, template_file=template_files[0])
  File "/home/me/.venv/lib64/python3.6/site-packages/netmiko/_textfsm/_clitable.py", line 303, in _ParseCmdItem
    for record in fsm.ParseText(cmd_input):
  File "/home/me/.venv/lib64/python3.6/site-packages/textfsm/parser.py", line 895, in ParseText
    self._CheckLine(line)
  File "/home/me/.venv/lib64/python3.6/site-packages/textfsm/parser.py", line 944, in _CheckLine
    if self._Operations(rule, line):
  File "/home/me/.venv/lib64/python3.6/site-packages/textfsm/parser.py", line 1025, in _Operations
    % (rule.line_num, line))
textfsm.parser.TextFSMError: State Error raised. Rule Line: 36. Input Line:  AS Boundary Router
```

If a router LSA that was originateed by an ABR is encountered first, the last line of the resulting error message will reflect this:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/me/.venv/lib64/python3.6/site-packages/netmiko/utilities.py", line 347, in wrapper_decorator
    return func(self, *args, **kwargs)
  File "/home/me/.venv/lib64/python3.6/site-packages/netmiko/base_connection.py", line 1447, in send_command
    template=textfsm_template,
  File "/home/me/.venv/lib64/python3.6/site-packages/netmiko/utilities.py", line 280, in get_structured_data
    return _textfsm_parse(textfsm_obj, raw_output, attrs)
  File "/home/me/.venv/lib64/python3.6/site-packages/netmiko/utilities.py", line 252, in _textfsm_parse
    textfsm_obj.ParseCmd(raw_output, attrs)
  File "/home/me/.venv/lib64/python3.6/site-packages/netmiko/_textfsm/_clitable.py", line 272, in ParseCmd
    self.table = self._ParseCmdItem(self.raw, template_file=template_files[0])
  File "/home/me/.venv/lib64/python3.6/site-packages/netmiko/_textfsm/_clitable.py", line 303, in _ParseCmdItem
    for record in fsm.ParseText(cmd_input):
  File "/home/me/.venv/lib64/python3.6/site-packages/textfsm/parser.py", line 895, in ParseText
    self._CheckLine(line)
  File "/home/me/.venv/lib64/python3.6/site-packages/textfsm/parser.py", line 944, in _CheckLine
    if self._Operations(rule, line):
  File "/home/me/.venv/lib64/python3.6/site-packages/textfsm/parser.py", line 1025, in _Operations
    % (rule.line_num, line))
textfsm.parser.TextFSMError: State Error raised. Rule Line: 36. Input Line:   Area Border Router
```

**Comment by FragmentedPacket** [comment]
@ariesgeek Do you mind testing the attached PR to let me know if this solves your issue?

**Comment by ariesgeek** [comment]
Technically, it fixes the error and it does permit the existence of an ABR and an ASBR.  It also captures the OSPF area if it has changed.  However, there's some key output missing.  In technical terms, router-LSA Bit E ("AS Boundary Router") and Bit B ("Area Border Router") are not included in the TextFSM output, despite being provided in the output of the IOS command.  I point out the technical terms only because [it's important information](https://tools.ietf.org/html/rfc2328#page-206).

Somewhat of a purist, I may have [gone a bit overboard](https://github.com/ariesgeek/ntc-templates/pull/1), but I ended up capturing two new Values:

```
Value LSA_ABR (Area\sBorder\sRouter)
Value LSA_ASBR (AS\sBoundary\sRouter)
```

...that I then captured with the LSA header information:

```
  ^\s+${LSA_ABR}$$
  ^\s+${LSA_ASBR}$$
```

When you look at the FSM as written in the existing template, you'll see how this became problematic quickly.  If I followed suit and used a `Filldown`, once an ABR was encountered, for example, then _every_ link showed as an ABR.  Otherwise, only the first link inside an LSA would indicate the ABR status.

The crux of the problem is that, as written, every _link_ is a row.  The purpose of the command is to display all of the router _LSAs_, each of which will contain information on one or more _links_.

Ultimately, to accomplish this, I had to pretty much rework the FSM within the existing template to some extent such that each row is an LSA, and the links contained in the LSAs are lists.

Sorry.  I'm not really known for giving succinct answers.

Maybe merge #691 so that we're at least getting around the error, and I can submit a separate issue and PR if you'd like, that will refine the template a bit so that we get the above detail in the output?

**Comment by FragmentedPacket** [comment]
I can definitely get those new values added and capture the output rather than just accounting for it.

As for the other changes, it follows our current flow on a lot of the existing templates using the fill down. I will capture those with the same values you have and then merge it.
