### ISSUE TITLE
Having trouble with alcatel_sros templates 

### ISSUE THREAD

**Issue by kerwbstomp** [networktocode/ntc-templates#698]
##### ISSUE TYPE

 - Template Creation Help

##### TEMPLATE USING

```
Value PORT (\S+)
Value DESCRIPTION (.*?)

Start
  ^\s*Port\sId\s+"${PORT}", Description "${DESCRIPTION}" -> Record
```

##### SAMPLE COMMAND OUTPUT

```
show port description

```

##### SUMMARY

It's probably just me being terrible. However:
I tried my stab at creating an alcatel_sros template (nokia_sros) in netmiko. It doesn't seem to catch anything. The format for the files are alcatel_sros_show_port_description.textfsm/raw/yaml in the correct directories as mentioned in your readme.md. It seems that alcatel_sros_show_service_id_base.textfsm also just gives string data, although the command does call for an 'id' number between id and base. i.e show service id 1234 base. Is this something wrong with my Text-FSM template? I was able to edit an existing juniper_junos template just fine. 

##### STEPS TO REPRODUCE

```
import json
from netmiko import Netmiko
from netmiko import ConnectHandler

my_device = {
    "host": "10.6.6.155",
    "username": "username",
    "password": "password",
    "device_type": "alcatel_sros",
}

net_connect = Netmiko(**my_device)
# Requires ntc-templates to be installed in ~/ntc-templates/templates
output = net_connect.send_command("show port description", use_textfsm=True)

#json_output = (json.dumps(output, indent=2))

#data = json_output
print(output)

```

##### EXPECTED RESULTS

Data to be parsed and returned with Port ID and Description

##### ACTUAL RESULTS

Only a long string of Data was returned 

```
(venv) user@ip:~/netbox-interface-importer$ python3.8 test_textfsm.py 
===============================================================================
Port Descriptions on Slot 1
===============================================================================
Port Id        Description
-------------------------------------------------------------------------------
1/1/1          test link
1/1/2          10/100/Gig Ethernet SFP
1/1/3          LAG-1
1/1/4          LAG-2
1/1/5          LAG-2
1/1/6          10/100/Gig Ethernet SFP
1/1/7          10/100/Gig Ethernet TX
1/1/8          10/100/Gig Ethernet TX
1/1/9          LAG-1
1/1/10        Test Link 2
=================================
```

**Comment by itdependsnetworks** [comment]
likely something like: ```Value PORT (\S+)
Value DESCRIPTION (.*?)

Start
  ^=+$$
  ^-+$$
  ^Port\s+Descriptions\s+on\s+Slot\s+1
  ^Port\s+Id\s+Description
  ^${PORT}\s+${DESCRIPTION}$$ -> Record```

I would join the slack channel (as per readme) if further clarification is needed.
