### ISSUE TITLE
Creation of a Faq

### ISSUE THREAD

**Issue by itdependsnetworks** [networktocode/ntc-templates#716]
##### ISSUE TYPE

 - Documentation Report

##### SUMMARY

There is currently some misunderstood aspects to the library, suggesting to build a FAQ, can think of the following:
* Why require the `Error` at the end of each line?
* Why is the impact of being a parsing engine, and not a data modeling engine? 
  * Post processing is implied
  * Keys between vendors do not always match up
* Why is the index ordered the way it is?
* Does this work on Windows?

I am sure there are many others.

**Comment by Yakuza-UA** [comment]
Great idea.
If there was a detailed FAQ, it would save me a lot of time and would help to avoid unnecessary commits and re-work. I nearly gave up by now.

By the way, I am sure you wanted to say

- Why require the Error at the end of **each section**?

**Comment by FragmentedPacket** [comment]
@Yakuza-UA Since you just went through a lengthy process with submitting several templates, do you mind providing a bit of feedback as to what would've helped simplify the process that we can include in the FAQ?
