### ISSUE TITLE
Issues with trying to use the test-template playbook

### ISSUE THREAD

**Issue by bdowling** [networktocode/ntc-templates#73]
##### ISSUE TYPE

 - Bug Report

##### COMMAND 
```
ansible-playbook  test-template.yml
-- ansible 2.3.0 (devel 07a517aebd) last updated 2017/01/09
```

##### SUMMARY

I was working on some template improvements and wanted to add the tests in.  I ran into a couple of issues.

1) test-template.yml does not work out of the box.  Perhaps I'm missing something, but it seems to not work with ansible 2.3 dev branch.  Starting with I can't see where TEST_DIR was defined, | split('_') balks, and with_items on the last task seemed to be in the wrong spot.  I was able to work through these and get it running with the diff below (Also simplified the prompting a bit with new var setup).

```diff
--- a/test-template.yml
+++ b/test-template.yml
@@ -7,30 +7,27 @@
   vars_prompt:
     - name: template_name
       prompt: "Enter the name of the template to verify:"
-      default: "cisco_nxos_show_ip_route"
-      private: no
-
-    - name: platform
-      prompt: "Enter the platform"
-      default: "cisco_nxos"
+      default: "cisco_ios_show_snmp_community"
       private: no

+  vars:
+    top_dir: "{{ lookup('env', 'PWD') }}"
+    TEST_DIR: "{{ top_dir }}/tests/"
+    platform: "{{ template_name.split('_')[0:2] | join('_') }}"
+    command_variable: "{{ template_name.split(platform + '_') | last }}"
+    command: "{{ command_variable.split('_') | join(' ') }}"
+
   tasks:

-  - name: extract command from template name
-    set_fact: command_variable="{{ template_name | split(platform + '_') | last }}"
-
-  - name: extract command string from command_variable
-    set_fact: command="{{ command_variable | split('_') | join(' ') }}"
-
   - name: run TextFSM locally on test input
     ntc_show_command:
       connection: offline
       file: "{{ item }}"
       platform: "{{ platform }}"
       command: "{{ command }}"
+      template_dir: "{{ top_dir }}/templates"
     with_fileglob:
-      - "{{ TEST_DIR }}/{{ platform }}/{{ command_variable}}/{{ template_name}}*.raw"
+      - "{{ TEST_DIR }}/{{ platform }}/{{ command_variable }}/{{ template_name }}*.raw"
     register: ntc_result

   - name: read parsed sample files
@@ -39,7 +36,7 @@
     register: ntc_result

   - name: verify that parsed result is the same as expected
+    with_items: "{{ ntc_result.results }}"
     compare_dict:
       result: "{{ item.item.response }}"
       sample: "{{ item.ansible_facts.parsed_sample }}"
-    with_items: "{{ ntc_result.results }}"
```
2) In addition to the above, once I did get it working I was not able to do negative testing with incorrect values on the parsed vs raw samples.  After digging a little further I found that compare_dict was not doing the job 100%.  I'm not sure if things changed somewhere in ansible, but the dicts are being passed in as strings and it appears to be breaking the string into characters to compare the expected results contains the same set of ascii characters (not necessarily in the right order!)  I was able to work out a patch for this as well, but I wanted to mention it before hand.  As that code is also in a separate repo, probably should just discuss there.  test-templates.py has a similar compare function in this repo, but I wasn't able to get that to run either.

3) after I succeeded with the above, ran into a case where I wanted to introduce a new variable (for ios show snmp) as entries can optional have an ACL apply, but then I wasn't sure how the template verification should handle "optional" record variables.  I think gTextFSM probably shouldn't be returning them if they were not parsed out of the input (or at least differentiate undefined from ""), but it not clear to me if you can make vars optional.  I guess I can discuss this one separately later, but just wanted to mention it.

**Comment by bdowling** [comment]
I think I have a more complete compare_dict module working now.  I haven't submitted it as a PR yet as I'm looking for input/feedback on this issue first to make sure I didn't take a wrong turn.

https://github.com/bdowling/ntc-ansible/tree/testing_fixes

Here is some of the relevant output of the aformentioned cisco_ios_show_snmp_community tests output with this new compare_dict:

```json
"result": [
  {
  "item": "*/ansible-modules/ntc-ansible/ntc-templates/tests/cisco_ios/show_snmp_community/cisco_ios_show_snmp_community_2.raw",
  
  "stdout": "Test Group[1]: Value for key 'acl' is not same as sample input\nResult was: 'SNMPILMIacl'\nSample was: 'SNMPILMIaclBAD'\n | Key 'extra' is not found in result output",
    "stdout_lines": [
        "Test Group[1]: Value for key 'acl' is not same as sample input",
        "Result was: 'SNMPILMIacl'",
        "Sample was: 'SNMPILMIaclBAD'",
        " | Key 'extra' is not found in result output"]
  },
  {
   "item": "*/ntc-templates/tests/cisco_ios/show_snmp_community/cisco_ios_show_snmp_community.raw",
   "msg": "Differences were detected in the raw vs parsed",
    "stdout": "Test Group[1]: Key 'acl' is not found in sample input\nTest Group[2]: Key 'acl' is not found in sample input\nTest Group[3]: Key 'acl' is not found in sample input",
    "stdout_lines": [
        "Test Group[1]: Key 'acl' is not found in sample input",
        "Test Group[2]: Key 'acl' is not found in sample input",
        "Test Group[3]: Key 'acl' is not found in sample input"]
}]
```

Just noticed a styling issue with the " | Key" line there, but that could be fixed.

**Comment by itdependsnetworks** [comment]
Just went  this issue over briefly but I have noticed the same thing. Also the further detail in failure message should be helpful.

**Comment by bdowling** [comment]
I know I paraphased the errors as I didn't want to paste each one I worked through, but, fwiw, these are the initial errors encountered:

```
ask path: /home/bdowling/src/ansible-modules/ntc-ansible/ntc-templates/test-template.yml:20
fatal: [127.0.0.1]: FAILED! => {
    "failed": true,
    "msg": "template error while templating string: no filter named 'split'. String: {{ template_name | split(platform + '_') | last }}"
}
```
changing the `| split('_')` to `.split('_')` gets you to the TEST_DIR error:
```
TASK [run TextFSM locally on test input] ******************************************************
task path: /home/bdowling/src/ansible-modules/ntc-ansible/ntc-templates/test-template.yml:26
fatal: [127.0.0.1]: FAILED! => {
    "failed": true,
    "msg": "'TEST_DIR' is undefined"
}
```

Fixing those two issues led me to the other discovery that the dictionary comparisons were not working as intended.
