### ISSUE TITLE
missing tests folder for cisco_ios_show_ip_bgp

### ISSUE THREAD

**Issue by jmcgill298** [networktocode/ntc-templates#74]
##### ISSUE TYPE

 - Missing Files

##### TEMPLATE USING

```
cisco_ios_show_ip_bgp
```
##### SUMMARY

The folder containing the raw and parsed files is missing.
@wintermute000 do you have these files? Are you on the networktocode slack channel?

**Comment by wintermute000** [comment]
Hi jmcgill298

unfortunately I was testing/writing the code using customer output. I can't share them, but you can run the code against any example and see for yourself.

note I'm still not sure its 100% correct as I didn't do a line by line comparison of over 10k routes but from the data that I was comparing it seemed to do the job. It definitely handles a TON more corner cases than the initial code.

Sorry I'm not in that slack, happy to join, though I'm just a dabbler.

**Comment by sjtarik** [comment]
Hi @wintermute000,

Why don't you anonymize it? You can replace Ip patterns with some non-routable ones, mac addresses with random mac combinations and remove all resolved URL addresses. I have a simple hack script doing that before posting tests. Maybe we should include something like that in project.

Best,
Tarik

**Comment by wintermute000** [comment]
How about these? I just took the example from the Cisco textbook.

[example.txt](https://github.com/networktocode/ntc-templates/files/702982/example.txt)
[output.txt](https://github.com/networktocode/ntc-templates/files/702983/output.txt)
