### ISSUE TITLE
cisco_nxos_show_ip_bgp_summary.textfsm doesn't account for dual line bgp when output is too wide

### ISSUE THREAD

**Issue by ChiefArcher** [networktocode/ntc-templates#766]
"show ip bgp sum" on nxos.
If you have a long remote-asn (such as a asdot notation or just a big remote-asn), nxos splits it into two lines

Example:
10.5.253.1   4 65001.0
                            123123  123123 123123132  0 0 1w5d  4452
instead of 
10.5.253.1 4 65001.0 123123  123123 123123132  0 0 1w5d  4452

in cisco_nxos_show_ip_bgp_summary.textfsm
add
^${BGP_NEIGH}\s+\d+\s+${NEIGH_AS}
^\s+${MSG_RCVD}\s+${MSG_SENT}\s+\d+\s+${IN_QUEUE}\s+${OUT_QUEUE}\s+${UP_DOWN}\s+${STATE_PFXRCD}\s*$$ -> Record

under line 17:
^${BGP_NEIGH}\s+\d+\s+${NEIGH_AS}\s+${MSG_RCVD}\s+${MSG_SENT}\s+\d+\s+${IN_QUEUE}\s+${OUT_QUEUE}\s+${UP_DOWN}\s+${STATE_PFXRCD}\s*$$ -> Record

**Comment by FragmentedPacket** [comment]
@ChiefArcher Did the PR above solve all your issues?

**Comment by ChiefArcher** [comment]
yep.. good to go
