### ISSUE TITLE
Issue with cisco_ios_show_vrf.textfsm template

### ISSUE THREAD

**Issue by rara08** [networktocode/ntc-templates#786]
@whitej6

##### ISSUE TYPE
 - Bug Report

##### TEMPLATE USING

`
  Value Required NAME (\S+)
  Value DEFAULT_RD ((\d+|\d{1,3}.\d{1,3}.\d{1,3}.\d{1,3}):\d+|<not set>)
  Value PROTOCOLS (\S+)
  Value List INTERFACES (\S+)

  Start
    ^\s+Name\s+Default RD\s+Protocols\s+Interfaces -> Start_record
    # Capture time-stamp if vty line has command time-stamping turned on
    ^Load\s+for\s+
    ^Time\s+source\s+is

  Start_record
    ^\s{2}\S+ -> Continue.Record
    ^\s{60}\s+${INTERFACES}
    ^\s+${NAME}\s+${DEFAULT_RD}\s+${PROTOCOLS}\s+${INTERFACES}
`

##### SAMPLE COMMAND OUTPUT from stdout

Name                             Default RD            Protocols   Interfaces\n  Mgmt-vrf                         <not set>             ipv4,ipv6   Gi0/0\n  user                             172.30.197.254:5      ipv4        Lo0\n                                                                     Vl10\n                                                                     Vl11\n                                                                     Vl25

##### SUMMARY
Parser does not parse output correctly.  I had to remove "\s+" from start (line 7).
This was on Cat9K running - Cisco IOS XE Software, Version 16.06.06

##### STEPS TO REPRODUCE

'
  - name: SYS >> Parse show vrf command
     set_fact:
       vrf_facts: "{{ command_output.stdout[0] | parse_cli_textfsm('template/cisco_ios_show_vrf.template') }}"
'

##### EXPECTED RESULTS

Correctly structure "sh vrf" output.

##### ACTUAL RESULTS
Failed parse, empty variable.
vrf_facts = []

**Comment by zkiroel** [comment]
hello, are you able to share an image that illustrates how that must work (output sample I mean), please?
my device is c76xx and removing \s+ was not helped with 'show vrf'
Thank you

**Comment by itdependsnetworks** [comment]
Closing pending receipt of raw data, feel free to re-open/re-create once that raw data is provided.
