### ISSUE TITLE
cisco_nxos_show_environment return an empty list

### ISSUE THREAD

**Issue by harinw03** [networktocode/ntc-templates#790]
##### ISSUE TYPE
 - Bug Report

##### TEMPLATE USING

```
Value POWER_SUPPLY (\d+)
Value POWER_SUPPLY_MODEL (\S+)
Value POWER_SUPPLY_OUTPUT (\d+)
Value POWER_SUPPLY_CAPACITY (\d+)
Value POWER_SUPPLY_STATUS (\w+)
Value FAN (\S+)
Value FAN_STATUS (\S+)
Value TEMPERATURE_MODULE (\d+)
Value TEMPERATURE_SENSOR (\S+)
Value TEMPERATURE_MAJOR_THRESH (\d+)
Value TEMPERATURE_MINOR_THRESH (\d+)
Value TEMPERATURE_CURRENT (\d+)
Value TEMPERATURE_STATUS (\S+)

Start
  ^Power\s+Actual\s+Total -> Power
  ^Fan\s+Model\s+Hw\s+Status -> Fan

Power
  ^${POWER_SUPPLY}\s+${POWER_SUPPLY_MODEL}\s+${POWER_SUPPLY_OUTPUT}\s+\w+\s+${POWER_SUPPLY_CAPACITY}\s+\w+\s+${POWER_SUPPLY_STATUS} -> Record
  ^Module\s+Model\s+Draw\s+Allocated\s+Status -> Start

Fan
  ^Fan\s+Zone\s+Speed -> Temperature
  ^${FAN}\s+\S+\s+\S+\s+${FAN_STATUS} -> Record
  ^Temperature: -> Temperature

Temperature
  ^${TEMPERATURE_MODULE}\s+${TEMPERATURE_SENSOR}(\s+)?\(\S+\)\s+${TEMPERATURE_MAJOR_THRESH}\s+${TEMPERATURE_MINOR_THRESH}\s+${TEMPERATURE_CURRENT}\s+${TEMPERATURE_STATUS} -> Record
```

##### SAMPLE COMMAND OUTPUT

```
Power Supply:
Voltage: 12 Volts
Power                             Actual      Actual        Total
Supply    Model                   Output      Input      Capacity    Status
                                (Watts )    (Watts )     (Watts )
-------  -------------------  ----------  ----------  ----------  --------------
1        N9K-PAC-650W              101 W       103 W       650 W     Ok
2        N9K-PAC-650W               96 W       102 W       650 W     Ok


Power Usage Summary:
--------------------
Power Supply redundancy mode (configured)                PS-Redundant
Power Supply redundancy mode (operational)               PS-Redundant

Total Power Capacity (based on configured mode)             650.00 W
Total Grid-A (first half of PS slots) Power Capacity        650.00 W
Total Grid-B (second half of PS slots) Power Capacity       650.00 W
Total Power of all Inputs (cumulative)                     1300.00 W
Total Power Output (actual draw)                            197.00 W
Total Power Input (actual draw)                             206.00 W
Total Power Allocated (budget)                                N/A
Total Power Available for additional modules                  N/A

Fan:
---------------------------------------------------------------------------
Fan             Model                Hw     Direction       Status
---------------------------------------------------------------------------
Fan1(sys_fan1)  N9K-C9300-FAN2       --     front-to-back   Ok
Fan2(sys_fan2)  N9K-C9300-FAN2       --     front-to-back   Ok
Fan3(sys_fan3)  N9K-C9300-FAN2       --     front-to-back   Ok
Fan_in_PS1      --                   --     front-to-back   Ok
Fan_in_PS2      --                   --     front-to-back   Ok
Fan Zone Speed: Zone 1: 0x80
Fan Air Filter : NotSupported


Temperature:
--------------------------------------------------------------------
Module   Sensor        MajorThresh   MinorThres   CurTemp     Status
                       (Celsius)     (Celsius)    (Celsius)
--------------------------------------------------------------------
1        FRONT           70              42          24         Ok
1        BACK            80              70          26         Ok
1        CPU             90              80          42         Ok
1        TD2-1           105             90          35         Ok
1        NS-1            105             90          37         Ok

```

##### SUMMARY
cisco nxos show environment returns empty[]. Show environment temperature works perfectly. 

##### STEPS TO REPRODUCE

```
	swenv = sshsw1.send_command("show environment")
	postntcenv = parse_output(platform=cisco_nxos, command="show environment", data=swenv)
        print (postntcenv)
```

##### ACTUAL RESULTS
```
   []
```

**Comment by diepes** [comment]
@itdependsnetworks i would like to fix this,
 just to make sure im on the right track, "SAMPLE COMMAND OUTPUT" above will be added as "tests/cisco_nxos/show_environments/cisco_nxos_show_environments2.raw" ?

**Comment by jmcgill298** [comment]
@diepes it would be *environment* without the "s", but that would be the correct path.

**Comment by diepes** [comment]
@harinw03 what info from the output were you trying to retrieve ?
Proposed fix will give the power supply output.

For the rest it would be better to use more specific commands 
e.g.
     show environment fan
     show environment clock
     show environment temperature
     show environemtn "power usage" ??? 

As far as i can see we can only extract a single table at a time.

```
---
parsed_sample:
  - power_supply: "1"
    power_supply_model: "N7K-AC-3KW"
    power_supply_output: "407"
    power_supply_input: ""
    power_supply_capacity: "3000"
    power_supply_status: "Ok"
    power_supply_voltage: "50"
  - power_supply: "2"
    power_supply_model: "N7K-AC-3KW"
    power_supply_output: "370"
    power_supply_input: ""
    power_supply_capacity: "3000"
    power_supply_status: "Ok"
    power_supply_voltage: "50"

```

**Comment by harinw03** [comment]
@diepes I was looking for below tables "power" and "fan". I was able to use "show environment temperature ". 
Does "show environment fan " command output can be parsed in same module ?


Power Supply:
Voltage: 12 Volts
Power                             Actual      Actual        Total
Supply    Model                   Output      Input      Capacity    Status
                                (Watts )    (Watts )     (Watts )
-------  -------------------  ----------  ----------  ----------  --------------
1        N9K-PAC-650W              101 W       103 W       650 W     Ok
2        N9K-PAC-650W               96 W       103 W       650 W     Ok

Fan:
---------------------------------------------------------------------------
Fan             Model                Hw     Direction       Status
---------------------------------------------------------------------------
Fan1(sys_fan1)  N9K-C9300-FAN2       --     front-to-back   Ok
Fan2(sys_fan2)  N9K-C9300-FAN2       --     front-to-back   Ok
Fan3(sys_fan3)  N9K-C9300-FAN2       --     front-to-back   Ok
Fan_in_PS1      --                   --     front-to-back   Ok
Fan_in_PS2      --                   --     front-to-back   Ok
Fan Zone Speed: Zone 1: 0x80
Fan Air Filter : NotSupported

**Comment by diepes** [comment]
@harinw03  the best is probably to log a new issue for nxos "show environment fan" and "show environment power", with the command and the output, then we can add it.
Looking at the above, we should be able to parse the Fan table, (excluding the "Fan Zone Speed", and "Fan Air Filter"
