### ISSUE TITLE
This is not a data modeling project. So is there any data modeling project can work with this?

### ISSUE THREAD

**Issue by KongNan** [networktocode/ntc-templates#802]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
**(This is not a Feature Idea)**

I know this is not a data modeling project. 
So is there any data modeling project can work with this?
Thank you!

Sorry my English is poor

**Comment by itdependsnetworks** [comment]
You can look at https://github.com/CiscoTestAutomation/genieparser

**Comment by KongNan** [comment]
I tried that and fount it doesn't support windows. But still a great work. Thank you!
