### ISSUE TITLE
change key names to match ios template

### ISSUE THREAD

**Issue by centove** [networktocode/ntc-templates#816]
##### ISSUE TYPE
 - Feature Idea

##### TEMPLATE USING
Value Filldown NAME (\S+)
Value Required SN (\d+)
Value ACTION (\w+)
Value PROTOCOL ([^any][\w+\d+]+)
Value SOURCE (host\s\d+\.\d+\.\d+\.\d+|any|\d+\.\d+\.\d+\.\d+/\d+)
Value PORT_MODIFIER (eq|gt|lt|neq|range)
Value PORT_RANGE ([(\S+\s\S+)]+)
Value DESTINATION (host\s\d+\.\d+\.\d+\.\d+|any|\d+\.\d+\.\d+\.\d+/\d+) 
Value MODIFIER (.*)

Start
  ^.*List\s+${NAME}(\s+\[readonly\])* 
  ^\s+${SN}\s+${ACTION}\s+${PROTOCOL}\s+${SOURCE}(\s+${PORT_MODIFIER})*(\s${PORT_RANGE})*\s+${DESTINATION}(\s+${MODIFIER})* -> Record

```

```

##### SAMPLE COMMAND OUTPUT
```

```

##### SUMMARY
Rename fields SN and NAME to LINE_NUM and ACL_NAME to have consistent keys between ios and eos outputs 
so you don't wind up with a spaghetti mess of conditional code while processing the output from multiple devices.

**Comment by itdependsnetworks** [comment]
Mistakes were made... we should have considered this from the start but it was not. That being said we have decided not to pursue these changes as there are many people expecting the current keys and it would be problematic to them. 

Apologies.
