### ISSUE TITLE
arista_eos_show_interfaces_status parse failures

### ISSUE THREAD

**Issue by centove** [networktocode/ntc-templates#834]
##### ISSUE TYPE
 - Bug Report

##### TEMPLATE USING
arista_eos_show_interfaces_status.textfsm
Value PORT (\S+)
Value NAME (\S.*(?<!\s))
Value STATUS (connected|notconnect|inactive|errdisabled|disabled)
Value VLAN (\S+)
Value DUPLEX (\S+)
Value SPEED (\S+)
Value TYPE (\S+)

Start
  ^${PORT}\s+${NAME}\s+${STATUS}\s+${VLAN}\s+${DUPLEX}\s+${SPEED}\s+${TYPE} -> Record
  ^${PORT}\s+${STATUS}\s+${VLAN}\s+${DUPLEX}\s+${SPEED}\s+${TYPE} -> Record

```

```

##### SAMPLE COMMAND OUTPUT

Port       Name              Status       Vlan        Duplex  Speed Type        
Et1        Cust: (SERV-XXXXX disabled     1             auto   auto 1000BASE-T  
Et2        Cust: (SERV-01694 disabled     1             auto   auto 1000BASE-T  
Et3        Cust: (SERV-XXXXX disabled     1             auto   auto 1000BASE-T  
Et4        Cust: (SERV-01695 disabled     1             auto   auto 1000BASE-T  
Et5        Cust: (SERV-XXXXX disabled     1             auto   auto 1000BASE-T  
Et6        Cust: (SERV-01696 disabled     1             auto   auto 1000BASE-T  
Et7        Cust: (SERV-XXXXX disabled     1             auto   auto 1000BASE-T  
Et8        Cust: (SERV-01697 disabled     1             auto   auto 1000BASE-T  
Et9        Cust: (SERV-XXXXX disabled     1             auto   auto 1000BASE-T  
Et10       Cust: (SERV-01698 disabled     1             auto   auto 1000BASE-T  
Et11       Cust: (SERV-XXXXX disabled     1             auto   auto 1000BASE-T  
Et12       Cust: (SERV-01699 disabled     1             auto   auto 1000BASE-T  
Et13       Cust: (SERV-XXXXX disabled     1             auto   auto 1000BASE-T  
Et14       Cust: (SERV-01700 disabled     1             auto   auto 1000BASE-T  
Et15       Cust: (SERV-XXXXX disabled     1             auto   auto 1000BASE-T  
Et16       Cust: (SERV-01701 disabled     1             auto   auto 1000BASE-T  
Et17       Cust: (SERV-XXXXX disabled     1             auto   auto 1000BASE-T  
Et18       Cust: (SERV-01702 disabled     1             auto   auto 1000BASE-T  
Et19       Cust: (SERV-XXXXX disabled     1             auto   auto 1000BASE-T  
Et20       Cust: (SERV-01703 disabled     1             auto   auto 1000BASE-T  
Et21       Cust: (SERV-XXXXX disabled     1             auto   auto 1000BASE-T  
Et22       Cust: (SERV-01704 disabled     1             auto   auto 1000BASE-T  
Et23       Cust: (SERV-XXXXX disabled     1             auto   auto 1000BASE-T  
Et24       Cust: (SERV-01705 disabled     1             auto   auto 1000BASE-T  
Et25       Cust: (SERV-XXXXX disabled     1             auto   auto 1000BASE-T  
Et26       Cust: (SERV-01706 disabled     1             auto   auto 1000BASE-T  
Et27       Cust: (SERV-XXXXX disabled     1             auto   auto 1000BASE-T  
Et28       Cust: (SERV-01707 disabled     1             auto   auto 1000BASE-T  
Et29       Cust: (SERV-XXXXX disabled     1             auto   auto 1000BASE-T  
Et30       Cust: (SERV-01708 disabled     1             auto   auto 1000BASE-T  
Et31       Cust: (SERV-XXXXX disabled     1             auto   auto 1000BASE-T  
Et32       Cust: (SERV-01709 disabled     1             auto   auto 1000BASE-T  
Et33       Cust: (SERV-XXXXX disabled     1             auto   auto 1000BASE-T  
Et34       Cust: (SERV-01710 disabled     1             auto   auto 1000BASE-T  
Et35       Cust: (SERV-XXXXX disabled     1             auto   auto 1000BASE-T  
Et36       Cust: (SERV-01711 disabled     1             auto   auto 1000BASE-T  
Et37       Cust: (SERV-XXXXX disabled     1             auto   auto 1000BASE-T  
Et38       Cust: (SERV-01712 disabled     1             auto   auto 1000BASE-T  
Et39       Cust: (SERV-XXXXX disabled     1             auto   auto 1000BASE-T  
Et40       Cust: (SERV-01713 disabled     1             auto   auto 1000BASE-T  
Et41       Cust: (SERV-XXXXX disabled     1             auto   auto 1000BASE-T  
Et42       Cust: (SERV-01714 disabled     1             auto   auto 1000BASE-T  
Et43       Cust: (SERV-XXXXX disabled     1             auto   auto 1000BASE-T  
Et44       Cust: (SERV-01715 disabled     1             auto   auto 1000BASE-T  
Et45       Cust: (SERV-XXXXX disabled     1             auto   auto 1000BASE-T  
Et46       Cust: (SERV-01716 disabled     1             auto   auto 1000BASE-T  
Et47       Cust: (SERV-XXXXX disabled     1             auto   auto 1000BASE-T  
Et48       Cust: (SERV-01717 disabled     1             auto   auto 1000BASE-T  
Et49       Core: drxx.yul01  notconnect   in Po49       full    10G Not Present 
Et50       Core: drxx.yul01  notconnect   in Po49       full    10G Not Present 
Et51       Core: drxx.yul01  connected    in Po49       full    10G 10GBASE-SR  
Et52       Core: drxx.yul01  connected    in Po49       full    10G 10GBASE-SR  
Ma1                          notconnect   routed      a-half  a-10M 10/100/1000 
Po49       Core: dr01-dr02.y connected    trunk         full    20G N/A    
```

```

##### SUMMARY
The template in the repository fails on ports et49-et52 as the ports are members of the a port-channel and the vlan field is used to indicate which port-channel they are a member of.

##### STEPS TO REPRODUCE
Use the template to parse a 'show interface status' command on an arista device with port-channels configured with members in the port-channel.  

##### EXPECTED RESULTS
---
{'port': 'Et49', 'name': 'Core: drxx.yul01 () {} [10000Mbit]', 'status': 'notconnect', 'vlan': 'in Po49', 'duplex': 'full', 'speed': '10G', 'type': 'Not Present'}
{'port': 'Et50', 'name': 'Core: drxx.yul01 () {} [10000Mbit]', 'status': 'notconnect', 'vlan': 'in Po49', 'duplex': 'full', 'speed': '10G', 'type': 'Not Present'}
{'port': 'Et51', 'name': 'Core: drxx.yul01 () {} [10000Mbit]', 'status': 'connected', 'vlan': 'in Po49', 'duplex': 'full', 'speed': '10G', 'type': '10GBASE-SR'}
{'port': 'Et52', 'name': 'Core: drxx.yul01 () {} [10000Mbit]', 'status': 'connected', 'vlan': 'in Po49', 'duplex': 'full', 'speed': '10G', 'type': '10GBASE-SR'}
---
##### ACTUAL RESULTS

```
{'port': 'Et49', 'name': 'Core: drxx.yul01 () {} [10000Mbit]', 'status': 'notconnect', 'vlan': 'in', 'duplex': 'Po49', 'speed': 'full', 'type': '10G'}
{'port': 'Et50', 'name': 'Core: drxx.yul01 () {} [10000Mbit]', 'status': 'notconnect', 'vlan': 'in', 'duplex': 'Po49', 'speed': 'full', 'type': '10G'}
{'port': 'Et51', 'name': 'Core: drxx.yul01 () {} [10000Mbit]', 'status': 'connected', 'vlan': 'in', 'duplex': 'Po49', 'speed': 'full', 'type': '10G'}
{'port': 'Et52', 'name': 'Core: drxx.yul01 () {} [10000Mbit]', 'status': 'connected', 'vlan': 'in', 'duplex': 'Po49', 'speed': 'full', 'type': '10G'}
{'port': 'Ma1', 'name': '', 'status': 'notconnect', 'vlan': 'routed', 'duplex': 'a-half', 'speed': 'a-10M', 'type': '10/100/1000'}

```

**Comment by centove** [comment]
Potential fix:
diff --git a/lib/ntc_templates/parse.py b/lib/ntc_templates/parse.py
old mode 100644
new mode 100755
diff --git a/templates/arista_eos_show_interfaces_status.textfsm b/templates/arista_eos_show_interfaces_status.textfsm
index cbbcc7b..6a675ca 100644
--- a/templates/arista_eos_show_interfaces_status.textfsm
+++ b/templates/arista_eos_show_interfaces_status.textfsm
@@ -1,10 +1,10 @@
 Value PORT (\S+)
 Value NAME (\S.*(?<!\s))
 Value STATUS (connected|notconnect|inactive|errdisabled|disabled)
-Value VLAN (\S+)
-Value DUPLEX (\S+)
+Value VLAN (\S.*(?<!\s))
+Value DUPLEX (full|half|auto)
 Value SPEED (\S+)
-Value TYPE (\S+)
+Value TYPE (\S.*(?<!\s))
 
 Start
   ^${PORT}\s+${NAME}\s+${STATUS}\s+${VLAN}\s+${DUPLEX}\s+${SPEED}\s+${TYPE} -> Record
diff --git a/templates/arista_eos_show_ip_access-lists.textfsm b/templates/arista_eos_show_ip_access-lists.textfsm
index a494d62..da63b6f 100644

**Comment by jmcgill298** [comment]
@centove can you put in a PR to address this?

**Comment by centove** [comment]
I have no clue how to work git at that level I barely know how to pull 
stuff :)

**Comment by jmcgill298** [comment]
do you have sample data that you can provide that would show where the current template fails?

**Comment by jmcgill298** [comment]
https://github.com/networktocode/ntc-templates/pull/835
