### ISSUE TITLE
Arista_eos: show ip bgp summary Error 

### ISSUE THREAD

**Issue by mzakkar0** [networktocode/ntc-templates#844]
##### ISSUE TYPE

 - Bug Report

##### TEMPLATE USING

from netmiko import ConnectHandler

from operator import itemgetter

from ntc_templates.parse import parse_output

 

#password = getpass()ex

device_list = open('/Users/817101629/Documents/Python_stuff/python_NW_automation/mylist.yml')

for ip in device_list:

    ip = ip.strip()

    switch = {

        'ip': ip,

        'username': 'admin',

        'password': 'GCC@gcc!',

        'device_type': 'arista_eos',

    }
    print (f'Connecting to the Device: {ip}')
    net_connect = ConnectHandler(**switch)
bgp_output = net_connect.send_command('show ip bgp summary')
bgp_parsed = parse_output(platform="arista_eos", command="show ip bgp summary", data=bgp_output)
print(bgp_parsed)

##### ACTUAL RESULTS

```

```

**Comment by diepes** [comment]
@mzakkar0 please provide output from arista for "show ip bgp summary"

**Comment by FragmentedPacket** [comment]
@mzakkar0 Please reopen once you're able to provide the offending output.
