### ISSUE TITLE
cisco_nxos_show_ip_arp_detail.textfsm fails to parse Age field (Age results are of form 00:14:15 AND 0.732312)

### ISSUE THREAD

**Issue by mcfone** [networktocode/ntc-templates#851]
##### ISSUE TYPE

 - Bug Report

##### TEMPLATE USING

```

Using template cisco_nxos_show_ip_arp_detail.textfsm (supplied as part of ntc-templates v1.60):

Value ADDRESS (\d+\.\d+\.\d+\.\d+)
Value AGE (\d+:\d+:\d+|-)
Value MAC (\S+)
Value INTERFACE (\S+)
Value PHYSICAL_INTERFACE (\S+)

Start
  ^${ADDRESS}\s+${AGE}\s+${MAC}\s+${INTERFACE}\s+${PHYSICAL_INTERFACE} -> Record

```

##### SAMPLE COMMAND OUTPUT

Following command run on a cisco Nexus7000 C7009 L3 switch running NXOS 6.2(20):
sh ip arp detail
(some output elided for brevity)

146.118.64.100  00:14:15  fa16.3eb0.4437  Vlan666          port-channel666 
146.118.64.102  00:00:14  fa16.3e20.e36f  Vlan666          port-channel666 
146.118.64.103  0.732312  fa16.3efe.7305  Vlan666          port-channel666 
146.118.64.148  0.435461  INCOMPLETE      Vlan666          Vlan666         
146.118.64.198  0.380157  INCOMPLETE      Vlan666          Vlan666         
146.118.64.208  0.524358  INCOMPLETE      Vlan666          Vlan666         
146.118.64.224  0.479902  fa16.3e01.958e  Vlan666          port-channel666 
146.118.64.226  0.479649  fa16.3ebc.f748  Vlan666          port-channel666 
146.118.65.0    0.359478  INCOMPLETE      Vlan666          Vlan666         
146.118.65.22   00:07:34  fa16.3e80.3b85  Vlan666          port-channel666 

##### SUMMARY

The pattern for the Age field only matches output lines such as
146.118.64.100  00:14:15  fa16.3eb0.4437  Vlan666          port-channel666 
and not lines such as
146.118.64.103  0.732312  fa16.3efe.7305  Vlan666          port-channel666
resulting in ARP table entries being missed

This can be fixed by changing the Age pattern from
Value AGE (\d+:\d+:\d+|-)
to
Value AGE (\S+)

or by using the updated template:

Value Required ADDRESS (\d+\.\d+\.\d+\.\d+)
Value Required AGE (\S+)
Value Required MAC (\S+)
Value INTERFACE (\S+)
Value PHYSICAL_INTERFACE (\S+)

Start
  ^Address\s+Age\s+MAC Address\s+Interface -> Start_record

Start_record
  ^${ADDRESS}\s+${AGE}\s+${MAC}\s+${INTERFACE}\s+${PHYSICAL_INTERFACE} -> Record
  ^\s+$$
  ^$$
  ^.* -> Error "LINE NOT FOUND"

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by diepes** [comment]
@mcfone please provide the full output for "sh ip arp detail"

then it can be added as an test template to ensure this and future fixes are correct.

e.g. the proposed Value AGE (\d+:\d+:\d+|-) to Value AGE (\S+) fails on the current test as time can also be just a dash.

**Comment by mcfone** [comment]
From my reading, the pattern "\S+" should match any non-whitespace character, so should match a dash...

I note that the template cisco_nxos_show_ip_arp.textfsm also uses "(\S+)" as the Value for AGE.

Full output of "sh ip arp det" attached.

________________________________

**Comment by diepes** [comment]
Thank's @mcfone, added output as new test and did pr #857  to fix template.  Yes you are right \S+ matches, it forgot the "+"

I see the output seem to be cut short ? 

I just removed the last line from the test sample.
"146.118.67.207  00:00:47  fa16.3ee"
