### ISSUE TITLE
Having trouble with textfsm

### ISSUE THREAD

**Issue by r1chardnoggin** [networktocode/ntc-templates#858]
Hello,
I'm new here. I'm a network engineer by trade and I'm trying to get into network automation but I'm a noob on that front, so I'm trying to develop my skillset. I have installed netmiko and textfsm. However when I call on textfsm (net_connect.send_command (show ip interface brief', use_textfsm=True) in my code it fails to use it to parse the output and I just get back unstructured data. I'm not entirely sure what I'm missing. I believe I have installed everything correctly but like I said I'm knew to this arena. 

I have the ntc-templates/templates directory as well as my export NET_TEXTFSM pointed to that location.
`pip3 install ntc-templates` shows requirements already satisfied.
`pip3 list | grep netmiko` shows 3.3.2

Any help would be greatly appreciated.

##### ISSUE TYPE

 - Bug Report
 - Feature Idea
 - Documentation Report

##### TEMPLATE USING

```

```

##### SAMPLE COMMAND OUTPUT

```

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by jmcgill298** [comment]
@r1chardnoggin are you able to follow this example and it work? https://github.com/networktocode/ntc-templates#usage

```
output = net_connect.send_command("show ip interface brief")
from ntc_templates.parse import parse_output
output_parsed = parse_output(platform="cisco_ios", command="show vlan", data=vlan_output)
print(output_parsed)
```

**Comment by r1chardnoggin** [comment]
@jmcgill298 that seems to work. Is this the desired format in order for things to work properly?

**Comment by jmcgill298** [comment]
That is not the method that you are trying to use, but that demonstrates that this project is installed and working as expected. You can get help with netmiko at `https://github.com/ktbyers/netmiko/issues/new` or on the #netmiko channel on `networktocode.slack.com`. I would make sure that your environment variables specifies the absolute path, and if that does not work, then follow up with the netmiko project.

**Comment by FragmentedPacket** [comment]
@r1chardnoggin Hopefully everything is sorted and working for you. If not, join our Slack that @jmcgill298 posted and join the `#netmiko` or `#networktocode` channel for help!
