### ISSUE TITLE
cisco_ios_show_ip_bgp.template some entries are not parsed

### ISSUE THREAD

**Issue by dirkvdplas** [networktocode/ntc-templates#87]
##### ISSUE TYPE

 - Bug Report

##### TEMPLATE USING
Value Filldown STATUS ([bdhimrsSx*>])
Value Filldown PATH_SELECTION ([bdhimrsSx*> ])
Value Filldown ROUTE_SOURCE ([bdhimrsSx*> ])
Value Filldown NETWORK (\S{0,18})
Value Required NEXT_HOP (\S{0,19})
Value Filldown METRIC (\S{0,6})
Value LOCAL_PREF (\S{0,6})
Value WEIGHT (\S{0,6})
Value AS_PATH (.*?)
Value ORIGIN ([ie\?])

Start
  # Since using mostly position, play it safe and ensure we see header first
  ^\s+Network\s+Next Hop\s+Metric\s+LocPrf\s+Weight\s+Path -> Bgp_table

Bgp_table
  #
  #
  # Match if subnet is 17,18 characters long, creates two lines
  # Example: *>i 10.104.192.208/29
  ^\s{0,1}${STATUS}${PATH_SELECTION}${ROUTE_SOURCE}\s{0,1}(?=${NETWORK}).{17,18}$$ -> Next
  #
  #
  # Compliment to previous, status, path_selection, route_source, network is filldown.
  # Example:                     157.191.186.194          0    100  50000 64801 64808 64608 64601 64787 i
  ^\s{23,25}(?=${NEXT_HOP}).{19}\s(?=\s{0,6}${METRIC}).{6}\s(?=\s{0,6}${LOCAL_PREF}).{6}\s(?=\s{0,6}${WEIGHT}).{6}\s*${AS_PATH}\s*${ORIGIN}$$ -> Record
  #
  #
  # Match first when there is no network, since previous line had it already (compliment and filldown below)
  # Example: * i172.16.1.0/24    172.16.1.2               0    100      0 i
  ^\s{0,1}${STATUS}${PATH_SELECTION}${ROUTE_SOURCE}\s{0,1}\s{16}\s(?=${NEXT_HOP}).{19}\s(?=\s{0,6}${METRIC}).{6}\s(?=\s{0,6}${LOCAL_PREF}).{6}\s(?=\s{0,6}${WEIGHT}).{6}\s*${AS_PATH}\s*${ORIGIN}$$ -> Record
  #
  #
  # Full normal example. metric, and as_path might not exist, regex defaults to blank line.
  # Example: *>                  0.0.0.0                  0         32768 i
  ^\s{0,1}${STATUS}${PATH_SELECTION}${ROUTE_SOURCE}\s{0,1}(?=${NETWORK}).{16}\s(?=${NEXT_HOP}).{19}\s(?=\s{0,6}${METRIC}).{6}\s(?=\s{0,6}${LOCAL_PREF}).{6}\s(?=\s{0,6}${WEIGHT}).{6}\s*${AS_PATH}\s*${ORIGIN}$$ -> Record

EOF

##### SAMPLE COMMAND OUTPUT
```
* i199.16.104.96/27 10.66.166.3              0    100      0 11111 99999 65278 ?
* i                 10.66.166.4              0    100      0 11111 99999 65278 ?
* i                 10.66.166.2              0    100      0 11111 99999 65278 ?
*>                  10.118.160.97                          0 11111 99999 65278 ?
* i199.16.104.128/27
                    10.66.166.3              0    100      0 11111 99999 ?
* i                 10.66.166.4              0    100      0 11111 99999 ?
* i                 10.66.166.2              0    100      0 11111 99999 ?
*>                  10.118.160.97                          0 11111 99999 ?
* i199.16.104.160/27
                    10.66.166.3              0    100      0 11111 99999 ?
* i                 10.66.166.4              0    100      0 11111 99999 ?
* i                 10.66.166.2              0    100      0 11111 99999 ?
*>                  10.118.160.97                          0 11111 99999 ?

```

Parsed output (the issue is with prefix 199.16.104.128/27  (this is not an actual public ip, pure for demonstration purposes), 4 paths in "show_ip_bgp" output, but only 3 paths are parsed
```
['*', ' ', 'i', '199.16.104.96/27', '10.66.166.4', '0', '100', '0', '11111 99999 65278', '?']
['*', ' ', 'i', '199.16.104.96/27', '10.66.166.2', '0', '100', '0', '11111 99999 65278', '?']
['*', '>', ' ', '199.16.104.96/27', '10.118.160.97', '', '', '0', '11111 99999 65278', '?']
['*', ' ', 'i', '199.16.104.128/27', '10.66.166.4', '0', '100', '0', '11111 99999', '?']
['*', ' ', 'i', '199.16.104.128/27', '10.66.166.2', '0', '100', '0', '11111 99999', '?']
['*', '>', ' ', '199.16.104.128/27', '10.118.160.97', '', '', '0', '11111 99999', '?']
['*', ' ', 'i', '199.16.104.160/27', '10.66.166.4', '0', '100', '0', '11111 99999', '?']
['*', ' ', 'i', '199.16.104.160/27', '10.66.166.2', '0', '100', '0', '11111 99999', '?']

````

##### SUMMARY

Textfsm Parsed output only shows 3 out of 4 paths for prefix 199.16.104.128/27. The first path is not parsed. I am using textfsm version 0.2.2 directly from commandline on Linux Ubuntu 14.4, python 2.7.12

**Comment by itdependsnetworks** [comment]
@dirkvdplas can you please edit your Issue to include backticks around the output? Textfsm is extremely sensitive to spacing and need to see this in the original formating. Can you also un-omit that output for similar reasons

**Comment by dirkvdplas** [comment]
@itdependsnetworks  can I send the requested output to you via private message? I don't want to provide output of our bgp-table here (for security reasons)

**Comment by itdependsnetworks** [comment]
@dirkvdplas that is fine. you can contact me on slack, or e-mail ken@networktocode.com. 

Either way, can you please clean up the original so it is viewable? 

e.g. 
\`\`\` 
\<your code here\>
 \`\`\`

**Comment by itdependsnetworks** [comment]
Can you try changing this line: https://github.com/networktocode/ntc-templates/blob/master/templates/cisco_ios_show_ip_bgp.template#L26

from: `^\s{23,25}`
to: `^\s{20,25}`

?

**Comment by dirkvdplas** [comment]
Hi Ken,

You’re the man! This fixes the issue. I performed a diff compared to original parsed output and the new parsed output has all the missing entries!
Thanks.

Dirk

Van: Ken Celenza [mailto:notifications@github.com]
Verzonden: vrijdag 24 februari 2017 4:38
Aan: networktocode/ntc-templates
CC: Plas, Dirk van der; Mention
Onderwerp: Re: [networktocode/ntc-templates] cisco_ios_show_ip_bgp.template some entries are not parsed (#87)


Can you try changing this line: https://github.com/networktocode/ntc-templates/blob/master/templates/cisco_ios_show_ip_bgp.template#L26

from: ^\s{23,25}
to: ^\s{20,25}

?
