### ISSUE TITLE
cisco_nxos_show_interface_brief.texfsm and output modifier unexpected result

### ISSUE THREAD

**Issue by Tes3awy** [networktocode/ntc-templates#938]
##### ISSUE TYPE

 - Bug Report

```python
from netmiko import ConnectHandler

device = {
        "device_type": "cisco_nxos",
        "ip": ip,
        "username": "cisco",
        "password": "cisco",
}

with ConnectHandler(**device) as net_connect:
    # Parse the hostname of the device
    hostname = net_connect.send_command("show hostname", use_textfsm=True)[0]["hostname"]
    # Parse the show interface brief of the  device
    dwn_intfs = net_connect.send_command("show interface brief | include ^Eth.*down.*Link.not.connected", use_textfsm=True)

print(dwn_intfs)
```

##### SAMPLE COMMAND OUTPUT

```cisco
Eth1/6          1       eth  access down    Link not connected       auto(D) --
Eth1/7          1       eth  access down    Link not connected       auto(D) --
Eth1/8          1       eth  access down    Link not connected       auto(D) --
Eth1/9          1       eth  access down    Link not connected       auto(D) --
Eth1/10         1       eth  access down    Link not connected       auto(D) --
...output truncated
```

##### SUMMARY

I am using Netmiko with TEXTFSM to parse the `down` + `Link not connected` interfaces on a Nexus switch. Basically, this output modifier gets me what I need (`include ^Eth.*down.*Link.not.connected`), but it is not converted into a list of dictionaries as expected. Running the Python script without the output modifier, I get the expected result `list[dicts]`. So, the problem is with the output modifier after the `|`.

##### STEPS TO REPRODUCE
Run the attached Python sample script.

##### EXPECTED RESULTS
```json
{
    "description": "",
    "interface": "Eth1/6",
    "ip": "",
    "mode": "access",
    "mtu": "",
    "portch": "--",
    "reason": "Link not connected",
    "speed": "auto(D)",
    "status": "down",
    "type": "eth",
    "vlan": "1",
    "vrf": ""
},
{
    "description": "",
    "interface": "Eth1/7",
    "ip": "",
    "mode": "access",
    "mtu": "",
    "portch": "--",
    "reason": "Link not connected",
    "speed": "auto(D)",
    "status": "down",
    "type": "eth",
    "vlan": "1",
    "vrf": ""
},
...output truncated
```

##### ACTUAL RESULTS

```
Eth1/6          1       eth  access down    Link not connected       auto(D) --
Eth1/7          1       eth  access down    Link not connected       auto(D) --
Eth1/8          1       eth  access down    Link not connected       auto(D) --
Eth1/9          1       eth  access down    Link not connected       auto(D) --
Eth1/10         1       eth  access down    Link not connected       auto(D) --
...output truncated
```

Thank you.

**Comment by Tes3awy** [comment]
Any updates?

**Comment by jvanderaa** [comment]
This can't parse the headers. You should likely be just sending the entire command and do the processing within the Python looking for the list items you are looking for.

**Comment by Tes3awy** [comment]
> 
> 
> This can't parse the headers. You should likely be just sending the entire command and do the processing within the Python looking for the list items you are looking for.

Hello @jvanderaa,

I used the same output modifier with `cisco_ios` instead of `cisco_nxos` and it worked and parsed the expected output.

You can try it out:

```python
from netmiko import ConnectHandler

device = {
    "device_type": "cisco_ios",
    "ip": "sandbox-iosxe-latest-1.cisco.com",
    "username": "developer",
    "password": "C1sco12345"
}

with ConnectHandler(**device) as net_connect:
    output = net_connect.send_command(
        command_string="show ip interface brief | include ^GigabitEthernet.*up.*up",
        use_textfsm=True,
    )

print(output)
```

**output:**

```json
[
    {
        "intf": "GigabitEthernet1",
        "ipaddr": "10.10.20.48",
        "status": "up",
        "proto": "up",
    },
    {
        "intf": "GigabitEthernet2",
        "ipaddr": "10.10.30.48",
        "status": "up",
        "proto": "up",
    },
    {
        "intf": "GigabitEthernet2.1629",
        "ipaddr": "10.198.177.1",
        "status": "up",
        "proto": "up",
    },
]
```

**Comment by jvanderaa** [comment]
What happens if you send the command `show interface brief`? You should get all of the table. Then pull the parsing out of the table.

**Comment by Tes3awy** [comment]
> What happens if you send the command `show interface brief`? You should get all of the table. Then pull the parsing out of the table. 

I mentioned this in the issue. When I send the command without any output modifier, I get the expected output (list[dict]), otherwise, I get plain text output. So, I am wondering why does output modifiers work with _cisco_ios_ but don't work with _cisco_nxos_!

**Comment by jvanderaa** [comment]
I don't have a NXOS readily in front of me and have to spend some time to get one spun up. On the NXOS template the start of the parsing is defined on lines 14/15 here: https://github.com/networktocode/ntc-templates/blob/master/ntc_templates/templates/cisco_nxos_show_interface_brief.textfsm#L14

```
Start
  ^Port\s+VRF\s+Status\s+IP\s+Address\s+Speed\s+MTU -> Management 
```

Since those lines do not show up in the output, then the TextFSM parser does not know where to start parsing. 

The IOS output likely has the start portion in the command output, and thus why it is able to parse and not the NXOS.

Thanks for the clarification on the question @Tes3awy as I was thrown off by the title.

**Comment by Tes3awy** [comment]
> I don't have a NXOS readily in front of me and have to spend some time to get one spun up. On the NXOS template the start of the parsing is defined on lines 14/15 here: https://github.com/networktocode/ntc-templates/blob/master/ntc_templates/templates/cisco_nxos_show_interface_brief.textfsm#L14
> 
> 
> 
> ```
> 
> Start
> 
>   ^Port\s+VRF\s+Status\s+IP\s+Address\s+Speed\s+MTU -> Management 
> 
> ```
> 
> 
> 
> Since those lines do not show up in the output, then the TextFSM parser does not know where to start parsing. 
> 
> 
> 
> The IOS output likely has the start portion in the command output, and thus why it is able to parse and not the NXOS.
> 
> 
> 
> Thanks for the clarification on the question @Tes3awy as I was thrown off by the title. 

Thanks a lot for your elaboration. I really appreciate it 🙏🏻
