### ISSUE TITLE
pls help with multiple text lines parsing into a LIST

### ISSUE THREAD

**Issue by Kennyisnothere** [networktocode/ntc-templates#948]
text as below:
VID Ports
1 UT:Eth-Trunk39(D) Eth-Trunk100(D) 10GE1/0/3(D) 10GE1/0/4(D)
10GE2/0/3(D) 10GE2/0/4(D) GE1/0/1(U) GE1/0/3(U)
GE1/0/5(U) GE1/0/7(U) GE1/0/9(U) GE1/0/11(U)
20 TG:Eth-Trunk1(U) Eth-Trunk2(U) Eth-Trunk3(U) Eth-Trunk4(U)
Eth-Trunk5(U) Eth-Trunk6(U) Eth-Trunk7(U) Eth-Trunk8(U)
Eth-Trunk9(U) Eth-Trunk10(U) Eth-Trunk11(U) Eth-Trunk12(U)

textfsm template as below:
Value VID (\d+)
Value List Port (Eth-Trunk\d+|10GE\d+/\d+/\d+|GE\d+/\d+/\d+)

Start
^ +.* -> Continue.Record
^ +${VID} +(UT|ST|UT|MP|TG):${Port}( -> Continue
^ +${VID} +\S+)+ +${Port}( -> Continue
^ +${VID} +\S+) +\S+ +${Port}( -> Continue
^ +${VID} +\S+)+ +\S+ +\S+ +${Port}( -> Continue
^ +${Port}( -> Continue
^ +\S+)+ +${Port}( -> Continue
^ +\S+) +\S+)+ +${Port}( -> Continue
^ +\S+) +\S+)+ +\S+ +${Port}( -> Continue
^ +\S+) +\S+)+ +\S+ +\S+ +${Port}( -> Continue

result as below:
=============== RESTART: C:\Users\kennytan\Desktop\Python\Huawei - py\HW-TexFSM1.py ==============
VID Port

1 ['Eth-Trunk39', 'Eth-Trunk100', '10GE1/0/3', '10GE1/0/4']
['10GE2/0/3', '10GE2/0/4', 'GE1/0/1', 'GE1/0/3']
['GE1/0/5', 'GE1/0/7', 'GE1/0/9', 'GE1/0/11']
20 ['Eth-Trunk1', 'Eth-Trunk2', 'Eth-Trunk3', 'Eth-Trunk4']
['Eth-Trunk5', 'Eth-Trunk6', 'Eth-Trunk7', 'Eth-Trunk8']
['Eth-Trunk9', 'Eth-Trunk10', 'Eth-Trunk11', 'Eth-Trunk12']

**how can i make the second & third list merging into the first list, likewise for the last three lists merging into one list???Many thanks!**

**Comment by itdependsnetworks** [comment]
This is best handled on the #networktocode channel on Slack, sign up here: http://slack.networktocode.com/
