### ISSUE TITLE
error : templates not found

### ISSUE THREAD

**Issue by muradsabbah** [networktocode/ntc-templates#976]
Hello all,
i have this error when i try to clone  
murad2524625@ubuntu:~/netmiko-test$ gh repo clone networktocode/ntc-templates
Cloning into 'ntc-templates'...
warning: templates not found /usr/share/git-core/templates
fatal: Unable to find remote helper for 'https'
exit status 128

##### ISSUE TYPE

 - Bug Report
 - Feature Idea
 - Documentation Report

##### TEMPLATE USING

```

```

##### SAMPLE COMMAND OUTPUT

```

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by itdependsnetworks** [comment]
This seems like a local git issue.
