### ISSUE TITLE
Issue with Cisco WLC show exclusionlist

### ISSUE THREAD

**Issue by hagleyj** [networktocode/ntc-templates#993]
Existing Template is:
Value MAC (([\da-fA-F]{2}[-:]){5}[\da-fA-F]{2})
Value COMMENT (.*)

Start
  ^Manually\s*Disabled\s*Clients -> ManuallyDisabled
  ^No\s*dynamically
  ^\s*$$
  ^. -> Error

ManuallyDisabled
  ^---
  ^MAC\s+Address\s+Description
  ^${MAC}\s+${COMMENT} -> Record
  ^\s*$$ -> Start

Template should be:

Value MAC (([\da-fA-F]{2}[-:]){5}[\da-fA-F]{2})
Value COMMENT (.*)

Start
  ^Manually\s*Disabled\s*Clients -> ManuallyDisabled
  ^No\s*dynamically
  ^\s*$$
  ^. -> Error

ManuallyDisabled
  ^\s*$$
  ^---
  ^MAC\s+Address\s+Description
  ^---
  ^${MAC}\s+${COMMENT} -> Record
  ^\s*$$ -> Start

**Comment by itdependsnetworks** [comment]
Seems like you have a fix, please put in a PR, but will close this one as it is not filled out per template
