### ISSUE TITLE
cisco-ios, show authentication session not parsing

### ISSUE THREAD

**Issue by derekavieira** [networktocode/ntc-templates#996]
##### ISSUE TYPE

 - Bug Report

##### TEMPLATE USING

```

```

##### SAMPLE COMMAND OUTPUT

```

```

##### SUMMARY
it looks like in newer IOS code Cisco has added a line of dashes which is interfering with parsing

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by derekavieira** [comment]
Value INTERFACE (.+?)
Value MAC (.+?)
Value METHOD (.+?)
Value DOMAIN (.+?)
Value STATUS (.+?)
Value SESSION (\w+?)

Start
  ^Interface\s+MAC Address\s+Method\s+Domain -> Catch
  # Capture time-stamp if vty line has command time-stamping turned on
  ^Load\s+for\s+
  ^Time\s+source\s+is

Catch
  ^-+$$
  ^${INTERFACE}\s+${MAC}\s+${METHOD}\s+${DOMAIN}\s+${STATUS}\s+${SESSION}$$ -> Record
  ^.* -> Start

**Comment by derekavieira** [comment]
i had it in the issue, but if you exclude "-" in your show command it gets around the issue

switch#show authentication sessions | ex -
Interface                MAC Address    Method  Domain  Status Fg  Session ID
Tw5/0/11                 xxxx.xxxxx.xxxx mab     DATA    Unauth      9C80190A000019D50E1841B9

**Comment by diepes** [comment]
@derekavieira if you can provide the command assume it is "show authentication sessions"  and the raw output, we can add an additional test and fix the parsing.

**Comment by itdependsnetworks** [comment]
No response in a year for output, closing
